### ISSUE TITLE
model information

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#1]
I suggest we start with the lowest level packages. If I understood it, a package for accessing model information (name needed, insight or inside?) would encompass sjstats functions like `model_frame()` or `pred_vars()` etc?

Do we want to use those names or reimplement the functions from scratch, using the code base, but new names and reducing dependencies? I would say the latter, maybe we can come up with new names then...

**Comment by DominiqueMakowski** [comment]
Awesome, I'll have a look!

Note: we should probably rename `re_terms` to something like `model_random` to keep consistency. However, then it becomes indeed ambiguous whether we want to access the names or the values (same for model_respones model_predictors). So... maybe we should add "terms" to the functions, such as `model_terms_predictors`, have the three variants (predictors, response and random) and the "general" `model_terms()` that returns all the terms from the formula. Or if you feel that model_terms_foo is too long, maybe just `terms_foo` would do?

**Comment by strengejacke** [comment]
I think three words are too long, so I would go for `model_*()` for those functions. If we get data, we could use a `*_data()` suffix, like `model_data()`. The corresponding function name for the response value could be `reponse_data()`. `model_terms()` should be reserved for the wrapper that returns the names of all variables: response, predictors and random effects.

**Comment by DominiqueMakowski** [comment]
So you suggest `model_foo()` to have the terms and `foo_data()` to have the values?

**Comment by strengejacke** [comment]
Yes, that is what I currently prefer. It allows us to be consistent, with the first string in the function name referring to the _object_ the function refers to, and the second string being the information retrieved (data, terms, predictors...). Would you agree, or are other function names probably more feasible and intuitive?

**Comment by DominiqueMakowski** [comment]
you're right, this logic makes sense. So we would have:

- Individual:
  - model_predictors & predictors_data
  - model_response & response_data
  - model_random & random_data 
- Meta:
  - model_terms & model_data

**Comment by strengejacke** [comment]
Yes. Or we have a certain prefix for tasks: `get_*()` would return _data_, while `model_*()` would return _names_ or _information_...

I will work on implementing the methods, but we should think about this once more, and if needed, refactor/rename the functions later.

**Comment by DominiqueMakowski** [comment]
maybe something like

- Individual:
  - name_predictors & data_predicors
  - name_response & data_response
  - name_random & data_random
- Meta:
  - and then `name(model)` and `data(model)` would all return a list with all the `name_*` and `data_*`, respectively.

In general there would be one *main* function (`foo()`) which would return all the specific subfunctions (`foo_x`, `foo_y` etc.). The prefix would be related to what we want and the eventual suffix to where we want it (i.e. applied to what), and no suffix would mean "in general"/"to the entire model".

**Comment by strengejacke** [comment]
`data()` is a reserved functions, `name()` is very similar to `names()`.

Now that I have revised all functions and have a running prototyp to commit (later tonight), I feel like your suggestion here #issuecomment-458886087 are good choices. They contain the word `model()` resp. terms that are related to models (response, predictors, random). This seems to me a bit more natural when I think about a function and what it does.

Meanwhile, `get_*()` seems a bit generic to me.

**Comment by strengejacke** [comment]
Ok, I have committed the first "working draft" of the package. All current tests (mostly copied from sjstats, little bit revised) pass well, package-check (R CMD check) says all is OK. I think we can now start with the dev-branches...

**Comment by DominiqueMakowski** [comment]
Wouldn't it be more consistent to have:
- model_predictors & data_predictors
- model_response & data_response
- model_terms & data_*model* (?)

All functions either starting by model_ or by data_ depending on whether we want to access the "names" or the "values".

Also, I am wondering if it wouldn't be simpler for further usage if model_terms returned a list or a named vector, e.g., list("predictors" = predictors, "response"=response, "random"=random). 

We could then use it as:
```r
terms <- model_terms(fit)
do_some_stuff(terms$response, terms$predictors)
```

which is shorter than:
```r
predictors <- model_predictors(fit)
response <- model_response (fit)
do_some_stuff(response, predictors)
```
and more stable than:
```r
terms <- model_terms(fit)
do_some_stuff(terms[1], tail(terms, -1))
```

**Comment by strengejacke** [comment]
Regarding naming, I see the point. And I think it's indeed a good idea to have a common prefix. Yet, `data_*()` feels strange to me, maybe we should go for `get_*()`?

- model_predictors & get_predictors
- model_response & get_response
- model_terms & get_data

Or the long-form, `get_model_predictors()`, but it might be ok to have the short form.

**Comment by DominiqueMakowski** [comment]
or maybe contrast find_ with get_, e.g. `find_predictors()` and `get_predictors()`, find would "find" the name of the stuff, and get_ would actually get it?

**Comment by strengejacke** [comment]
yeah, that sounds good!
