### ISSUE TITLE
add effects and component args to find_parameters()

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#104]
Currently, `find_parameters()` has no arguments `effects` and `component` for mixed models or stan models. I saw @DominiqueMakowski using `find_parameters(model, effects, component)` in _bayestestR_, and indeed, it's a bit confusing that we don't have these arguments here.

Should we add them?

**Comment by strengejacke** [comment]
Sorry, I meant `find_parameters()`.

**Comment by DominiqueMakowski** [comment]
My bad I just mindlessly used the code for specifying parameters for models. Indeed, one would expect `find_` and `get_` to be the same argument wise.

**Comment by strengejacke** [comment]
It's pretty straighforward, just some stupid typing... We just need to add these codeline everywhere where applicable, I think (assuming `pars` is the list with all parameters):

```r
elements <- .get_elements(effects, component)
lapply(pars, function(i) i[elements])
```

**Comment by strengejacke** [comment]
hm, it's some _very long_ stupid typing... ^^

**Comment by DominiqueMakowski** [comment]
😅
