### ISSUE TITLE
get_priors for brms: flat priors

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#105]
``` r
library(brms)
model <- insight::download_model("brms_mixed_1")
insight::get_priors(model)
#> Model was fitted with uninformative (flat) priors!
#>   parameter distribution location scale
#> 1        wt
```

<sup>Created on 2019-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Currently, this returns a dataframe with characters (and empty character strings where nothing is there).

In the case of flat priors, would be possible to add "uniform" in the `distribution` column and NaNs in the others (instead of empty character strings)?

**Comment by strengejacke** [comment]
doesn't a uniform prior still have location 0?

**Comment by DominiqueMakowski** [comment]
I am not sure it has a location, as it is defined by the range :)

**Comment by strengejacke** [comment]
Range is `Inf`. :-)
