### ISSUE TITLE
Function behaviour

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#11]
Please check this "demo":
http://rpubs.com/sjPlot/insight-glmmtmb

- What should be the defaults? Lists or character vectors as return value?
- What should be the defaults: All values, conditional model only etc. (so what would be useful defaults for `effects` and `component`)?

We have to check all functions carefully and make sure that not accidentally a value is returned where no value is to be expected (e.g. no `"zi"`-component for linear (mixed) models).

**Comment by DominiqueMakowski** [comment]
I like the current behaviour a lot, great work!
I think the current defaults are also good. 

I am just wondering if the "cond, and "disp" shortcuts are necessary for the output. I think I understand that you want to mimic the behaviour of the `component` parameter of glmmTMB (taking in "zi", "disp" or "cond"). It could still be accepting both full names and short names as arguments (the same way cor.test accepts "bonf" and "bonferonni"). But in the output, unless I'm missing something, wouldn't it be more natural to have the full names conditional and dispersion? Again, that preference might be biased by my absence of experience with these models 😬

**Comment by strengejacke** [comment]
Yes, probably for the output it makes more sense to get the full name for the return values. What would you use for `zi` as output? `zero_inflation`, `zero_inflated` or `zero-inflated` or whatsoever?

For the arguments, I could use the long-form as well, as they can be abbreviated by the user (due to `match.arg()`).

**Comment by DominiqueMakowski** [comment]
for zi I have no opinion... either zero_inflation or zero_inflated (which makes sense if it refers to the zero_inflated- part of the model)

**Comment by strengejacke** [comment]
Little update (new URL)
http://rpubs.com/sjPlot/insight-glmmtmb2

**Comment by strengejacke** [comment]
Ok, I think we can close this now, as we have the functions work like we planned. Next step would be more tests to check if the functions work for all model packages. I think we can use the test-file for the `lmer()`-function as a template for other model-functions.

**Comment by DominiqueMakowski** [comment]
@strengejacke I am truly amazed and impressed by all your work, its pace and quality 👏
