### ISSUE TITLE
get_response: rename "resp" arg?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#114]
I just realised that `get_response` has the `resp` arg: "Optional names of response variables for which to extract values." It took me a few seconds to identify what its purpose was; it might be more transparent to call it something like "select" (which is also the term used in other places, e.g. standardize.data.frame) and reformulate its definition, saying that it can be used to select the response variable in case of multivariate regressions.

If worried about the breaking change, we could introduce the new arg and keep the old one for one release, deprecating the usage of the latter, to ease the transition.

Sorry to have missed that earlier.

**Comment by strengejacke** [comment]
Not sure if it really breaks changes, I must check that. I'm also not very satisfied with the name, I think initially the choice was based on brms, where you have a `resp` name in a similar context.
