### ISSUE TITLE
format_table and conditional print_colour

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#124]
I think we should move [format_table](https://github.com/easystats/parameters/blob/master/R/format_table.R) to insight so it can be used by parameters and performance (and bayestestR) and add a [print_colour_if](https://github.com/easystats/report/blob/master/R/display_colours.R#L155) (or `condition` as an argument in `print_colour`) so we can outsource and clean up the report tables with coloured cell. What do you think?

**Comment by DominiqueMakowski** [comment]
And eventually [format_value](https://github.com/easystats/parameters/blob/master/R/format_value.R), as it might be handy in performance.

**Comment by strengejacke** [comment]
I think format_value and print_color_if are handy tools to have them available for all packages (and thus located in insight), but I'm not sure if we need format_table everywhere? Currently, I'm not aware of any tabular output (in a classicle "table" sense), where we would need visual separators between columns? But if you feel it's useful for bayestestR etc., we can have it in insight as well...

**Comment by DominiqueMakowski** [comment]
It could indeed be used in bayestestR for describe posterior. Moreover, it's not just about separations (that can be deactivated):

``` r
cat(parameters::format_table(iris, sep=" "))
#> Sepal.Length Sepal.Width Petal.Length Petal.Width    Species
#> ------------------------------------------------------------
#> 5.1                  3.5          1.4         0.2     setosa
#> 4.9                    3          1.4         0.2     setosa
#> 4.7                  3.2          1.3         0.2     setosa
#> 4.6                  3.1          1.5         0.2     setosa
#> 5                    3.6          1.4         0.2     setosa
#> ... 
```

<sup>Created on 2019-07-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It's also a wrapper to justify the cols and all ^^ Critically, it would be good to expand it again (you sort of achieved it initially in report) to support colours and all. We could also add a bit more flexibility, allowing the user to tweak other aspects than only the column separation. I feel like it would fit more in insight with the other core cross-functions than with parameters.

**Comment by strengejacke** [comment]
Shall I for now simply copy the files to insight, and we keep improving them here?

**Comment by DominiqueMakowski** [comment]
id say so

**Comment by strengejacke** [comment]
I think `print_color_if()` should be named differently, as currently `print_color()` directly uses `cat()` and does not just return the color code. But this is needed for `colour_if()`, so maybe we should the function just name like that, and not `print_color_if()` (as this implies directly printing via `cat()`).

**Comment by DominiqueMakowski** [comment]
I agree!
