### ISSUE TITLE
feature request: introduce `get_statistic` function

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/insight#126]
This feature request is clearly from a developer perspective where creating meta-functions that deal with regression model objects will be easier.

I often use `broom::tidy` to get a tidy dataframe or results from regression model objects. This makes it easy to write wrapper functions dealing with regression objects because the output is consistent across functions.

``` r
# model
mod <- stats::lm(data = mtcars, formula = wt ~ am)

# statistic is t
summary(mod)

#> Call:
#> stats::lm(formula = wt ~ am, data = mtcars)
#> 
#> Residuals:
#>     Min      1Q  Median      3Q     Max 
#> -1.3039 -0.3694 -0.2049  0.3156  1.6551 
#> 
#> Coefficients:
#>             Estimate Std. Error t value Pr(>|t|)    
#> (Intercept)   3.7689     0.1646  22.895  < 2e-16 ***
#> am           -1.3579     0.2583  -5.258 1.13e-05 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Residual standard error: 0.7175 on 30 degrees of freedom
#> Multiple R-squared:  0.4795, Adjusted R-squared:  0.4622 
#> F-statistic: 27.64 on 1 and 30 DF,  p-value: 1.125e-05

# tidy output - unclear what the statistic is
broom::tidy(mod)

#> # A tibble: 2 x 5
#>   term        estimate std.error statistic  p.value
#>   <chr>          <dbl>     <dbl>     <dbl>    <dbl>
#> 1 (Intercept)     3.77     0.165     22.9  1.49e-20
#> 2 am             -1.36     0.258     -5.26 1.13e- 5
```

Note here that it is not clear what the `statistic` column corresponds to. This might be obvious for oft-used model like `lm`, but will not be more esoteric objects (e.g., `aovlist` or `mclogit`).

Automating how to extract statistic might be easier for some model objects where they are consistent with the statistic used-

```r
  # models for which statistic is t-value
  t.mods <-
    c(
      "biglm",
      "cch",
      "coeftest",
      "drc",
      "felm",
      "gam",
      "gamlss",
      "garch",
      "glmmPQL",
      "gls",
      "gmm",
      "ivreg",
      "lm",
      "lm.beta",
      "lmerMod",
      "lmRob",
      "lmrob",
      "mlm",
      "multinom",
      "nlmerMod",
      "nlrq",
      "nls",
      "orcutt",
      "plm",
      "polr",
      "rlm",
      "rlmerMod",
      "rq",
      "speedglm",
      "speedlm",
      "svyglm",
      "svyolr"
    )

  # models for which statistic is z-value
  z.mods <-
    c(
      "aareg",
      "clm",
      "clmm",
      "coxph",
      "ergm",
      "glmmadmb",
      "glmmTMB",
      "lavaan",
      "mjoint",
      "mle2",
      "mclogit",
      "mmclogit",
      "negbin",
      "survreg"
    )

  # models for which statistic is F-value
  f.mods <- c(
    "aov",
    "aovlist",
    "anova",
    "Gam",
    "manova"
  )
```

But not for others where this needs to be dealt on a case-by-case (or rather package-by-package basis)-

```r
  # models for which there is no clear t-or z-statistic
  # which statistic to use will be decided based on the family used
  g.mods <- c(
    "glm",
    "glmerMod",
    "glmRob",
    "glmrob"
  )

  # t-statistic
  g.t.mods <- c(
    "quasi",
    "gaussian",
    "quasibinomial",
    "quasipoisson",
    "Gamma",
    "inverse.gaussian"
  )

  # for z-statistic, the families are going to be "binomial" and "poisson"
  # but package-dependent; `robustbase` gives z for "Gamma" family, e.g.
```

I am not sure how to implement this algorithmically (brute-force, like `is_model`, or something more intricate?) and we can think about it if there is interest in having such a function in `insight`.

**Comment by strengejacke** [comment]
I would say such a function is suitable for _insight_, but I would rather call it `find_statistic()`, because you find information, and don't get data.

> g.t.mods

Do you mix families and models here? Or were you referring to specific glm-families?

My feeling is that we could hardcode for known models (i.e. check if it inherits from one of your above listed classes), and else use `tryCatch()` on `summary()`, checking for column names, and see whether there is something like `Pr(>|t|)` or so.

**Comment by DominiqueMakowski** [comment]
> My feeling is that we could hardcode for known models (i.e. check if it inherits from one of your above listed classes), and else use tryCatch() on summary(), checking for column names, and see whether there is something like Pr(>|t|) or so.

I agree, sounds like the most clever approach. In case the model is unknown and harvesting the name unsuccessful, we could throw a warning *"this model's statistic is unknown by insight. Could you please report this at https://github.com/easystats/insight/issues/"*

**Comment by IndrajeetPatil** [comment]
Cool. I will start working on this now.
