### ISSUE TITLE
cleaning up lints

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/insight#128]
I have setup lint detector in #127 and there are a ton of lints in the code that need to be cleaned up. 
https://cran.r-project.org/web/packages/lintr/vignettes/creating_linters.html

I think this will be good for long-term code health and maintenance.

**Comment by strengejacke** [comment]
If it's possible to customize the cleaner, I would do that because imho not all suggested changes make sense or improve readability.

**Comment by strengejacke** [comment]
Since I removed lintr due to too "aggressive" cleaning, I think we can close this issue.
