### ISSUE TITLE
Column names

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#133]
@DominiqueMakowski Since insight was developed before we had our coding conventions, column names do not follow the convention of other easystats packages.

In most cases, `get_parameters()` or `find_parameters()` is used, where we have a `parameter` column, Should we try to change the package so it returns column names that match our coding conventions? It's really odd to always write `xy$Parameter`, but only for objects from _insight_ you write `xy$parameter`.

This would temporarily require for our packages to use something like `get_parameters(model)[[1]]`, until we have finished the code revision... But it also requires changes in a lot of places. What do you say?

- [ ] insight
- [x] bayestestR
- [x] performance
- [x] parameters
- [x] see

**Comment by DominiqueMakowski** [comment]
Mmh, I'd agree to harmonize! Even though it's indeed a bit of a hassle to replace $parameter by [[1]], but fortunately CTRL + F exists :)

**Comment by strengejacke** [comment]
I'm just checking, it seems that less packages / code chunks are affected as I initially thought...

**Comment by strengejacke** [comment]
You may crosscheck, but I think all instances of "get_parameters()" are fixed now, so that they refer to `[[1]]` etc. instead `$parameters`.

**Comment by strengejacke** [comment]
There was one instance in bayestestR that we forgot (https://github.com/easystats/bayestestR/commit/825e51f7a37034bceb6c9291cf10cde33f897e65), else all current CRAN packages should be prepared for this issue. It affects `effective_sample.MCMCglmm()`. Should we wait with renaming columns in insight, or just hope that between insight and next bayestestR update there's only a minimal chance that people run into this issue?

**Comment by strengejacke** [comment]
`get_priors()` should be fixed as well, affects _bayestestR_.

**Comment by DominiqueMakowski** [comment]
Mmh I don't know. Go with your feeling ☺️
