### ISSUE TITLE
is_zeroinf vs is_zero_inflated

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#136]
is there any difference between these two? in model_info?

**Comment by strengejacke** [comment]
no, it was first names is_zeroinf, and I later added an alias. We can remove `is_zeroinf` at some point. I think it's also mentioned in the docs?

**Comment by DominiqueMakowski** [comment]
sorry didn't take the time to read or to check 😬 
👍 for removing zeroinf as it could be confusing

**Comment by strengejacke** [comment]
To be safe, I think we can remove the alias _after_ the next update.
