### ISSUE TITLE
function for type of model

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#14]
I am thinking about a function that would return the model type in a clear and "human" way. For instance, "linear model", "logistic model", "probit model", "Bayesian mixed logistic model" etc., 

There could be a variant (`find_model(fit, short=FALSE)`) that returns the "full" name in a consistent manner, e.g. "general linear model (poisson family with a log link)", "general linear mixed model (gamma family with an inverse link)" and a variant  (short=TRUE) that returns the short names, i.e., "logistic model" instead of "general linear model (binomial family with a logit link)".

Besides its use in the future report package, it could be useful for users to add titles to plot, captions to table and so on. However, I think it has its place here, in the insight package. What do you think?

**Comment by strengejacke** [comment]
Yes, the basis for this is `model_info()`, which is already implemented. All we need (or maybe not, if it's better located in a "report"-package) is a nice `print()`-method that prints out human readable summayries.

**Comment by DominiqueMakowski** [comment]
You're right, it's better if we keep the basis to retrieve the elements here and the formatting wrapping into report!
