### ISSUE TITLE
Functions list

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#15]
![image](https://user-images.githubusercontent.com/8875533/52157445-045d8d80-26ca-11e9-824a-fdff3e690943.png)

This list of functions is becoming neat and consistent ☺️ 

I was just wondering about these two options:
- Rename `link_fun` for `link_function` 
- Add info from `find_terms` in `model_info()`; this last function would be a shortcut for finding all things this package provide. Sauron's One Ring 💍

**Comment by strengejacke** [comment]
We could include numbers of observations as well.
