### ISSUE TITLE
Backticks in Parameter names?

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#151]
@DominiqueMakowski Currently, functions like get_parameters() or get_predictors() return backticks in parameter names when these contain non-regular or whitespace character, but only for some models, not for all.

However I saw that backticks in names does not work well for some functions in _parameters_. Do we want to remove backticks in general for all functions that return a `Parameter` column? (And only for names in this column)

**Comment by DominiqueMakowski** [comment]
not sure what would be the consequences of this decision, but I'd say yes? what do you think?

**Comment by strengejacke** [comment]
Exactly the same thoughts. ;-) No idea about the consequences, but "yes" sounds good.

I'll wrap this code into a small function (`remove_backticks()` or so), and in case it doesn't work, we just let this function do nothing.

**Comment by strengejacke** [comment]
ok, _insight_ and _parameters_, and thereby also _effectsize_ are fixed now. I did not touch Bayesian models, because this will probably affect bayestestR. We must see if we want to change this behaviour for bayestestR as well.
