### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#17]
Ok, I list some model-functions or package names for which I think we still need tests (or add more tests), just to not forget anything:

- [x] lm
- [x] glm
- [x] pscl (hurdle, zeroinfl)
- [x] brms
- [x] rstanarm
- [x] nlme (lme, gls)
- [x] MASS (polr)
- [x] betareg
- [x] gam
- [x] vgam
- [x] Gam
- [x] gamm
- [x] gamm4
- [x] truncreg
- [x] nnet (multinom)
- [x] survey (svyglm)

Any important models I forgot or you would like to add?

**Comment by strengejacke** [comment]
For merMob-objects, `find_formula()` could be used to extract fixed and random effects formula as _seperate_ values (so this would differ from standard `stats::formula()` behaviour, but would be consistent with other models like `lme`, that save the random effects formula in a separate slot.

**Comment by strengejacke** [comment]
> We could also think of a vignette/section documenting how to implement the support for new models

And if we manage it to make all other functions just call `find_formula()`, and for random effects just extract the grouping variable, adding new models is extremely easy. They just need to add a `find_formula()`-function, and that's it.

**Comment by DominiqueMakowski** [comment]
Sounds brilliant 🙌 ! What a chance to be able to have a walk in the cold :)
How would this work for zi models?

**Comment by strengejacke** [comment]
- I think `find_formula()` should _always_ return a list, even for simple `lm`-objects (in this case, only one element names `conditional`).
- For more complex models, the list has more elements (random, zero_inflated, zero_inflated_random...).
- The function returns only as many elements as necessary, e.g. for a mixed model w/o zero-inflation, only `conditional` and `random` are returned.
- Existing functions can than always use `find_formula(x)[["conditional"]]` or `find_formula(x)[["zero_inflated"]]`, no matter which model is called. If the model has no such element, `NULL` is returned.

The only problem is the handling of merMod or glmmTMB-objects (or brms), because the formula contains both fixed and random effects (e.g. `Reaction ~ Days + (1 + Days | Subject)`. While it's easy to return only the random effects with `lme4::findbars()`, for the element `conditional` we need to remove the random effects from that formula.

A second thing to keep in mind is when we call `find_random()`, we need to check whether the `random` element contains a `|`, and if so, only return the grouping factor. But that's less a problem, as we do this currently anyway.

**Comment by strengejacke** [comment]
We really need only one generic of the other `find_*()`-functions, which just call something like `all.vars(find_formula(x, effects = "xy", component = "yz")` (except for random effects, where we need to extract the group factor from the formula). The behaviour of the functions - from a user perspective - doesn't change. But the underlying code is much simpler, easier to maintain and to enhance.

**Comment by strengejacke** [comment]
Ok, the crucial part is done now, I guess. I need to revise all tests now, because each `find_*()`-functions returns a list by default, but you have a `flatten`-argument for all those functions. That means, most tests currently fail because of the changed behaviour.

Once the tests are updated and the functions work as intended, we need to do some thorough testing of brms models, especially multivariate models, mixed models etc. I guess `find_formula()` does currently not capture these models properly.

**Comment by strengejacke** [comment]
I have added some more functionality to support brms and rstanarm. For brms, many models work. However, _insight_ fails for multivariate response models with random effects (models b13 and b14 in this example: http://rpubs.com/sjPlot/insight-brms).

**Comment by strengejacke** [comment]
I have updated http://rpubs.com/sjPlot/insight-brms - model b13 works now, and for model b14, the random-effects structure returns two random effects, due to its special case (where `ID` indicates correlated effects between random effects in multivariate-response models). This may cause some functions to fail, but I think we can be OK with this at the moment.

I'll close #12 for now, as it seems to be working. I'll still add some tests.

**Comment by DominiqueMakowski** [comment]
nice work

**Comment by DominiqueMakowski** [comment]
It seems that with a tweaked travis config file, insight [passes](https://travis-ci.org/easystats/insight) 🎉 (I dunno why but I really like the travis and codecov badges 😅).

However, I had to comment out the following tests that do not pass: 
- test-brms (all the file for now)
- test-glmmTMB: lines 136 and 137
- test-response_data2: lines 35 and 36

**Comment by strengejacke** [comment]
I think we can use the glm-template for new models. That should cover a lot of functions / cases...

**Comment by strengejacke** [comment]
I think I start liking codecov, because it raises awareness to missing tests.
