### ISSUE TITLE
model_info() and ordinal/multinominal/cumulative link models

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#183]
Currently, `model_info()` returns `TRUE` for `$is_ordinal` for models with ordinal outcomes (such as `MASS::polr()`), but also for multinominal models like `brglm::bracl()`. So, `$is_ordinal` just tells the user that the model has a categorical (factor) outcome with more than two levels. 

Should we be more exact here, so that `$is_ordinal` is only `TRUE` for models with _ordinal_ response variables, and `$is_multinominal` for models with unordered factors as response?

@DominiqueMakowski @mattansb @IndrajeetPatil @pdwaggoner

**Comment by mattansb** [comment]
> Should we be more exact here, so that $is_ordinal is only TRUE for models with ordinal response variables, and $is_multinominal for models with unordered factors as response?

👍

**Comment by pdwaggoner** [comment]
> Should we be more exact here, so that $is_ordinal is only TRUE for models with ordinal response variables, and $is_multinominal for models with unordered factors as response?

Yes, I think we should be more exact as ordered vs. unordered categories is not a trivial difference, as we all know well. It would be a good idea, in line with the easystats approach, to be as explicit and clear about these things as possible, especially for users who may be less familiar/comfortable with more advanced statistical techniques.
