### ISSUE TITLE
ger_priors fails when flat intercept priors

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#184]
which makes, in turn, fail `model_parameters()`.
```r
model <- stan_glm(disp ~ carb, data=mtcars, priors=NULL, prior_intercept=NULL)
insight::get_priors(model)
```
```
 Error in `$<-.data.frame`(`*tmp*`, "parameter", value = c("(Intercept)",  : 
  replacement has 2 rows, data has 0 
```

**Comment by strengejacke** [comment]
what would be the desired result for flat priors?

**Comment by strengejacke** [comment]
distribution uniform, location 0 and scale Inf?

**Comment by DominiqueMakowski** [comment]
> distribution uniform, location 0 and scale Inf? That seems reasonable, or even NaNs for location and scale as these non-applicable parameters for a uniform distrib

**Comment by DominiqueMakowski** [comment]
Do you think about updating insight on CRAN anytime soon?

**Comment by strengejacke** [comment]
As I got a mail due to failing checks, yes. The next days.
