### ISSUE TITLE
Check link_inverse for MCMCglmm

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#190]
Yes, MCMCglmm hides the link-inverse function quite well, must dig a bit more into the details.

_Originally posted by @strengejacke in https://github.com/strengejacke/ggeffects/issues/130#issuecomment-609750253_

**Comment by strengejacke** [comment]
@IndrajeetPatil @mattansb @DominiqueMakowski anyone who has some time to figure out the different families and what link functions should be returned (but currently are not)?

**Comment by mattansb** [comment]
I think we should at least have the families and links in `?family`...?

(But if anyone wants to go into all the families provided `brms`....😅)

**Comment by strengejacke** [comment]
MCMCglmm has some special families, and AFAIK no `family()` method.
