### ISSUE TITLE
format_value() should consider "options(OutDec=',')" for separator formatting

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#193]
See https://github.com/strengejacke/sjPlot/issues/622 and https://stat.ethz.ch/R-manual/R-devel/library/base/html/options.html.

**Comment by strengejacke** [comment]
@DominiqueMakowski I think this is a bit more work. `sprintf()` always returns a `.` as decimal separator, while `format()` uses `getOptions("OutDec")` as default separator. I'm not sure if you can specify a decimal-separator in `sprintf()` as well? I would rather set this issue to low priority if it's too much hassle for a quick fix.

**Comment by bwiernik** [comment]
Here is my `format_num()` function that handles decimal separators, big and small number separators (commas, dots, thin spaces), negative and positive signs, infinite signs, etc. https://github.com/psychmeta/psychmeta/blob/45fc4e2a1553a1ffa8cb57d9d5929cb6d469c766/R/output.R#L54
