### ISSUE TITLE
get_variance formula citation

### ISSUE THREAD

**Issue by GallVp** [easystats/insight#197]
Dear authors

Thank you for your awesome work. I am writing to you in reference to the following statement in the [get_variance](https://easystats.github.io/insight/reference/get_variance.html) guide:

For all other models, the distribution-specific variance is based on lognormal approximation, log(1 + var(x)/u^2), (see Nakagawa et al. 2017). However, I was unable to find this equation in the cited article. Can you kindly add additional information to the citation?

Moreover, there seems to be some discrepancy in distribution variance computed by `get_variance` and the method suggested by Nakagawa et al. 2017 for `glmer` model with Gamma family and log link. Following code is from heading 3.3 in the supplementary file accompanying Nakagawa et al. 2017.

```R
DataAll <- read.csv('DataAll.csv')
# Fit alternative model including fixed and all random effects
sizemodeGLMERf <- glmer(BodyL ~ Sex + Treatment + Habitat + (1 | Population) +
(1 | Container), family = Gamma(link = log), data = DataAll)
# Calculation of the variance in fitted values
VarF <- var(as.vector(model.matrix(sizemodeGLMERf) %*% fixef(sizemodeGLMERf)))
# Full model
nuF <- 1/attr(VarCorr(sizemodeGLMERf), "sc")^2
VarOdF <- 1/nuF # the delta method
VarOlF <- log(1 + 1/nuF) # log-normal approximation
VarOtF <- trigamma(nuF) # trigamma function
# comparing the three
c(VarOdF = VarOdF, VarOlF = VarOlF, VarOtF = VarOtF)
```

Result from above:
VarOdF
0.007088892
 VarOlF
0.007063884
VarOtF 
0.007114078

Results from `get_variance(sizemodeGLMERf)`:

$var.fixed
[1] 0.01196684

$var.random
[1] 0.002308591

$var.residual
[1] 3.735298e-05

$var.distribution
[1] 3.735298e-05

$var.dispersion
[1] 0

$var.intercept
Container              Population 
0.0013995269      0.0009090637 

#### Data

[DataAll.csv.zip](https://github.com/easystats/insight/files/4537059/DataAll.csv.zip)

### References

* Nakagawa, S., Johnson, P. C. D., & Schielzeth, H. (2017). The coefficient of determination R2 and intra-class correlation coefficient from generalized linear mixed-effects models revisited and expanded. Journal of The Royal Society Interface, 14(134), 20170213. doi: 10.1098/rsif.2017.0213

#### R

platform       x86_64-apple-darwin19.4.0   
arch           x86_64                      
os             darwin19.4.0                
system         x86_64, darwin19.4.0        
status                                     
major          3                           
minor          6.3                         
year           2020                        
month          02                          
day            29                          
svn rev        77875                       
language       R                           
version.string R version 3.6.3 (2020-02-29)
nickname       Holding the Windsock  

#### lme4 1.1-21

**Comment by strengejacke** [comment]
Thanks @GallVp for pointing this out. Indeed, there was a comment for "Gamma" family stating that some more checks are needed. I've revised the function, so it should now be in line with the results from Nakagawa et al. Also, the r-squared for gamma models is now in line with packages like MuMIn.

>  log(1 + var(x)/u^2)

u should be mu, just to clarify. I can't help you that much, actually, because the implementation of the variance functions is based on a code from one of the lme4-authors, who allowed us to use his code, and this was one of his comments. Indeed, the code includes `log1p(vv / mu^2)`, which is `log(1 + var(x)/mu^2)`, and this leads to the same results for log-approximation as Nakagawas code:

``` r
DataAll <- read.csv('~/../Desktop/DataAll.csv')
library(insight)
library(lme4)
#> Loading required package: Matrix

m <- glmer(BodyL ~ Sex + Treatment + Habitat + (1 | Population) +
             (1 | Container), family = Gamma(link = log), data = DataAll)

get_variance(m)
#> $var.fixed
#> [1] 0.01196684
#> 
#> $var.random
#> [1] 0.002308591
#> 
#> $var.residual
#> [1] 0.007088892
#> 
#> $var.distribution
#> [1] 0.007088892
#> 
#> $var.dispersion
#> [1] 0
#> 
#> $var.intercept
#>    Container   Population 
#> 0.0013995270 0.0009090637
```

<sup>Created on 2020-04-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
