### ISSUE TITLE
Some suggested packages no longer exist on CRAN

### ISSUE THREAD

**Issue by yrosseel** [easystats/insight#198]
(This came up during a revdep check of lavaan)

The package 'HRQoL'  is listed in the Suggests: field of the DESCRIPTION file, but is no longer available on CRAN. As a result, checking fails unless _R_CHECK_FORCE_SUGGESTS_ is set to TRUE.

**Comment by strengejacke** [comment]
Thanks for the pointer. HRQoL was already removed [here](https://github.com/easystats/insight/commit/2e139183531f68a0a4bbd9ffd6b09ac2e196a2ba) (though not yet on CRAN), and _splines_ is still a library, but shipped with R itself, I think. So suggesting _splines_ should still be no problem.

**Comment by yrosseel** [comment]
You responded as I was editing my initial issue (as I realized that splines indeed is part of base R).  But indeed, it is already fixed in dev. Never mind.
