### ISSUE TITLE
R-version dependency

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#20]
I just saw that I simply copied the dependency R >= 3.2 - but is this really necessary? Can't we just reduce that dependency even further?

**Comment by DominiqueMakowski** [comment]
I haven't even specified the need for `stats` in other packages (even though I still call it) and it seems to work as expected... So I guess we could remove all deps

**Comment by strengejacke** [comment]
I'm not sure if you can submit a pkg w/o any specification... But I reduced it to R >= 3.0, I guess that should be ok to potentially reach many users.
