### ISSUE TITLE
find_formula.glmmTMB has some problem (after last update?)

### ISSUE THREAD

**Issue by iago-pssjd** [easystats/insight#208]
I have a model for which
```
> fitflu$call
glmmTMB(formula = NEW_CASES ~ offset(log(DP05_0001E)) + (1 | 
    DAYSFIRSTCASE) + INTER_LEV4 + (1 | INTER_LEV4:DAYSFIRSTCASE) + 
    Rural_urban_Continuum_Code_2013 + DP05_0024PE + DP05_0024PE:vac1819_gt65y + 
    (1 | FIPS) + DSL, data = data, family = "nbinom2", REML = TRUE, 
    ziformula = ~0, dispformula = ~1)
```
and I didn't get `ggeffects` to work. So, following the error message I arrived to:
```
> insight::find_predictors(fitflu)
$conditional
[1] "DP05_0001E" "DSL"    
```
I am trying to build a reproducible example, but without success until now.

**Update**

I see that the problem is in `find_formula`:
```
> insight:::find_formula.glmmTMB(fitflu)
$conditional
NEW_CASES ~ offset(log(DP05_0001E)) + DSL
<environment: 0x55ab151766d8>

$random
$random[[1]]
~1 | DAYSFIRSTCASE
<environment: 0x55ab1512fac0>

$random[[2]]
~1 | INTER_LEV4:DAYSFIRSTCASE
<environment: 0x55ab15123638>

$random[[3]]
~1 | FIPS
<environment: 0x55ab231d4e30>

```
**Update 2**:
In `.get_fixed_effects`, in the `if (grepl("|", f_predictors, fixed = TRUE)) `, the `if` and the `else if(!grepl("\\+(\\s)*\\((.*)\\)", f_string))` conditions are FALSE. Finally, in the `else`, I get
```
> .trim(gsub("\\+(\\s)*\\((.*)\\)", "", f_string))
[1] "NEW_CASES ~ offset(log(DP05_0001E))  + DSL"
```
I do not understand these conditions, but if intead of using 
```
gsub("\\+(\\s)*\\((.*)?\\)", "", f_string)
```
was added an `?` as follows:
```
gsub("\\+(\\s)*\\((.*?)\\)", "", f_string)
```
it seems it would solve this problem. But I'm not sure it would generate another problems.

Thank you!

**Comment by strengejacke** [comment]
Possibly related to https://github.com/easystats/insight/issues/79

**Comment by iago-pssjd** [comment]
Yes, if the example in issue #79 also arrives to some expression `gsub("\\+(\\s)*\\((.*)\\)", "", f_string)` then the offset, as it finishes with ')' would be hided by it.
