### ISSUE TITLE
CRAN submission

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#21]
Ok, what would be the remaining goals before we initially submit to CRAN. beside some open issues like #4, #5, #17 and #19?

I would like to submit to CRAN soon, within this month probably, unless we have more major functionality to add, and go continue working on the next pkg, e.g. bayestestR or report. And I would start using insight in my other packages for the next release cycle...

- [x] passing CRAN checks
- [x] docs are fine

**Comment by DominiqueMakowski** [comment]
Agree. The only remaining things that I can think of that would need to be eventually discussed is the extraction of other data components, such as residuals (`get_residuals()`?) and random effects related stuff (correlation structure?). However, they are not a priority so we can consider pushing an initial release without it.

**Comment by strengejacke** [comment]
residuals is a goot idea. I hope that most models return those via `stats::residuals()`, but we will see. There are different type of residuals, should we focus on specific types, or return all available types? I'm not sure when to use which residuals (Pearson's, scaled, ...), and which are returned by the different model objects by default.

**Comment by DominiqueMakowski** [comment]
Haven't thought about the residuals type... Maybe we can add the most "default" (useful?) one (the one returned by `stats::residuals()`?), and if ever someone asks or require more, we will expand this function accordingly?

**Comment by strengejacke** [comment]
If I understand codecoverage right, it checks which parts of the code are affected by tests, and which parts are probably not covered by tests, right?

If so, I'm afraid it's difficult to get 100% coverage... But that's not that important, or is it?

**Comment by DominiqueMakowski** [comment]
Indeed, on the coverage website, it lists all files and a percentage of coverage, if you click on these files you can see which lines are covered.

It is mostly a "general index" rather than a precise and accurate thing, as it doesn't say whether the tests actually good (it considers it good as long as anything runs through a line), and sometimes it won't catch everything (such as here in the brms file, deactivated on travis). 

As for the goal, ropensci says that [*"It is good practice to write unit tests for all functions, and all package code in general, ensuring key functionality is covered. Test coverage below 75% will likely require additional tests or explanation before being sent for review"*](https://ropensci.github.io/dev_guide/building.html). However, as some packages are inherently more difficult to test than others, I think it is again a very general aim. Quality should be more important than the coverage percentage, which I see as a tool to help us write tests and hint us if we missed something.

**Comment by strengejacke** [comment]
More than 75% coverage is doable. Once we have added tests for more models, the S3 are mostly covered.

Maybe we can remove some `tryCatch` code blocks where these are probably really not needed, but I'm a bit paranoid of missing exceptions, and I prefer to return `NULL` instead of getting an error.

Eg here
https://github.com/easystats/insight/blob/master/R/n_obs.R#L60
I think that try catch can be safely removed (which also increases test coverage).

**Comment by strengejacke** [comment]
I think we can skip #19 for now and address that issue for another future update. For now, we should close #4, #5 and #17

**Comment by strengejacke** [comment]
Ok, all tests pass well. I would like two things to check, and then go for submission:

1) docs / help-file (see #4)
2) vignette - do we need vignettes at this stage anyway?

**Comment by DominiqueMakowski** [comment]
In my opinion in general (besides the CRAN milestone), documentation for this package should importantly include:

- Short presentation of the syntax and goal (i.e. "most of the functions starts by find_ or get_ which respectively retrieve names or data")
- List of functions
- Examples demonstrating the usecase (could be incorporated in the function list)
- List of supported models
- Vignette about how to add support for new models

Most of the items (but the last one?) could fit on the readme page, offering a direct view of the capabilities 💪

**Comment by strengejacke** [comment]
Do you have the time to propose a revision of the read.me file?

**Comment by DominiqueMakowski** [comment]
Yes will try today

**Comment by DominiqueMakowski** [comment]
I've experimented a bit and think the most straightforward approach is to list the functions with a link to their docs where there are examples. Indeed, all the functions are very transparent in terms of what they do, so showing on the readme an example of `get_data()` seemed a bit useless.

Also for the installation, I think it's more streamlined and relevant just to have the link of the github installation, and once on CRAN we will simply add the CRAN badge. The rationale is that people wandering on github already know how to install packages from CRAN (it's literary the first thing you learn on R), so what the really need is just the link of the repo to copy paste it to R. Also, if we stick to the master/dev branches, we can assume that the master will always be pretty stable, so there shouldn't be a problem to direct users to it.


There is still the need to:
- Double check and complete the list of supported models (btw, I didn't see gamm4 :)?
- Completing the `supporting_new_models` vignette.
- Should `is_multivariate` be internal (see picture)?

![image](https://user-images.githubusercontent.com/8875533/52829185-b8b5d580-3106-11e9-91e0-58eef2f2be3d.png)

**Comment by strengejacke** [comment]
> btw, I didn't see gamm4

gamm4 returns a list of two objects, merMod and gam. So typically you call the methods with `model$gam`. Since the class of the returned object is a list, I'm not sure if we should check for this kind of list-objects?

**Comment by DominiqueMakowski** [comment]
mmh that's a good point. We can mark it for the 0.2 milestone to give us some time to think about it, because it would be nevertheless a nice addition directly supporting gamm4 returns.

**Comment by strengejacke** [comment]
Ok, gamm and gamm4 should work now, however, only for the `gam`-component of the model. The random parts are really strange, I'm not sure if it's necessary to return the random formula as well, and I'm not sure how to do this properly. Maybe we can for now live with this implementation, and think about random stuff for gamm/gamm4 in a later update.

Tests are missing, though...

**Comment by strengejacke** [comment]
Let me give an example:

Here's the model fit:

```r
gamm4(y~s(x0)+x1+s(x2),data=dat,random=~(1|fac))
```

and here's the formula:

```r
formula(br$mer)
#> y.0 ~ X - 1 + (1 | Xr) + (1 | Xr.0) + (1 | fac)
```

I'm not sure how to extract the information properly, and what exactly is needed here. `Xr` were not specified in the random effects formula.

**Comment by strengejacke** [comment]
For gamm4, we maybe could work with `getME(br$mer, "flist")`.

**Comment by DominiqueMakowski** [comment]
Yes, a first even partial, support is already awesome! We can still expand on it depending of future needs and demand ☺️

**Comment by strengejacke** [comment]
> * Should `is_multivariate` be internal (see picture)?

If possible, I would like to keep it as exported function, because multivariate response models require special treatment (due to the nested lists). Thus, it makes sense (and I need it in my packages as well) to be able to check this special case of model, and thus to provide a small function to do so. 

Especially against the background that also some objects returned by _insight_ function store the information if the results came from a multivariate model, and `is_multivariate()` also checks those cases, if necessary.

**Comment by DominiqueMakowski** [comment]
We could also export all the `is_*` functions :)

**Comment by strengejacke** [comment]
The other two are really only helper functions, that also exists in other packages (though function names are different)... But I'm fine with exporting those functions as well, as long as we don't export too many helpers.

**Comment by DominiqueMakowski** [comment]
You're right. Let's stick with that!

**Comment by strengejacke** [comment]
I'm doing a last check on a "real-version-number"-version (I temporarily changed the pkg version to 0.1.1, so Stan-tests are not computed), and I _hope_ all issues are resolved now...

**Comment by strengejacke** [comment]
next try... Local tests and Travis say it's ok, when CRAN also does so, I'd like to submit the initial package the next days, or tomorrow. What do you think? Too early? Functions now seem rather robust to me, at least for the range of models we already support.

**Comment by strengejacke** [comment]
Ok, still need to read the docs carefully again.

- [ ] passing CRAN checks
- [ ] docs are fine

**Comment by DominiqueMakowski** [comment]
I think it's more than ok for an initial submission ☺️  Polishing and edge cases fixing will come in the next milestones.

**Comment by strengejacke** [comment]
Ok, the pkg is on its way to CRAN...
