### ISSUE TITLE
clean_names with functioned interactions

### ISSUE THREAD

**Issue by mattansb** [easystats/insight#220]
These should all return `"a:b"`:

``` r

insight::clean_names("a:b")
#> [1] "a:b"
```

Miss….

``` r
insight::clean_names("a:scale(b)")
#> [1] "a:scale(b)"

insight::clean_names("scale(a):b")
#> [1] "a"

insight::clean_names("scale(a):scale(b)")
#> [1] "a"
```

<sup>Created on 2020-09-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Well, it works with model object:

``` r
m <- lm(mpg ~ wt * cyl + vs * log(hp) * sqrt(gear) + carb, data = mtcars)
insight::clean_names(m)
#> [1] "mpg"  "wt"   "cyl"  "vs"   "hp"   "gear" "carb"
```

<sup>Created on 2020-09-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The string-version usually thinks of the input as "column names", thus each string is considered as "one variable". Although there might be no column name in a model.frame() that contains a `:` (not sure though, but I think so)... So it's actually working as intended.

**Comment by strengejacke** [comment]
But maybe we can think if it would make sense to have an exception here and split strings by `:`.

**Comment by mattansb** [comment]
Would be nice if this could be used to clean parameter names (`attr(terms(m),"term.labels")`) as well.

To deal with interaction it could be, maybe, something like this?

``` r
x <- c("scale(a)", "scale(b)", "scale(a):scale(b)")


sapply(x, function(.x) {
  if (grepl(":", .x, fixed = TRUE)) {
    paste(sapply(strsplit(.x, ":", fixed = TRUE), insight::clean_names), collapse = ":")
  } else {
    insight::clean_names(.x)
  }
})
#>          scale(a)          scale(b) scale(a):scale(b) 
#>               "a"               "b"             "a:b"
```

<sup>Created on 2020-09-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
