### ISSUE TITLE
Check test

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#224]
This issue started appearing recently when running the tests:
https://github.com/easystats/insight/runs/1132649074#step:10:277

However, nothing particular has changed according to the afex package, and the afex package itself was also not updated. I'm not sure why this test fails.

So, @mattansb @DominiqueMakowski @IndrajeetPatil , can you please install the latest _insight_ from GitHub and then run this test:
https://github.com/easystats/insight/blob/master/tests/testthat/test-mixed.R

(**Note** that it is currently disabled by using `FALSE` in the if-statement...)

Does it work for you?

**Comment by strengejacke** [comment]
The tests also fail on CRAN: https://cran.r-project.org/web/checks/check_results_insight.html

However, only since yesterday or so. Before that, all check results were OK...

**Comment by mattansb** [comment]
Runs locally without any fails...

**Comment by strengejacke** [comment]
Seems to be resolved... In the same mystical way as it appeared?
