### ISSUE TITLE
get_weights returns weights when there are none

### ISSUE THREAD

**Issue by mattansb** [easystats/insight#228]
In both cases here the result should be `NULL`

(Affecting the dev of https://github.com/easystats/effectsize/issues/82)

``` r
library(lme4)
#> Loading required package: Matrix
m <- lmer(mpg ~ am + (1|cyl), mtcars)

insight::get_weights(m)
#>  [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1


library(rstanarm)
m <- stan_glm(mpg ~ am + cyl, mtcars, refresh = 0, family = gaussian())

insight::get_weights(m)
#> numeric(0)
```

<sup>Created on 2020-09-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Obviously, it's a design-decision:

``` r
library(lme4)
#> Loading required package: Matrix
m <- lmer(mpg ~ am + (1|cyl), mtcars)
weights(m)
#>  [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
```

<sup>Created on 2020-09-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

But we could check if all weights are 1, and if so, return NULL (with `all(weights(m) == 1L)` or so).

**Comment by mattansb** [comment]
Thanks!
