### ISSUE TITLE
get_auxiliary()

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#230]
Beside (or instead of) `get_sigma()` we might want to have a `get_auxiliary()` function. Any ideas which parameters this function could return?

**Comment by mattansb** [comment]
All the family (distribution) specific parameters. From the top of my head:

- The dispersion parameter in quasibinomial / quasipoisson / negative binom / Gamma / inverse.gaussian / etc,
- The various fixed (i.e. not modeled) distribution parameters in [`brms` families](https://cran.r-project.org/web/packages/brms/vignettes/brms_families.html) (`?brms::brmsfamily`) - all the single `dpar` types / parameters that don't start with `b_*`?

**Comment by strengejacke** [comment]
Could you be more specific and name the parameters? I'm not sure where to look to find these information right now...

**Comment by mattansb** [comment]
|                      Family       | Aux_param |
| --- | ---- |
|                   gaussian      |     sigma|
|                    student       |nu, sigma|
|                negbinomial   |        shape|
|                      Gamma     |      shape|
|                skew_normal   | alpha, sigma|
|                 lognormal      |     sigma|
|         shifted_lognormal |     ndt, sigma|
|                exgaussian     |beta, sigma|
|                    wiener        |      `NA` ??? |
|          inverse.gaussian  |         shape|
|                   weibull        |   shape|
|                   frechet        |      nu|
|                      Beta         |    phi|
|                 dirichlet        |      `NA` ??? |
|                 von_mises    |       kappa|
|              asym_laplace |quantile, sigma|
|         gen_extreme_value |      sigma, xi|
|               multinomial       |       `NA` ??? |
|            hurdle_poisson       |       hu|
|        hurdle_negbinomial  |     hu, shape|
|              hurdle_gamma      | hu, shape|
|          hurdle_lognormal     |  hu, sigma|
|    zero_inflated_binomial   |           zi|
|        zero_inflated_beta       |  phi, zi|
| zero_inflated_negbinomial  |     shape, zi|
|     zero_inflated_poisson      |        zi|
|    zero_one_inflated_beta  | coi, phi, zoi|


Having trouble finding for these: `multinomial`, `wiener`, `dirichlet`, will try again later.

**Comment by strengejacke** [comment]
I'm afraid I need some examples for models with:

- alpha
- xi
- hu
- shape
- phi
- ndt
- coi
- zoi

to know the pattern of column names to extract those parameters.

**Comment by DominiqueMakowski** [comment]
Sounds like klingon to me

**Comment by strengejacke** [comment]
I actually have a dictionary Klingon-German...

**Comment by strengejacke** [comment]
Who would like to contribute here? https://github.com/easystats/insight/issues/230#issuecomment-749715865

@IndrajeetPatil @mattansb @DominiqueMakowski  :-)

**Comment by mattansb** [comment]
Sorry.... Don't know any of these....
