### ISSUE TITLE
include sigma in get_parameters for Bayesian non-mixed models?

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#232]
> I'm not sure it's necessary to display it by default in `model_parameters()` (I think that most people would _not_ expect it in the default parameters)

Why not? This is nothing particular new and always worked for Bayesian mixed models, now it works for non-mixed as well. I'm currently reading https://avehtari.github.io/ROS-Examples/, and this convinced me including information on residual standard deviation as default for `model_parameters()`:

``` r
library(parameters)
model <- lm(mpg ~ wt + cyl, data = mtcars)

model_parameters(model)
#> Parameter   | Coefficient |   SE |         95% CI |     t | df |      p
#> -----------------------------------------------------------------------
#> (Intercept) |       39.69 | 1.71 | [36.18, 43.19] | 23.14 | 29 | < .001
#> wt          |       -3.19 | 0.76 | [-4.74, -1.64] | -4.22 | 29 | < .001
#> cyl         |       -1.51 | 0.41 | [-2.36, -0.66] | -3.64 | 29 | 0.001 
#> 
#> Residual standard deviation: 2.57
```

<sup>Created on 2020-09-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

But I'm open for other suggestions.

_Originally posted by @strengejacke in https://github.com/easystats/bayestestR/issues/338#issuecomment-697249869_

**Comment by strengejacke** [comment]
So, back to topic, in the light of https://github.com/easystats/insight/issues/232#issuecomment-699642516, what are your opinions about

"include sigma in get_parameters for Bayesian non-mixed models?"

**Comment by DominiqueMakowski** [comment]
I would say that get_parameters should return parameters estimated by the models as defined in the README (which usually correspond to some effects of some kind), and in that sense sigma isn't really similar to one. I feel like developers using get_parameters() would expect it to return only "regular" parameters, and if they want to retrieve aux parameters, they can always use get_sigma() to do so. TLDR; we shouldn't mix apples and pears and go with the most expected output for each function

**Comment by strengejacke** [comment]
Ok, I think, `get_sigma()` should be enough, and then in _report_, we could add information on sigma.

**Comment by strengejacke** [comment]
See also https://statmodeling.stat.columbia.edu/2020/09/26/does-this-fallacy-have-a-name/ and discussion.

**Comment by strengejacke** [comment]
Just saw a _very_ old comment in the _performance_ code, which was from ... ... ... @DominiqueMakowski !

> # TODO: What with sigma and deviance?

So, you already recognized the importance of sigma some time ago 😄

**Comment by DominiqueMakowski** [comment]
haha the past me keeps surprising current me
