### ISSUE TITLE
possible problem on linux

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/insight#239]
When `anovaBF` has random component (e.g., repeated measures ANOVA), the `linux`/`ubuntu` and `macOS` builds fail because of the following problem:

**Trace**:

```r
input string 11 is invalid in this locale
Backtrace:
 1. performance::r2_bayes(bf.object, average = TRUE, ci = conf.level)
 2. performance:::r2_posterior.BFBayesFactor(model, ...)
 3. performance:::.r2_posterior_model_average(model, prior_odds = prior_odds)
 4. performance:::r2_posterior.BFBayesFactor(1/model[1])
 5. insight:::get_parameters.BFBayesFactor(model, unreduce = FALSE)
 6. insight:::find_parameters.BFBayesFactor(...)
 7. base::lapply(...)
 8. insight:::FUN(X[[i]], ...)
 9. base::gsub("`", "", x, fixed = TRUE)
```

**Relevant code**:

https://github.com/easystats/insight/blob/5bce6619d0270d5bad89dff6ea919ffc235b94b3/R/find_parameters.R#L887-L895

**Possible solution**: https://stackoverflow.com/a/51724490/7973626

Note that this is separate from https://github.com/easystats/performance/issues/152 because that is also observed on `Windows`.

**Comment by strengejacke** [comment]
Not sure, looks like the `gsub()` is the source of this issue and is called from within an R core function.

**Comment by IndrajeetPatil** [comment]
I can confirm that this was `BayesFactor` issue and tests ran fine on `linux` once I relied on the devel version of `BayesFactor`.
