### ISSUE TITLE
`get_priors` fails only for `contingencyTableBF`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/insight#241]
``` r
library(insight)
library(BayesFactor)
#> Loading required package: coda
#> Loading required package: Matrix
#> ************
#> Welcome to BayesFactor 0.9.12-4.3. If you have questions, please contact Richard Morey (richarddmorey@gmail.com).
#> 
#> Type BFManual() to open the manual.
#> ************
data(raceDolls)

# t-test
mod <- ttestBF(x = sleep$extra[sleep$group==1], y = sleep$extra[sleep$group==2], paired=TRUE)

get_priors(mod)
#>    Parameter Distribution Location     Scale
#> 1 Difference       cauchy        0 0.7071068

# contingency tabs
bf <- contingencyTableBF(raceDolls, sampleType = "indepMulti", fixedMargin = "cols")

get_priors(bf)
#> Error in data.frame(Parameter = prior_names, Distribution = "cauchy", : arguments imply differing number of rows: 0, 1

bf@denominator@prior
#> $a
#> [1] 1
#> 
#> $fixedMargin
#> [1] "cols"
```

<sup>Created on 2020-10-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by IndrajeetPatil** [comment]
Since there is no parameter for this test, I this we could return something like, which is not much but at least the function consistently works across all tests from `BayesFactor`:

```r
get_priors(mod)
#>    Scale
#> 1  1
```

**Comment by strengejacke** [comment]
Can this be considered as "flat" prior? @mattansb ? Or should we return NULL / NA?

**Comment by mattansb** [comment]
It's not flat - but I'm not sure what exactly it _is_ - some beta / multinomial /  dirichlet or something like that... Also seems to change depending on `sampleType`, so...

I suggest returning just `a` (the name of the parameter):

```R
bf@numerator[[1]]@prior$a
```

**Comment by IndrajeetPatil** [comment]
Is the distribution here really Cauchy?

``` r
library(insight)
library(BayesFactor)
data(raceDolls)

# contingency tabs
bf <- contingencyTableBF(raceDolls, sampleType = "indepMulti", fixedMargin = "cols")

get_priors(bf)
#>   Parameter Distribution Location Scale
#> 1     Ratio       cauchy        0     1
```

If I am not mistaken, we should be providing this value, right?

```r
bf@denominator@type
```

**Comment by mattansb** [comment]
Not sure what it is... Would have to dig deep in the BayesFactor docs and references...... Let me know what you find ^_^

**Comment by IndrajeetPatil** [comment]
Let's just ask Richard!

Closing in favor of https://github.com/richarddmorey/BayesFactor/issues/150/

**Comment by IndrajeetPatil** [comment]
My hunch was correct. Indeed, we should be returning `bf@denominator@type` value here:

> No, it isn't Cauchy. Details are here: https://link.springer.com/article/10.3758/s13428-016-0739-8. Indeed, the necesary information for the prior is in `bf@denominator@type` and `bf@denominator@prior` (in particular, the fixed margin is also important).

**Comment by strengejacke** [comment]
Can someone open a PR? The necessary handling of this exception should be done somewhere here: https://github.com/easystats/insight/blob/fb51da019201edfa57fec1c651c70a440e752c10/R/get_priors.R#L284

**Comment by IndrajeetPatil** [comment]
I will take a stab at this tomorrow.

**Comment by IndrajeetPatil** [comment]
I will make a PR by the end of the day. Please don't submit to `CRAN`, in case you were planning. 

I would like to have a version of `insight` on `CRAN`, where the current issue is resolved. I can then use it in my own package.

**Comment by strengejacke** [comment]
Ok. It looks like the packages are in shape for the next update-round, so starting with insight by mid of this week, if you're done with this issue.
