### ISSUE TITLE
Installing "insight" package from CRAN

### ISSUE THREAD

**Issue by brownpw** [easystats/insight#253]
I get the following error.

```r
installing the source package ‘insight’

trying URL 'https://cran.rstudio.com/src/contrib/insight_0.11.0.tar.gz'
Content type 'application/x-gzip' length 722744 bytes (705 KB)
downloaded 705 KB

'"C:\PROGRA~1\R\R-4.0.3/bin/x64/Rterm.exe"' is not recognized as an internal or external command,
operable program or batch file.
Warning in install.packages :
  installation of package ‘insight’ had non-zero exit status

Package needed to install ggeffects.
```

**Comment by strengejacke** [comment]
This actually doesn't look like an insight issue. However, I've not read such an error message before, have you searched for this on the internet?

**Comment by brownpw** [comment]
I have but none of the suggestions seems to be working either. I was hoping this might be a bug in R version 4.0.3 Patched.

**Comment by brownpw** [comment]
I think I may have found something:

In the C:\Program Files\R\R-4.0.3\bin\x64 folder, the Rterm.exe program is named Rterm.exe.000. Is this as simple as renaming it or do I need to dlownload it?

**Comment by strengejacke** [comment]
I have no clear idea about the components from the R installation, maybe you should try to remove and re-install R?
