### ISSUE TITLE
Should we consider s(factor, bs="fs")  (i.e., factor smooths) as random factors?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#254]
Alright so here's some edgecase that I'm not sure what to do with. Basically, in `mgcv` one can add random factors either via using the `random` argument in the `gamm` function (in which case in relies on lme), or by modelling it as a particular smooth term, which is apparently (also based on my recall of an online training on mgcv), equivalent:

From `mgcv`'s docs on `smooth.terms`:

> **Factor smooth interactions**
> bs="fs" [...] The "fs" smoothers are set up to be efficient when used with gamm, and have penalties on each null sapce component (i.e. they are fully ‘random effects’).

The problem when specified as this, it is detected as a fixed effect, and just now led to some issues in modelbased (with my colleague @Tam-Pham).

``` r
insight::find_predictors(lme4::lmer(Sepal.Length ~ Petal.Length + (1|Species), data = iris))
#> $conditional
#> [1] "Petal.Length"
insight::find_predictors(gamm4::gamm4(Sepal.Length ~ Petal.Length + s(Sepal.Width), random=~(1|Species), data = iris))
#> $conditional
#> [1] "Petal.Length" "Sepal.Width"
insight::find_predictors(mgcv::gamm(Sepal.Length ~ Petal.Length + s(Sepal.Width), random=list(Species=~1), data = iris))
#> Warning in model.matrix.default(~b$groups[[n.levels - i + 1]] - 1, contrasts.arg
#> = c("contr.treatment", : non-list contrasts argument ignored
#> $conditional
#> [1] "Petal.Length" "Sepal.Width"

model <- mgcv::gam(Sepal.Length ~ Petal.Length + s(Sepal.Width) + s(Species, bs="fs"), data = iris)
insight::find_predictors(model)
#> $conditional
#> [1] "Petal.Length" "Sepal.Width"  "Species"
```

<sup>Created on 2020-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

While it could be argued that because these random effects are specified as smooth they should behave as regular smooths terms (i.e., be considered a fixed effect), but the problem is that sometimes it's easier to use this format instead of `gamm` which, as one can see in the example above, throws some errors... 

What do you think?

**Comment by strengejacke** [comment]
That probably makes sense. Do you have an example, where _modelbased_ fails?

**Comment by DominiqueMakowski** [comment]
Actually no, I thought about it, and in fact I think it's best to treat random factors entered as `s(factor, bs="fs")` as smooth terms rather as random. Because even though they are analog to random factors, they are entered as smooth terms so should be kept as is. So I think we can close this 😁
