### ISSUE TITLE
`R2_Nagelkerke` is `1.00`?

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#256]
@strengejacke Also, why is `R2_Nagelkerke` for the first 3 models `1.00`? Seems odd, no?

_Originally posted by @mattansb in https://github.com/easystats/performance/issues/164#issuecomment-731596481_

**Comment by strengejacke** [comment]
I think we need to adjust the `n_obs()` method to get the correct nobs, as described in https://github.com/easystats/performance/issues/165

**Comment by mattansb** [comment]
Nope, it's not that...

``` r
data(stroop, package = "afex")
stroop <- subset(stroop, pno %in% c("s1_1","s1_2","s1_3","s1_4","s1_5","s1_6","s1_7","s1_8","s1_9","s1_10"))
stroop <- subset(stroop, acc == 1)
stroop$trialnum <- stroop$trialnum/100
stroop$rt <- stroop$rt*1000

m1.1 <- glm(rt ~ condition + trialnum, 
            data = stroop,
            family = gaussian())

m2.1 <- glm(rt ~ condition + trialnum, 
            data = stroop,
            family = inverse.gaussian())
```

These are the same

``` r
insight::n_obs(m1.1)
#> [1] 3100
insight::n_obs(m2.1)
#> [1] 3100
```

But here….

``` r
m1.1$null.deviance
#> [1] 130006303
m2.1$null.deviance
#> [1] 0.3754939
```

<sup>Created on 2020-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Ok, so we have two issues here...

**Comment by mattansb** [comment]
Alternatively, maybe we can detect add a "dumb" method that - when the response is quantitative - R2 is just:

```R
R2_manual <- function(pred, obs) {
  1 - sum((obs - pred)^2) / sum((obs - mean(obs))^2)
}

pred <- predict(m1.1, type = "response")
obs <- insight::get_response(m1.1)

R2_manual(pred, obs)
#> [1] 0.002925233
 
pred <- predict(m2.1, type = "response")
obs <- insight::get_response(m2.1)

R2_manual(pred, obs)
#> [1] 0.003044578
```

(Using the R2 formula [based on RMSE](https://mattansb.github.io/MSBMisc/reference/R2.html))

**Comment by DominiqueMakowski** [comment]
any update here?

**Comment by strengejacke** [comment]
No, not yet. But the method [suggested by @mattansb](https://github.com/easystats/insight/issues/256#issuecomment-737035284) is the same as for [mhurdle-models](https://github.com/easystats/performance/blob/7265fa4ee78208b6ec7b388ad9d5a50e79635d57/R/r2.R#L115), so should be ready to implement.

**Comment by mattansb** [comment]
(Just to note that [this method](https://github.com/easystats/insight/issues/256#issuecomment-737035284) is also applicable to any  quantitive outcome (i.e., non-classification [binomial, multinomial, ordianl] model) - so also for Poisson, NB, ZI, etc...)
