### ISSUE TITLE
Use standard R `error` instead of `print_color`

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#257]
I'm planning to add support for `model_parameters` and `model_performance` to my [modelsummary package](https://vincentarelbundock.github.io/modelsummary/). One thing I'd like to do is try to extract the info I need using `easystats`, and then move to `broom` or `broom.mixed` if that fails.

Unfortunately, it looks like `insight` uses a non-idiomatic function to print error messages, instead of the standard `error`. I understand why some people might like red text, but it prevents standard silencing strategies such as:

``` r
library(parameters)

mod <- "junk"
try(model_parameters(mod), silent=TRUE)
#> Parameters can't be retrieved for objects of class 'simpleError'.
```

I wonder if you would be open to using a more standard error reporting strategy. Alternatively, do you recommend a better way to check if a function will produce a valid output for a given model type without printing an error message in case of failure?

Thanks for your work on this very cool package!

**Comment by strengejacke** [comment]
Yes, I think, currently you can just use `capture.output()` to prevent the printing. However, we usually try to add a `verbose`-argument, that - if `FALSE` - should prevent any printing. Maybe this is not yet consistently implemented across functions, I'll take a look at it. Maybe we can indeed switch to `warning()` in some more cases and not rely on `print_color()`.

**Comment by strengejacke** [comment]
> and then move to broom or broom.mixed if that fails.

There is of course no such case where the easystats packages will fail ;-)

**Comment by IndrajeetPatil** [comment]
> and then move to broom or broom.mixed if that fails. 

You might also want to keep an eye on this issue: https://github.com/easystats/parameters/issues/336

**Comment by strengejacke** [comment]
I _think_ this is now done. Mostly, `print_color()` was replaced by `warning()` or `message()`, and where appropriate, I added a `verbose` argument. Please re-open / open a new issue if I missed something. Update just submitted to CRAN.

**Comment by vincentarelbundock** [comment]
fantastic! Thanks so much!
