### ISSUE TITLE
return constants in terms?

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#26]
``` r
library(insight)
library(nlme)

data(Ovary)
m1 <- gls(follicles ~ sin(2*pi*Time) + cos(2*pi*Time), Ovary,
          correlation = corAR1(form = ~ 1 | Mare))

find_terms(m1)
#> $response
#> [1] "follicles"
#> 
#> $conditional
#> [1] "pi"   "Time"
```

Should `pi` be returned or not?

**Comment by DominiqueMakowski** [comment]
Hum, intuitively I would say no, since it's a constant (such as `2`)?

**Comment by strengejacke** [comment]
How many of such constants do we have? Just pi?

**Comment by DominiqueMakowski** [comment]
My guess would be technically one constant, which is `2*pi`?

**Comment by strengejacke** [comment]
No, I mean in general. :-)
How many of such constants does R have?

**Comment by DominiqueMakowski** [comment]
https://stat.ethz.ch/R-manual/R-devel/library/base/html/Constants.html

A small number apparently

**Comment by strengejacke** [comment]
ok, and `pi` is the only relevant one for formulas.
