### ISSUE TITLE
Issue with export_table(format = "markdown") w/ many footers

### ISSUE THREAD

**Issue by mattansb** [easystats/insight#262]
Following https://github.com/easystats/report/issues/91 (@strengejacke I am in LOVE with this function!)

Seems like the markdown option only allows one row of "footer" (here, a list)?

``` r
library(bayestestR)
#> Note: The default CI width (currently `ci=0.89`) might change in future versions (see https://github.com/easystats/bayestestR/issues/250). To prevent any issues, please set it explicitly when using bayestestR functions, via the 'ci' argument.
library(magrittr)
library(report)
#> report is in alpha - help us improve by reporting bugs on github.com/easystats/report/issues
library(insight)

lm1 <- lm(Sepal.Length ~ 1, data = iris)
lm2 <- lm(Sepal.Length ~ Species, data = iris)
lm3 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
lm4 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)


bayesfactor_models(lm1, lm2, lm3, lm4, denominator = 1) %>% 
  report_table()
#> Model                      | BF against model 1 | BF against model 3 (best model)
#> ---------------------------------------------------------------------------------
#> [1] (Intercept only)       |               1.00 |                      1/5.84e+55
#> [2] Species                |           1.70e+29 |                      1/3.45e+26
#> [3] Species + Petal.Length |           5.84e+55 |                            1.00
#> [4] Species * Petal.Length |           2.20e+54 |                         1/26.52
#> 
#> Bayes Factor Type: BIC approximation
#> Against denominator: Model 1

bayesfactor_models(lm1, lm2, lm3, lm4, denominator = 1) %>% 
  report_table() %>% 
  format() %>% 
  export_table(format = "markdown")
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">BF against model 1</th>
<th style="text-align: right;">BF against model 3 (best model)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">[1] (Intercept only)</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1/5.84e+55</td>
</tr>
<tr class="even">
<td style="text-align: left;">[2] Species</td>
<td style="text-align: right;">1.70e+29</td>
<td style="text-align: right;">1/3.45e+26</td>
</tr>
<tr class="odd">
<td style="text-align: left;">[3] Species + Petal.Length</td>
<td style="text-align: right;">5.84e+55</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">[4] Species * Petal.Length</td>
<td style="text-align: right;">2.20e+54</td>
<td style="text-align: right;">1/26.52</td>
</tr>
</tbody>
</table>

Bayes Factor Type: BIC approximation

<sup>Created on 2020-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Yes, see `?export_table`, the `footer` argument:

> Table footer, as string. For markdown-formatted tables, table footers, due to the limitation in markdown rendering, are actually just a new text line under the table.

**Comment by strengejacke** [comment]
Currently, it's limited to one line. Maybe we can think about allowing multiple lines?

**Comment by strengejacke** [comment]
``` r
library(bayestestR)
#> Note: The default CI width (currently `ci=0.89`) might change in future versions (see https://github.com/easystats/bayestestR/issues/250). To prevent any issues, please set it explicitly when using bayestestR functions, via the 'ci' argument.
library(magrittr)
library(report)
#> report is in alpha - help us improve by reporting bugs on github.com/easystats/report/issues
library(insight)

lm1 <- lm(Sepal.Length ~ 1, data = iris)
lm2 <- lm(Sepal.Length ~ Species, data = iris)
lm3 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
lm4 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)


bayesfactor_models(lm1, lm2, lm3, lm4, denominator = 1) %>% 
  report_table() %>% 
  format() %>% 
  export_table(format = "markdown")
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">BF against model 1</th>
<th style="text-align: right;">BF against model 3 (best model)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">[1] (Intercept only)</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1/5.84e+55</td>
</tr>
<tr class="even">
<td style="text-align: left;">[2] Species</td>
<td style="text-align: right;">1.70e+29</td>
<td style="text-align: right;">1/3.45e+26</td>
</tr>
<tr class="odd">
<td style="text-align: left;">[3] Species + Petal.Length</td>
<td style="text-align: right;">5.84e+55</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">[4] Species * Petal.Length</td>
<td style="text-align: right;">2.20e+54</td>
<td style="text-align: right;">1/26.52</td>
</tr>
</tbody>
</table>

Bayes Factor Type: BIC approximation

Against denominator: Model 1

<sup>Created on 2020-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattansb** [comment]
Thanks!

Also, the cpation/subtitle are copied to the footer?

``` r
library(bayestestR)
#> Note: The default CI width (currently `ci=0.89`) might change in future versions (see https://github.com/easystats/bayestestR/issues/250). To prevent any issues, please set it explicitly when using bayestestR functions, via the 'ci' argument.
library(magrittr)
library(report)
#> report is in alpha - help us improve by reporting bugs on github.com/easystats/report/issues
library(insight)

lm1 <- lm(Sepal.Length ~ 1, data = iris)
lm2 <- lm(Sepal.Length ~ Species, data = iris)
lm3 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
lm4 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)


t <- bayesfactor_models(lm1, lm2, lm3, lm4, denominator = 1) %>% 
  report_table() %>% 
  format()

attr(t, "table_caption") <- "Bayesian Model Comparison"
attr(t, "table_subtitle") <- "\nSome more words..."

export_table(t, format = "markdown")
```

<table>
<caption>Bayesian Model Comparison
Some more words…</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">BF against model 1</th>
<th style="text-align: right;">BF against model 3 (best model)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">[1] (Intercept only)</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1/5.84e+55</td>
</tr>
<tr class="even">
<td style="text-align: left;">[2] Species</td>
<td style="text-align: right;">1.70e+29</td>
<td style="text-align: right;">1/3.45e+26</td>
</tr>
<tr class="odd">
<td style="text-align: left;">[3] Species + Petal.Length</td>
<td style="text-align: right;">5.84e+55</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">[4] Species * Petal.Length</td>
<td style="text-align: right;">2.20e+54</td>
<td style="text-align: right;">1/26.52</td>
</tr>
</tbody>
</table>

Bayesian Model Comparison
Some more words…

Bayes Factor Type: BIC approximation

<sup>Created on 2020-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Apparently only in the reprex rendering?

![image](https://user-images.githubusercontent.com/26301769/101904210-caa71900-3bb5-11eb-8963-9ae8f1ff39ed.png)

**Comment by mattansb** [comment]
Huh... weird 🤷‍♂️

**Comment by strengejacke** [comment]
so actually, this issue is resolved, right?

**Comment by mattansb** [comment]
Yup
