### ISSUE TITLE
Adding `standardize_names` method for "parameters_distribution"

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/insight#270]
This somehow always bites me. To be consistent, it will be nice to have a separate method to handle objects of this class:

```r
library(parameters)

# doesn't work
standardize_names(describe_distribution(iris$Sepal.Length, "mean"), "broom")
#>       mean   std.dev iqr min max skewness  kurtosis   n n.missing
#> 1 5.843333 0.8280661 1.3 4.3 7.9 0.314911 -0.552064 150         0

# current workaround
standardize_names(as.data.frame(describe_distribution(iris$Sepal.Length, "mean")), "broom")
#>   estimate   std.dev iqr min max skewness  kurtosis   n n.missing
#> 1 5.843333 0.8280661 1.3 4.3 7.9 0.314911 -0.552064 150         0
```

**Comment by IndrajeetPatil** [comment]
Also, `trimmed.mean` here should be renamed to `estimate` in `broom` convention:

```r
standardize_names(as.data.frame(describe_distribution(iris$Sepal.Length, "trimmed", threshold = 0.1)), "broom")
#>   trimmed.mean   std.dev iqr min max skewness  kurtosis   n n.missing
#> 1     5.808333 0.8280661 1.3 4.3 7.9 0.314911 -0.552064 150         0
```

**Comment by strengejacke** [comment]
There is actually a specific method for this class, which however, intentionally skips this code-line (i.e. `ignore_estimate = TRUE`):

```r
  if (!isTRUE(ignore_estimate)) {
    cn[cn %in% c("Coefficient", "Std_Coefficient", "Median", "Mean", "MAP", "Trimmed_Mean")] <- "estimate"
  }
```

I'm not sure why, maybe exactly for this case that we don't want a column "estimate"?

**Comment by IndrajeetPatil** [comment]
Oh, right! When `centrality = "all"` in `describe_distribution`, this will basically rename a number of columns to `estimate` and that's what we were trying to avoid. 

That said, I think we can remove this condition and rename these columns because it is highly unlikely that someone in the wild is going to use `broom`-convention in this context (i.e., with `centrality = "all"`).
