### ISSUE TITLE
display() changes square brackets to round brackets

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#271]
``` r
m <- lm(Sepal.Length ~ Species * Sepal.Width, data=iris)
parameters::parameters(m)
#> Parameter                          | Coefficient |   SE |        95% CI | t(144) |      p
#> -----------------------------------------------------------------------------------------
#> (Intercept)                        |        2.64 | 0.57 | [ 1.51, 3.77] |   4.62 | < .001
#> Species [versicolor]               |        0.90 | 0.80 | [-0.68, 2.48] |   1.13 | 0.261 
#> Species [virginica]                |        1.27 | 0.82 | [-0.35, 2.88] |   1.55 | 0.123 
#> Sepal.Width                        |        0.69 | 0.17 | [ 0.36, 1.02] |   4.17 | < .001
#> Species [versicolor] * Sepal.Width |        0.17 | 0.26 | [-0.34, 0.69] |   0.67 | 0.503 
#> Species [virginica] * Sepal.Width  |        0.21 | 0.26 | [-0.29, 0.72] |   0.83 | 0.411
insight::display(parameters::parameters(m))
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Coefficient</th>
<th style="text-align: center;">SE</th>
<th style="text-align: center;">95% CI</th>
<th style="text-align: center;">t(144)</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">2.64</td>
<td style="text-align: center;">0.57</td>
<td style="text-align: center;">(1.51, 3.77)</td>
<td style="text-align: center;">4.62</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Species (versicolor)</td>
<td style="text-align: center;">0.90</td>
<td style="text-align: center;">0.80</td>
<td style="text-align: center;">(-0.68, 2.48)</td>
<td style="text-align: center;">1.13</td>
<td style="text-align: center;">0.261</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Species (virginica)</td>
<td style="text-align: center;">1.27</td>
<td style="text-align: center;">0.82</td>
<td style="text-align: center;">(-0.35, 2.88)</td>
<td style="text-align: center;">1.55</td>
<td style="text-align: center;">0.123</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sepal.Width</td>
<td style="text-align: center;">0.69</td>
<td style="text-align: center;">0.17</td>
<td style="text-align: center;">(0.36, 1.02)</td>
<td style="text-align: center;">4.17</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Species (versicolor) * Sepal.Width</td>
<td style="text-align: center;">0.17</td>
<td style="text-align: center;">0.26</td>
<td style="text-align: center;">(-0.34, 0.69)</td>
<td style="text-align: center;">0.67</td>
<td style="text-align: center;">0.503</td>
</tr>
<tr class="even">
<td style="text-align: left;">Species (virginica) * Sepal.Width</td>
<td style="text-align: center;">0.21</td>
<td style="text-align: center;">0.26</td>
<td style="text-align: center;">(-0.29, 0.72)</td>
<td style="text-align: center;">0.83</td>
<td style="text-align: center;">0.411</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-12-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

In the CI column, brackets are changed. Wondering if this is expected behaviour related to markdown printing?

**Comment by strengejacke** [comment]
Yes, this is intentional, as parentheses imho look better in html/pdf/word than brackets.

**Comment by DominiqueMakowski** [comment]
I see, should we add an argument to change this behaviour? Like `display(x, brackets_as_parenthesis=TRUE)` or `display(x, ci_brackets=c("[]", "()"))`?

**Comment by strengejacke** [comment]
It's actually part of the specific packages, not _insight_, as we here just have the definition of the generic. While the argument `ci_brackets` is already available in [`parameters::format()`](https://easystats.github.io/parameters/reference/display.parameters_model.html), I now added it to `display()` etc. as well.
