### ISSUE TITLE
get_df(): move implemention from parameters::dof() here 

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#273]
but we could still keep `parameters::dof` as an alias there so nothing's broken. But dfs are sometimes model-related properties (not only parameters), and it would be very useful to be able to query them consistently (especially for instance in performance when I'm trying to reimplement the LRT)

**Comment by strengejacke** [comment]
So we should close https://github.com/easystats/performance/issues/173?
And I think that df for parameters is something different than df for the model (as discussed in the 173-issue at performance), so I would not move the implementation, but rather keep both?

**Comment by DominiqueMakowski** [comment]
Ah right I forgot we already  discussed that... `model_df` indeed makes a lot of sense, and get_df would be more akin do dof() (unless we want something like `get_df(what=c("model", "parameters")`). In any case, it's by any means a priority as having a function to get model's df in performance would be perfect for the usecase I have in mind

**Comment by strengejacke** [comment]
But first let me know in which df exactly you're interested in? (https://github.com/easystats/performance/issues/173#issuecomment-750459895)

**Comment by strengejacke** [comment]
I implemented a `get_df()`, which basically does what `df.residuals()` does, or `n - k`. So this is slightly different to what `parameters::degrees_of_freedom()` does, which returns the df for the parameters to do tests:

``` r
library(insight)
library(parameters)

model <- lm(Sepal.Length ~ Petal.Length * Species, data = iris)
get_df(model)
#> [1] 144
degrees_of_freedom(model)
#> [1] 144

model <- glm(vs ~ mpg * cyl, data = mtcars, family = "binomial")
get_df(model)
#> [1] 28
degrees_of_freedom(model)
#> [1] Inf
```

<sup>Created on 2021-01-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
We may think of just having the methods `"residual"` (which is equal to `method = "any"`) or `"model"`, which would return https://github.com/easystats/performance/issues/173.
