### ISSUE TITLE
get_residuals()

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#275]
Maybe we could have a `get_residuals()` method that, by default, runs `stats::residuals()` and progressively support non-supported models.

```r 
m <- lm(Sepal.Length ~ Species, data=iris)
stats::residuals(m)
```

**Comment by strengejacke** [comment]
We could simply move this code here (https://github.com/easystats/performance/blob/aa9c03d5841d492cb7a4966fa1e84ce8c2905cc8/R/performance_mse.R#L35) to insight and use it as a base.
