### ISSUE TITLE
Issue with scoping in get_data.htest()

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/insight#276]
``` r
# data
Performance <-
  matrix(c(794, 86, 150, 570),
    nrow = 2,
    dimnames = list(
      "1st Survey" = c("Approve", "Disapprove"),
      "2nd Survey" = c("Approve", "Disapprove")
    )
  )

# function body
foo <- function(data) {
  mod <- stats::mcnemar.test(data, correct = FALSE)
  print(mod)

  insight::get_data(foo)
}

foo(Performance)
#> 
#>  McNemar's Chi-squared test
#> 
#> data:  data
#> McNemar's chi-squared = 17.356, df = 1, p-value = 3.099e-05
#> Warning: Could not get model data.
#> NULL
```

**Comment by mattansb** [comment]
I've moved this here, as I believe this stems from where `get_data.htest()` looks for the data.

**Comment by IndrajeetPatil** [comment]
@strengejacke Can we please resolve this soon-ish? I am kind of stuck somewhere on account of this 🛑

**Comment by strengejacke** [comment]
You must use `<<--`.

**Comment by IndrajeetPatil** [comment]
You mean like this?

```r
# function body
foo <- function(data, x, y) {
  data <<- data
  x_arg <- table(data %>% dplyr::pull({{ x }}), data %>% dplyr::pull({{ y }}))
  mod <- stats::mcnemar.test(x = x_arg, correct = FALSE)

  # extracting parameters
  as.data.frame(parameters::model_parameters(mod, cohens_g = TRUE))
}
```

Sigh, I was afraid of this. Unfortunately, this is the problem as here:
https://github.com/easystats/parameters/issues/176#issuecomment-725666538

I will see what I can do.

**Comment by strengejacke** [comment]
The problem is that - to access the data - we evaluate the function call:

```r
data_name <- unlist(strsplit(x$data.name, " (and|by) "))
data_call <- lapply(data_name, str2lang)
columns <- lapply(data_call, eval)
```

I don't know how to evaluate the expression if it's not in the parent frame or global environment. `eval()` has an `envir`-argument, but it seems like there is no option that will find your `x_arg` variable from your example.

**Comment by strengejacke** [comment]
Maybe you can indeed find a way using some/one of `?bindenv`.

**Comment by mattansb** [comment]
Maybe you can dig in the `emmeans` code - I know there were scoping problems resolved there.

**Comment by mattansb** [comment]
@IndrajeetPatil you can locally solve this by not getting the effect size from `parameters` and passing x,y to `cohens_g` directly (and then chind the results).

**Comment by IndrajeetPatil** [comment]
Thanks!

> @IndrajeetPatil you can locally solve this by not getting the effect size from parameters and passing x,y to cohens_g directly (and then chind the results).

Yeah, this is what I am currently doing. My workflow right now is:
- for Pearson's chi-squared: use `model_parameters` for both effect size and stats
- for one-sample chi-squared:  use `model_parameters` for both effect size and stats

But

- for McNemar's chi-squared: : `model_parameters` gives stats and `effectsize` gives effect sizes

And that inconsistency is what bothers me 😅 

> Maybe you can dig in the emmeans code - I know there were scoping problems resolved there.

I see. Cool, I will check it out.

**Comment by IndrajeetPatil** [comment]
@strengejacke Do you think the second solution here is appropriate for `insight`?

https://stackoverflow.com/questions/65533301/solving-scoping-issure-in-a-custom-function-to-extract-data-from-htest-object/65533557#65533557

**Comment by strengejacke** [comment]
That would not work for:

```r
x <- t.test(1:3, c(1,1:3))
get_data(x)
```

So there's no one-size-fits-all solution to this problem, I'm afraid...

**Comment by mattansb** [comment]
Can a trycatch be used here?

**Comment by strengejacke** [comment]
That might work. @IndrajeetPatil I updated `get_data()`, can you try it out?

**Comment by IndrajeetPatil** [comment]
Surprisingly, still doesn't work. I am confused now why it works in the `StackOverflow` solution, but not in the package context. I guess this is `env` related issue?

``` r
# data
Performance <-
  matrix(c(794, 86, 150, 570),
    nrow = 2,
    dimnames = list(
      "1st Survey" = c("Approve", "Disapprove"),
      "2nd Survey" = c("Approve", "Disapprove")
    )
  )

# function body
foo <- function(data) {
  mod <- stats::mcnemar.test(data, correct = FALSE)
  print(mod)

  insight::get_data(foo)
}

foo(Performance)
#> 
#>  McNemar's Chi-squared test
#> 
#> data:  data
#> McNemar's chi-squared = 17.356, df = 1, p-value = 3.099e-05
#> Warning: Could not get model data.
#> NULL
```

<sup>Created on 2021-01-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
Keeping it open for now, before we completely give up on it.

**Comment by IndrajeetPatil** [comment]
@mattansb Turns out, this doesn't just affect McNemar's test, but also _t_-test (and I am guessing a number of other `htest` objects):

``` r
df <- data.frame(x = rnorm(10), y = rnorm(10))

# function body
foo <- function(data) {
  mod <- stats::t.test(rnorm(10), y = rnorm(10), paired = FALSE)
  print(mod)
  
  insight::get_data(foo)
}

foo(df)
#> 
#>  Welch Two Sample t-test
#> 
#> data:  rnorm(10) and rnorm(10)
#> t = 0.43819, df = 16.105, p-value = 0.6671
#> alternative hypothesis: true difference in means is not equal to 0
#> 95 percent confidence interval:
#>  -0.801300  1.219157
#> sample estimates:
#>   mean of x   mean of y 
#>  0.11516322 -0.09376509
#> Warning: Could not get model data.
#> NULL
```

<sup>Created on 2021-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

We really need to figure out a way around this, otherwise the whole `effectsize` functionality implemented in `model_parameters` is unusable for package developers.

**Comment by mattansb** [comment]
> @mattansb Turns out, this doesn't just affect McNemar's test... We really need to figure out a way around this

Yeah, I know :/ Need some expeRts...

**Comment by IndrajeetPatil** [comment]
But wait a minute, how it is that this works even if `get_data` fails?

```r
# function body
foo <- function(data, type) {
  mod <- stats::oneway.test(extra ~ group, data = data)

  rlang::inform("data entered is")
  print(insight::get_data(mod))
  
  as.data.frame(effectsize::effectsize(mod, type = type))
}

foo(sleep, type = "eta")
#> data entered is
#> NULL
#> Warning: `var.equal = FALSE` - effect size is an approximation.
#>        Eta2  CI CI_low   CI_high
#> F 0.1630308 0.9      0 0.4159588
foo(sleep, type = "omega")
#> data entered is
#> NULL
#> Warning: `var.equal = FALSE` - effect size is an approximation.
#>      Omega2  CI CI_low   CI_high
#> F 0.1107341 0.9      0 0.3600181
```

**Comment by mattansb** [comment]
Because not all `effectsize.htest()` rely on `get_data.htest()`. If I can, I use other methods.
- For one way anova I just you `F_to_*` because it is close within like 2 decimal points (:
- For chisq is use `model$observed`.
- For `fisher.test()` / `cor.test()` I just pull the values directly from the object (OR / correlation).

**Comment by IndrajeetPatil** [comment]
Ah, I see!

What happens for a *t*-test? Why does _d_ work here, but not _g_?
(Note that I am **not** using the formula interface.)

``` r
# function body
foo <- function(x = 1:10, y = c(7:20), type) {
  mod <- t.test(x = x, y = y)  

  rlang::inform("data entered is")
  print(insight::get_data(mod))
  
  as.data.frame(effectsize::effectsize(mod, type = type))
}

foo(type = "d")
#> data entered is
#> NULL
#> Warning in effectsize.htest(mod, type = type): Unable to retrieve data from
#> htest object. Using t_to_d() approximation.
#>           d   CI    CI_low   CI_high
#> 1 -2.318399 0.95 -3.380808 -1.224004
foo(type = "g")
#> data entered is
#> NULL
#> Warning in effectsize.htest(mod, type = type): Unable to retrieve data from
#> htest object. Using t_to_d() approximation.
#>           d   CI    CI_low   CI_high
#> 1 -2.318399 0.95 -3.380808 -1.224004
```

<sup>Created on 2021-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by mattansb** [comment]
As the warning says 🤪

``` R
#> Warning in effectsize.htest(mod, type = type): Unable to retrieve data from
#> htest object. Using t_to_d() approximation.
```

This `d` isn't `Cohen's d`, but it is a close approximation (no equivalent for `Hedges' g`).

**Comment by IndrajeetPatil** [comment]
No, I understand that, but what I am wondering is if we can implement a similar approximation for `g` in `t_to_g()` function.

I found one such approach here: https://bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R/g.html

But it needs the sample sizes, which I guess means that we are back to square one since that will need data extraction.

**Comment by mattansb** [comment]
Thought of that, but we can't pull the group sizes from the `htest` :(

**Comment by IndrajeetPatil** [comment]
![tenor](https://user-images.githubusercontent.com/11330453/103549482-bea63280-4ea7-11eb-9311-1d93a33f9e0c.gif)

**Comment by IndrajeetPatil** [comment]
Tagging @vincentarelbundock here to see if he has any tricks up his sleeve! :)

**Comment by vincentarelbundock** [comment]
TBH, I haven't followed the whole conversation, but the problem seems to be that `get_data` retrieves columns by trying to evaluate `x$data.name`:

https://github.com/easystats/insight/blob/master/R/get_data.R#L1336

When you estimate your model interactively, `x$data.name` is the name of your data frame in the global environment. When you estimate your model inside a function, `x$data.name` is the name of the *argument*.

``` r
Performance <-
  matrix(c(794, 86, 150, 570),
    nrow = 2,
    dimnames = list(
      "1st Survey" = c("Approve", "Disapprove"),
      "2nd Survey" = c("Approve", "Disapprove")
    )
  )

mod <- stats::mcnemar.test(Performance, correct = FALSE)

foo1 <- function(data) {
  mod <- stats::mcnemar.test(data, correct = FALSE)
  print(mod$data.name)
}
foo2 <- function(Performance) {
  mod <- stats::mcnemar.test(Performance, correct = FALSE)
  print(mod$data.name)
}

print(mod$data.name)
#> [1] "Performance"

foo1(Performance)
#> [1] "data"

foo2(Performance)
#> [1] "Performance"
```

**Comment by mattansb** [comment]
@IndrajeetPatil closing because you're giving up? Or resolved??

**Comment by IndrajeetPatil** [comment]
Giving up. 

I feel like any solution we find is going to involve messing around with environments from which data is to be taken and that is 
(from what I understand) rarely a good practice for package functions.

**Comment by strengejacke** [comment]
Can you update insight and retry?

**Comment by IndrajeetPatil** [comment]
Nope, still doesn't work 😿
