### ISSUE TITLE
loglikelihood under OLS, ML and REML (for lm)

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#277]
The goal is to implement a loglikelihood function that also returns individual loglikelihoods (useful for some performance tests), alongside the one of the model (which usually corresponds to the sum of individual LLs).

Such functions are for instance implemented [here](https://github.com/SurajGupta/r-source/blob/a28e609e72ed7c47f6ddfbb86c85279a0750f0b7/src/library/stats/R/logLik.R#L69) in the nonnest2 package, and essentially copy the [base R](https://github.com/SurajGupta/r-source/blob/a28e609e72ed7c47f6ddfbb86c85279a0750f0b7/src/library/stats/R/logLik.R#L70) function but cut it before it sums all the individual LLs to get the model's loglik.

The problem is that I have two formulas that give the same results, that I'm trying to reconcile, but I don't know how.

## Basic one (ML - no weights)

``` r
x <- lm(Sepal.Length ~ Petal.Width + Species, data = iris)
stats::logLik(x)
#> 'log Lik.' -101.0339 (df=5)
```

The model's LL is **-101.0339**.

Here's the "**long**" method implemented in base R / nonnest2:

``` r
.lls_method1 <- function(x) {
  res <- insight::get_residuals(x)
  p <- x$rank
  n_obs <- length(res)
  s <- summary(x)$sigma
  # calculate s2 for ML method
  sml2 <- (s * sqrt((n_obs - p) / n_obs))^2
  
  # Get weights
  if (is.null(w <- x$weights)) {
    w <- rep.int(1, n_obs)
  } else {
    excl <- w == 0
    if (any(excl)) {
      res <- res[!excl]
      n_obs <- length(res)
      w <- w[!excl]
    }
  }
  
  # Get lls
  0.5 * (log(w) - (log(2 * pi) + log(sml2) + (w * res^2)/sml2))
}

sum(.lls_method1(x))
#> [1] -101.0339
```

As you can see it gives the same result (expected, it's pretty much the same function).

Now the problem is that **there is a second formula** that arrives to the same result:

``` r
.lls_method2 <- function(x) {
  estim <- function(x) sqrt(mean(insight::get_residuals(x)^2))
  stats::dnorm(insight::get_response(x), mean = insight::get_predicted(x), sd = estim(x), log = TRUE) 
}

sum(.lls_method2(x))
#> [1] -101.0339
```

**Why would I want to use this second *short* formula?** Because it's more concise, and most importantly because there is variant for it **to get the LLs under OLS**, instead of ML:

## OLS 

``` r
.lls_ols <- function(x) {
  estim <- function(x) sqrt(sum(insight::get_residuals(x)^2) / stats::df.residual(x))
  stats::dnorm(insight::get_response(x), mean = insight::get_predicted(x), sd = estim(x), log = TRUE) 
}

sum(.lls_ols(x))
#> [1] -101.0611
```

<sup>Created on 2021-01-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The difference is tiny, but [some argue](https://stats.stackexchange.com/questions/155474/why-does-lrtest-not-match-anovatest-lrt) that it gives better results, so it might be an interesting feature that we offer.

Based on that, you could think: **well let's use this short formula then**, as it is able to gives results for both ML and OLS.

And here's the problem. In the long formula, it also deals with **weights**. Somehow it adjust the LLs based on the weights in the model, which the "short" version doesn't do. That means that for a model with weights, the current short formula won't work.

My first question is: **how to adjust either the short formula by weights, OR to mimic the OLS variant in the long formula**? So that we have a function that works in all cases, and is able to do ML and OLS.

## Second problem: REML

Additionally to that first issue, there is another one. The base R function, for linear models, is also able to get [restricted ML - REML](https://github.com/SurajGupta/r-source/blob/a28e609e72ed7c47f6ddfbb86c85279a0750f0b7/src/library/stats/R/logLik.R#L89-L92) LL:

``` r
x <- lm(Sepal.Length ~ Petal.Width + Species, data = iris)
stats::logLik(x, REML=TRUE)
#> 'log Lik.' -107.0896 (df=5)
```

<sup>Created on 2021-01-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The adjustment seems pretty straightforward, but I don't know how to adapt it to make it return individual LLs, as the adjustment seems to be done after the LLs are summed together.

```r
  if(REML) N <- N - p
  val <- .5* (sum(log(w)) - N * (log(2 * pi) + 1 - log(N) + log(sum(w*res^2))))
  if(REML) val <- val - sum(log(abs(diag(object$qr$qr)[1L:p])))
```

The second question is: **how to make the REML adjustment to the short formula OR adapt the long formula to make also REML adjustment but still return the individual LLS**.

So that in the end, we have a robust function `get_loglikelihood(x, estimator=c("OLS", "ML", "REML")` that can fully reproduce base R's results + does more (i.e., returns the individual lls).

**Comment by DominiqueMakowski** [comment]
@mattansb I'm sure you can help make some sense out of this and detect the commonalities in the formulas 😬

**Comment by mattansb** [comment]
Oh man... this is quite an endeavor!

I don't know much, but the short form makes the most sense to me....

## Weights:

No idea... I suspect you'd need to multiply by `log(w)` somewhere?

## REML

No clue....

---

Note that for non-gaussian models you'd need a different method:

``` r
m <- glm(am ~ mpg, data = mtcars, family = binomial())

.lls_method3 <- function(x) {
  stats::dbinom(insight::get_response(x), 
                size = 1, # this will be different if model notation is cbind(k, n-k) ~ ...
                prob = insight::get_predicted(x),
                log = TRUE)
}

logLik(m)
#> 'log Lik.' -14.83758 (df=2)
sum(.lls_method3(m))
#> [1] -14.83758
```

<sup>Created on 2021-01-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

And for mixed models... and for mixture models... There's a lot to unpack (:

**Comment by DominiqueMakowski** [comment]
That's why for now we fall back on the default logLik method when we have nothing to add. But at least for `lm()` it would have been nice to have a more powerful implementation 😕

**Comment by mattansb** [comment]
We really should get an actual statistician on the team, hu? 😅

**Comment by strengejacke** [comment]
Just curious, @DominiqueMakowski, why are you so keen on logLik?

**Comment by strengejacke** [comment]
``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tidyr)

dat_ind <- lme4::cbpp %>%
  rowwise() %>%
  mutate(sick = list(c(rep(0, size - incidence), rep(1, incidence)))) %>%
  ungroup() %>%
  select(-size, -incidence) %>% 
  unnest(sick)

dat_agg <- lme4::cbpp %>% 
  mutate(no_incidence = size - incidence)

m_agg1 <- glm(cbind(incidence, size - incidence) ~ period,
              family = binomial,
              data = dat_agg)

m_agg2 <- glm(cbind(incidence, no_incidence) ~ period,
              family = binomial,
              data = dat_agg)

m_ind <- glm(sick ~ period, family = binomial, data = dat_ind)


.lls_method_m_ind <- function(x) {
  stats::dbinom(insight::get_response(x), 
                size = 1,
                prob = insight::get_predicted(x),
                log = TRUE)
}

.lls_method_m_agg1 <- function(x) {
  stats::dbinom(insight::get_response(x)[[1]], 
                size = insight::get_response(x)[[2]],
                prob = insight::get_predicted(x),
                log = TRUE)
}

.lls_method_m_agg2 <- function(x) {
  stats::dbinom(insight::get_response(x)[[1]], 
                size = insight::get_response(x)[[1]] + insight::get_response(x)[[2]],
                prob = insight::get_predicted(x),
                log = TRUE)
}

logLik(m_ind)
#> 'log Lik.' -284.5049 (df=4)
sum(.lls_method_m_ind(m_ind))
#> [1] -284.5049

logLik(m_agg1)
#> 'log Lik.' -99.0292 (df=4)
sum(.lls_method_m_agg1(m_agg1))
#> [1] -99.0292

logLik(m_agg2)
#> 'log Lik.' -99.0292 (df=4)
sum(.lls_method_m_agg2(m_agg2))
#> [1] -99.0292
```

<sup>Created on 2021-01-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
Because then I want to have a clean LRT + [other tests](https://github.com/easystats/performance/discussions), and some of them are relying on loglik. And the OLS and ML versions are to reproduce results from base R and lmtest (and REML fro compatibility with base R loglik()), so that we know that our solution is the best on the market

**Comment by DominiqueMakowski** [comment]
Because I reckon that many of the tests implemented in other software rely on static queries of stuff (typically `model$residuals`). By reimplementing (and improving) them using insight, we make them de facto compatible with a lot more models

**Comment by DominiqueMakowski** [comment]
Thanks to the wonderful @Tam-Pham that dived into the formulas the main issue here is in the process of being addressed, we will soon be able to close 🎉
