### ISSUE TITLE
model and resifual df methods for get_df

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#279]
I implemented a `get_df()`, which basically does what `df.residuals()` does, or `n - k`. So this is slightly different to what `parameters::degrees_of_freedom()` does, which returns the df for the parameters to do tests:

```r
library(insight)
library(parameters)

model <- lm(Sepal.Length ~ Petal.Length * Species, data = iris)
get_df(model)
#> [1] 144
degrees_of_freedom(model)
#> [1] 144

model <- glm(vs ~ mpg * cyl, data = mtcars, family = "binomial")
get_df(model)
#> [1] 28
degrees_of_freedom(model)
#> [1] Inf
```

We may think of just having the methods `"residual"` (which is equal to `method = "any"`) or `"model"`, which would return https://github.com/easystats/performance/issues/173.

_Originally posted by @strengejacke in https://github.com/easystats/insight/issues/273#issuecomment-753630791_

**Comment by strengejacke** [comment]
@mattansb @DominiqueMakowski thoughts?

**Comment by mattansb** [comment]
Can it also return other dfs? Like the model df we discussed somewhere?

**Comment by strengejacke** [comment]
Not yet, but this is what I have in mind:

> We may think of just having the methods "residual" (which is equal to method = "any") or "model", which would return easystats/performance#173
