### ISSUE TITLE
Support for older `R` versions

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#284]
Hi,

The new version of `modelsummary` now depends on `insight`, `performance` and `parameters`.

Today, I noticed that my tests failed on version 3.5 because `insight` has incremented the required version to 3.6. I'm sure there was a good reason for this, but I'm curious about your long term development plans.

R 3.5.3 was released in March 2019, so it feels a bit early to be dropping support.

Obviously, it's totally fine if `insight` et al. want to stay at the bleeding edge. I'll just have to switch it back to Suggests instead of Imports. No big deal. Just curious about your plans and thoughts on the issue.

**Comment by vincentarelbundock** [comment]
For reference, `modelsummary` is a dependency heavy package, and here are the other minimum required versions:

> checkmate 3.0.0
> broom 3.1
> generics 3.1
> glue 3.2
> kableExtra 3.1
> tables 2.12

**Comment by vincentarelbundock** [comment]
And by accident after I opened this issue I read this tweet by the `margins` creator:

https://twitter.com/thosjleeper/status/1350435512180473862

<img width="661" alt="Screen Shot 2021-01-16 at 09 43 36" src="https://user-images.githubusercontent.com/987057/104814907-59273f80-57df-11eb-819b-bf50f233998f.png">

**Comment by strengejacke** [comment]
There was mainly the reason to support `get_data()` for htest objects (https://github.com/easystats/insight/issues/258#issuecomment-750152806).

**Comment by vincentarelbundock** [comment]
I see. But this is incorrect, though:

> Issue is "resolved", min. requirement is now R >= 3.6. I mean, even lme4 does not run on R 3.5 any longer (according to the GitHub CI checks), so maybe we can say that insight at least needs R 3.6? Or is this a bad solution?

CRAN shows that `lme4` supports 3.2.0.

https://cran.r-project.org/web/packages/lme4/index.html

IMO, a better approach would be (a) support installation on older version, (b) use github actions to test older versions, (c) skip tests that we know are failing on older versions using:

```r
testthat::skip_if(getRversion() < '3.6.6')
```

This approach would allow people on university clusters or in corporate environments to use `easystats`, and it would be explicit.

**Comment by strengejacke** [comment]
Yeah, that might be an option. So we might roll back to depending on R >= 3.5. However, not sure when certain functions were first introduced, e.g. `isFALSE`? Not sure how much a hassle it would be to scan the code for functions that are newer than R3.5...

@mattansb @IndrajeetPatil @DominiqueMakowski any thoughts?

**Comment by mattansb** [comment]
Seems reasonable to roll back to 3.5.
In effectsize I (used to) add GH actions to test on 3.5,  and would hunt down changes (such as  adding isFALSE) in the R news docs 🤷‍♂️

**Comment by vincentarelbundock** [comment]
One approach would be to crawl the namespace of the [`backports` package](https://github.com/r-lib/backports) since it reimplements all functions not available pre-3.0.0. Then just grep those.

I can give this a shot eventually.

**Comment by vincentarelbundock** [comment]
"Eventually" means "now" apparently. Those are the functions in `backports` that are called somewhere in `insight`:

> anyNA <3.2.0
> isFALSE < 3.5.0
> isTRUE < 3.5.0
> trimws < 3.3.0
> isNamespaceLoaded < 3.2.0
> capture.output < 3.3.0
> str2lang < 3.6.0

So in principle you could get support for 3.3.0 by finding alternatives to two calls to the `str2lang` function and by adding two internal functions (`isTRUE` and `isFALSE`), which are one liners and can be lifted off the `backports` GPL code easily:

```r
isFALSE = function(x) {
  is.logical(x) && length(x) == 1L && !is.na(x) && !x
}
```

https://github.com/r-lib/backports/blob/master/R/isFALSE.R

**Comment by strengejacke** [comment]
It would be really **great** if you could create this list for other easystats-packages as well :-)

**Comment by strengejacke** [comment]
what about `sigma()`?

**Comment by strengejacke** [comment]
Just saw in the lme4-code, sigma is >= 3.30

```r
if(getRversion() >= "3.3.0") {
    importFrom("stats", sigma)
} else {
    export(sigma)
}
```

**Comment by vincentarelbundock** [comment]
`performance`:

> dQuote
> capture.output
> isTRUE
> anyNA

`parameters`:

>  isNamespaceLoaded < 3.2.0
> isTRUE < 3.5.0
>  isFALSE < 3.5.0
>  trimws < 3.3.0
>  dQuote
>  capture.output < 3.3.0


`backports` also has `suppressWarnings` and `suppressMessages`, but I'm not sure what changed in those functions.

For reference, all I did is execute this command in my terminal inside the repo, where `rg` is the `ripgrep` command (would also work with the silver searcher or somesuch):

```bash
rg "anyNA|asplit|capture.output|deparse1|dir.exists|dotsElt|dotsLength|dQuote|endsWith|errorCondition|file.info|file.mode|file.mtime|file.size|FUNS|get_backports|get0|hasName|isFALSE|isNamespaceLoaded|isTRUE|lengths|list2DF|R_user_dir|removeSource|sQuote|startsWith|str2expression|str2lang|strrep|suppressMessages|suppressWarnings|trimws|tryInvokeRestart|URLencode|vignetteInfo|warningCondition"
```

**Comment by mattansb** [comment]
I can't roll back `effectsize` before `insight` is rolled back.... How do we proceed? (waiting to submit to CRAN)

**Comment by IndrajeetPatil** [comment]
Can we please go ahead with `effectsize` submission with `3.6` and revisit the rolling back issue in the next few days? 
It's too late to start rolling back changes **now** while the package is already being reviewed `CRAN`.

I am desperately waiting for `effectsize` to make it to `CRAN`, so that I can update `tidyBF`, `statsExpressions`, and then `ggstatsplot`. All 3 of them are currently broken, and I don't want to be flooded with user questions about why suddenly things have stopped working.  😿

**Comment by mattansb** [comment]
Sounds reasonable - @strengejacke @DominiqueMakowski do you concur?

**Comment by strengejacke** [comment]
The roll back can be done with the next update round, but for now we have to stick to 3.6, as insight and parameters are just updated on CRAN.

**Comment by strengejacke** [comment]
I think going back to R >= 3.3 should be enough, so it's mainly isTRUE or isFALSE. Basically, each package just needs to have this file: https://github.com/easystats/insight/blob/master/R/backports.R (I'll add some functions if necessary), and then in the Description file adding "Depends: R (>= 3.3)".

**Comment by strengejacke** [comment]
(note that you might need to document the functions, I updated the file and wait for checks to pass...)

**Comment by strengejacke** [comment]
Some tests may fail, on older R versions, I simply wrapped those in

```r
if (getRversion() >= "3.6.0") {
...
}
```

Note that we should activate older R versions in the GitHub CI (I only added win/ubuntu, mac seems to be less stable on GitHub CI).

**Comment by mattansb** [comment]
So are we rolling back to 3.3.0?

> Some tests may fail, on older R versions, I simply wrapped those in

This can be `skip_if(getRversion() >= "3.6.0")`

**Comment by strengejacke** [comment]
Is `skip_if(getRversion() >= "3.6.0")` recognized by GitHub CI as well? I prefer to rely on good old base R ;-) I think back to R 3.3 is not necessary, 3.5 might be enough. But at least the backport.R file I created should cover all functions we're using back to R 3.3.

**Comment by IndrajeetPatil** [comment]
> Is skip_if(getRversion() >= "3.6.0") recognized by GitHub CI as well?

Yes, it is. I use conditions like these all the time for testing and actions never fail on GitHub

https://github.com/IndrajeetPatil/tidyBF/blob/1943bdf631f7182d07760552bd9761f3444e5feb/tests/testthat/test-bf_oneway_anova.R#L3-L7

**Comment by vincentarelbundock** [comment]
I had not really thought about it, but does there need to be an export at all? If it’s an internal function, probably not... I wonder what happens on older versions if people have backports package loaded. I suppose they’ll get a warning about masked function.

**Comment by strengejacke** [comment]
everything should be addressed now...

**Comment by vincentarelbundock** [comment]
This is amazing. You're the best!
