### ISSUE TITLE
Use mostattributes in format_table

### ISSUE THREAD

**Issue by mattansb** [easystats/insight#288]
``` r
df <- mtcars[1:3, 1:3]
attr(df, "table_footer") <- "This is a footer"
attributes(df)
#> $names
#> [1] "mpg"  "cyl"  "disp"
#> 
#> $row.names
#> [1] "Mazda RX4"     "Mazda RX4 Wag" "Datsun 710"   
#> 
#> $class
#> [1] "data.frame"
#> 
#> $table_footer
#> [1] "This is a footer"

df2 <- insight::format_table(df, digits = 3, preserve_attributes = TRUE)
attributes(df2)
#> $names
#> [1] "mpg"  "cyl"  "disp"
#> 
#> $class
#> [1] "data.frame"
#> 
#> $row.names
#> [1] 1 2 3
```

<sup>Created on 2021-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Should work with the `preserve_attributes` argument (https://easystats.github.io/insight/reference/format_table.html)

**Comment by mattansb** [comment]
But as you see... it does not :(

**Comment by strengejacke** [comment]
Ups, I didn't see that. Will dig into it.

**Comment by mattansb** [comment]
@strengejacke may I ask what is the advantage of using `modifyList()` over `mostattributes()` in this case?

**Comment by strengejacke** [comment]
One advantage is that I know `modifyList()`, but haven't heard of `mostattributes()` before ;-) And even modifyList was new to me, I saw it somewhere in the code from @DominiqueMakowski

**Comment by strengejacke** [comment]
But feel free to revise the code! Would it be, instead of 

```r
attributes(x) <- utils::modifyList(att, attributes(x))
```

it is 

```r
mostattributes(x) <- att
```

?

**Comment by mattansb** [comment]
exactly (:
I'll make the change soonish

**Comment by mattansb** [comment]
I reverted the change. It broke stuff and I'm too lazy to try and figure out what...
