### ISSUE TITLE
Support for tidymodels

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#289]
https://github.com/easystats/report/issues/122

``` r
library(tidymodels)

m <- linear_reg() %>% 
  set_engine("lm") %>% 
  set_mode("regression") %>% 
  fit(mpg ~ am + vs, data = mtcars)

class(m)
#> [1] "_lm"       "model_fit"
m$fit # actual model
#> 
#> Call:
#> stats::lm(formula = mpg ~ am + vs, data = data)
#> 
#> Coefficients:
#> (Intercept)           am           vs  
#>      14.594        6.067        6.929
m$spec # specifications
#> Linear Regression Model Specification (regression)
#> 
#> Computational engine: lm 
#> 
#> Model fit template:
#> stats::lm(formula = missing_arg(), data = missing_arg(), weights = missing_arg())
m$preproc # data-transformation related info
#> $y_var
#> [1] "mpg"
```

<sup>Created on 2021-01-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It seems like we could enable support fairly easily by just passing the function to the "fit" object of the list (did not test more extensively than that tho ^^)

(I just saw in their doc they have actual "sections" for different examples (https://parsnip.tidymodels.org/reference/linear_reg.html), which I didn't know we could do, but we might want to, as we have a lot of different "sections" in some of our examples for now separated by comments)

**Comment by DominiqueMakowski** [comment]
I think we just need to add:

```r
method.model_fit <- function(x) method(x$fit)
```

to enable support

**Comment by DominiqueMakowski** [comment]
@IndrajeetPatil you might be interested in looking into that with your comprehensive eye, as you could then enable support for tidymodels in your packages as well

**Comment by IndrajeetPatil** [comment]
Yeah, would love to work on this. Just need to stabilize the `API` for my packages, work on tests for `easystats` packages, and then I will have more time to work on adding new features. 😅

**Comment by strengejacke** [comment]
> (I just saw in their doc they have actual "sections" for different examples (https://parsnip.tidymodels.org/reference/linear_reg.html), which I didn't know we could do, but we might want to, as we have a lot of different "sections" in some of our examples for now separated by comments)

I don't see any sections in their examples?

**Comment by DominiqueMakowski** [comment]
They do, below the "Engine" section https://parsnip.tidymodels.org/reference/linear_reg.html#engine-details

**Comment by strengejacke** [comment]
That's not the examples.

**Comment by DominiqueMakowski** [comment]
@mbac since you opened the initial issue on 'report' about tidymodels support, would you be interested in contributing and trying out to make a pull request to enable its support here in insight? You can take a look [here](https://github.com/easystats/insight/commit/c6b9af9678bb7de501282fe9a3dce73c894d03d1) on how it works for one method (`find_formula()`), essentially we need to do that for other methods (see the commented lines in the tests [here](https://github.com/easystats/insight/blob/master/tests/testthat/test-tidymodels.R)).

**Comment by mbac** [comment]
Thanks for the proposal; however, I'm an anesthesiologist currently working between Pain Medicine and COVID-19 patients, so my profile isn't exactly that of a programmer.

I do dabble in data analysis for our research, though, and I would gladly help you test any such implementation…

**Comment by strengejacke** [comment]
``` r
library(tidymodels)

linear_reg() %>% 
  set_engine("lm") %>% 
  set_mode("regression") %>% 
  fit(mpg ~ am + vs, data = mtcars) %>% 
  parameters::model_parameters()
#> Parameter   | Coefficient |   SE |         95% CI | t(29) |      p
#> ------------------------------------------------------------------
#> (Intercept) |       14.59 | 0.93 | [12.78, 16.41] | 15.76 | < .001
#> am          |        6.07 | 1.27 | [ 3.57,  8.57] |  4.76 | < .001
#> vs          |        6.93 | 1.26 | [ 4.46,  9.40] |  5.49 | < .001
```

<sup>Created on 2021-03-22 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
