### ISSUE TITLE
Prior description wrong?

### ISSUE THREAD

**Issue by mischavk** [easystats/insight#290]
Hi,
I have question regarding the Bayesian correlation estimates provided in the package. If I understand it correctly, these depend on the BayesFactor::correlationBF function. In this function, a beta distribution is used for the _rho_ parameter:
"Noninformative priors are assumed for the population means and variances of the two population; a shifted, scaled beta(1/rscale,1/rscale) prior distribution is assumed for rho (note that rscale is called kappa by Ly et al. 2015; we call it rscale for consistency with other BayesFactor functions)." (https://www.rdocumentation.org/packages/BayesFactor/versions/0.9.12-4.2/topics/correlationBF)
This makes sense for a correlation, with the "ultrawide" prior corresponding to a uniform distribution.

Yet in your output, you call the prior distribution a "Cauchy". I don't really understand - maybe it's due to a typo, because the Bayesian t-Test in BayesFactor uses a Cauchy prior for the effect size? Or am I missing something?

**Comment by DominiqueMakowski** [comment]
>  a shifted, scaled beta(1/rscale,1/rscale) prior distribution is assumed for rho

``` r
insight::get_priors(BayesFactor::correlationBF(iris$Sepal.Length, iris$Sepal.Width))
#>   Parameter Distribution Location Scale
#> 1       rho         beta        3     3
```

<sup>Created on 2021-01-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


I put the location to the scale, to reflect the (first_arg, second_arg) kind of logic, but maybe it would be more accurate to put NA, as beta have no "location" parameter per se? 🤔 

Also, I transformed the scale to 1/rscale, as mentioned in the docs, so fro 1/3 it becomes "3".

**Comment by IndrajeetPatil** [comment]
Good catch!

This also makes output consistent with JASP's prior specification

![image](https://user-images.githubusercontent.com/11330453/106742203-004c0980-661d-11eb-8b37-3e18d5f5f3ce.png)
