### ISSUE TITLE
CIs for lme4 predictions with no random in newdata

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#298]
Basically I'd like to make predictions without random factors in the data (a fairly common case), but it fails. 

``` r
x <- lme4::lmer(mpg ~ am + (1 | cyl), data = mtcars)

newdata <- mtcars[c("am")]
rez <- insight::get_predicted(x, newdata=newdata)
#> Error in eval(predvars, data, env): object 'mpg' not found
```

<sup>Created on 2021-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

And from there I have a few questions as I'm not familiar with @strengejacke's code (previously relying on bootmer).

### 1)

First of all, these lines seems unnecessary we can delete them right?

https://github.com/easystats/insight/blob/41a0fb26efee7076d361ccdfb0d19fd786e6c12b/R/get_predicted.R#L163-L167

### 2)

https://github.com/easystats/insight/blob/41a0fb26efee7076d361ccdfb0d19fd786e6c12b/R/get_predicted.R#L169-L178

New here, if no new data is passed, you extract the model's data, and get the model matrix. But this doesn't work if a new data is passed, as most new data don't have the response variable in (as this is what they try to predict). 

So two solutions seems possible:

The first is that the model matrix is obtained from the new data + the predictions, like so:

https://github.com/easystats/insight/blob/41a0fb26efee7076d361ccdfb0d19fd786e6c12b/R/get_predicted.R#L177

Should be something like:

```r
newdata[[find_response(x)]] <- out # (the predicted values) 
mm <- stats::model.matrix(stats::terms(x), newdata)
```

And the second is that the model matrix is *always* the one of the "original data":

```r
newdata[[find_response(x)]] <- out # (the predicted values) 
mm <- stats::model.matrix(stats::terms(x), get_data(x))
```

Does that make sense?

**Comment by strengejacke** [comment]
> Basically I'd like to make predictions without random factors in the data (a fairly common case), but it fails.
> 
> ```r
> x <- lme4::lmer(mpg ~ am + (1 | cyl), data = mtcars)
> 
> newdata <- mtcars[c("am")]
> rez <- insight::get_predicted(x, newdata=newdata)
> #> Error in eval(predvars, data, env): object 'mpg' not found
> ```
> 
> Created on 2021-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)
> 
> And from there I have a few questions as I'm not familiar with @strengejacke's code (previously relying on bootmer).

Random effects needs to be included, but set to `NA` (depends on the package, I think glmmTMB needs another value, must look into the ggeffects code)

> 
> ### 1)
> First of all, these lines seems unnecessary we can delete them right?
> 
> https://github.com/easystats/insight/blob/41a0fb26efee7076d361ccdfb0d19fd786e6c12b/R/get_predicted.R#L163-L167
> 

I think so, the code is from you. Or have you copied it from somewhere?

> ### 2)
> https://github.com/easystats/insight/blob/41a0fb26efee7076d361ccdfb0d19fd786e6c12b/R/get_predicted.R#L169-L178
> 
> New here, if no new data is passed, you extract the model's data, and get the model matrix. But this doesn't work if a new data is passed, as most new data don't have the response variable in (as this is what they try to predict).
> 
> So two solutions seems possible:
> 
> The first is that the model matrix is obtained from the new data + the predictions, like so:
> 
> https://github.com/easystats/insight/blob/41a0fb26efee7076d361ccdfb0d19fd786e6c12b/R/get_predicted.R#L177
> 
> Should be something like:
> 
> ```r
> newdata[[find_response(x)]] <- out # (the predicted values) 
> mm <- stats::model.matrix(stats::terms(x), newdata)
> ```
> 
> And the second is that the model matrix is _always_ the one of the "original data":
> 
> ```r
> newdata[[find_response(x)]] <- out # (the predicted values) 
> mm <- stats::model.matrix(stats::terms(x), get_data(x))
> ```
> 
> Does that make sense?

Only the first option, i.e. adding the response, but to a fake value (as it's not required, and doesn't change anything).

``` r
library(insight)
library(lme4)
#> Loading required package: Matrix
m <- lmer(Sepal.Width ~ Petal.Length + Petal.Width + (1 | Species), data = iris)

as.data.frame(get_predicted(m, newdata = data.frame(
  Sepal.Width = 1,
  Petal.Length = c(1, 2, 3, 4),
  Petal.Width = c(2, 2, 3, 3),
  Species = "versicolor"
)))
#>   Predicted        SE   CI   CI_low  CI_high
#> 1  3.143441 0.7051942 0.95 1.761286 4.525596
#> 2  3.289470 0.6866668 0.95 1.943628 4.635313
#> 3  4.046061 0.7133077 0.95 2.648004 5.444118
#> 4  4.192090 0.7007264 0.95 2.818692 5.565489

as.data.frame(get_predicted(m, newdata = data.frame(
  Sepal.Width = 0,
  Petal.Length = c(1, 2, 3, 4),
  Petal.Width = c(2, 2, 3, 3),
  Species = "versicolor"
)))
#>   Predicted        SE   CI   CI_low  CI_high
#> 1  3.143441 0.7051942 0.95 1.761286 4.525596
#> 2  3.289470 0.6866668 0.95 1.943628 4.635313
#> 3  4.046061 0.7133077 0.95 2.648004 5.444118
#> 4  4.192090 0.7007264 0.95 2.818692 5.565489

as.data.frame(get_predicted(m, newdata = data.frame(
  Sepal.Width = 100,
  Petal.Length = c(1, 2, 3, 4),
  Petal.Width = c(2, 2, 3, 3),
  Species = "versicolor"
)))
#>   Predicted        SE   CI   CI_low  CI_high
#> 1  3.143441 0.7051942 0.95 1.761286 4.525596
#> 2  3.289470 0.6866668 0.95 1.943628 4.635313
#> 3  4.046061 0.7133077 0.95 2.648004 5.444118
#> 4  4.192090 0.7007264 0.95 2.818692 5.565489
```

<sup>Created on 2021-02-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by strengejacke** [comment]
For `include_random = FALSE`, we can set the random effects to `NA` (when these are not present):

``` r
library(insight)
library(lme4)
#> Loading required package: Matrix
m <- lmer(Sepal.Width ~ Petal.Length + Petal.Width + (1 | Species), data = iris)

as.data.frame(get_predicted(m, newdata = data.frame(
  Sepal.Width = 100,
  Petal.Length = c(1, 2, 3, 4),
  Petal.Width = c(2, 2, 3, 3),
  Species = NA
), include_random = F))
#>   Predicted        SE   CI   CI_low  CI_high
#> 1  3.143441 0.7051942 0.95 1.761286 4.525596
#> 2  3.289470 0.6866668 0.95 1.943628 4.635313
#> 3  4.046061 0.7133077 0.95 2.648004 5.444118
#> 4  4.192090 0.7007264 0.95 2.818692 5.565489
```

<sup>Created on 2021-02-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by DominiqueMakowski** [comment]
I added some more tests and refactored it a bit, but it all gives very very very weird results:

- for linear mixed models, when compared to other methods (bootstrap or [merTools](https://cran.rstudio.com/web/packages/merTools/vignettes/Using_predictInterval.html)), the analytical results are really small
- for logistic mixed models, as compared to the results say from glmmTMB, the results for the CIs for glmer is off the chart (seems to be not transformed into probabilities)

I think that having this implemented in a robust way is critical (so that it can be used as a basis for modelbased & ggeffects)

**Comment by strengejacke** [comment]
The general idea is to get the variance-covariance matrix and matrix multiply it with the model matrix, to get CIs for predictions (in a fast alternative way compared to bootstrapping). This is what I basically implemented in ggeffects, it returns the vcov for the _predictions_: https://github.com/strengejacke/ggeffects/blob/master/R/vcov.R
So you only need to compute the sqrt of the diagonal to get the SE, multiply by 1.96 and you have the CI.

However, as you can see in the code from `vcov.R`, starting from line 188, there are several things to consider: contrasts, polynomial terms, and removing possible duplicated rows/columns from the model matrix to avoid memory allocation issues. So if you want a stable implementation, even for many other model objects, you could copy that code.

2nd, for ZI or hurdle models (glmmTMB, pscl), you can make predictions conditioned on the count component only, or the "whole" model (i.e. count component, taking the zero-inflation or hurdle part into account). Predictions are fairly easy, `mu*(1-p)` (mu = expected mean of the count model, p = probability of passing the hurdle of the hurdle/ZI model). However, since you have two different distributions here (poisson or similar for count, binomial for hurdle), you cannot easily calculate the SE / CIs for those predictions (you can't "multiply" the CIs from the count model with the CIs from the hurdle/zi model). Thus, it's recommended to simulate response values and extract quantiles to get the CIs for zero-inflated models where you want predictions of the outcome, conditioned on the ZI component. This is described here (https://strengejacke.github.io/ggeffects/articles/introduction_randomeffects.html#marginal-effects-for-zero-inflated-mixed-models-1), and I think the code is somewhere here: https://github.com/strengejacke/ggeffects/blob/master/R/predict_zero_inflation.R

**Comment by DominiqueMakowski** [comment]
> The general idea is to get the variance-covariance matrix and matrix multiply it with the model matrix, to get CIs for predictions

But the problem is that the current implementation (which I believed you adapted straight from ggeffects?) gives impossible (i.e, outside 0-1 for probabilities) results for GLMMs (at least logistic), and for LMMs gives *very* different results from other bootstrap-based methods, so it's not currently an "alternative" but something entirely different. Note that it's also possible that I messed something up by copying / editing it from modelbased to here.

> So if you want a stable implementation, even for many other model objects, you could copy that code.

Isn't that what get_varcov does?

In any case, you know better all this prediction jazz, so I'll trust you, but I like when the comparison with other solutions are in the same line

**Comment by strengejacke** [comment]
> But the problem is that the current implementation (which I believed you adapted straight from ggeffects?) gives impossible (i.e, outside 0-1 for probabilities) results for GLMMs (at least logistic),

No, exactly the opposite is the case, see https://strengejacke.github.io/ggeffects/articles/technical_stata.html
The vcov/prediction-SE are on the scale of the linear predictor, so you need to backtransform via link-inverse.

> and for LMMs gives very different results from other bootstrap-based methods

Might be, because it's no bootstrapped method. However, it depends whether you take random effects into account or not. If so, you have to add "sigma" (or random effect variances) to the sqrt of the SE to get wider (i.e. "prediction") intervals.

**Comment by DominiqueMakowski** [comment]
Then the implementation [here](https://github.com/easystats/insight/blob/master/R/get_predicted.R#L189-L212) must be broken, because these tests are nowhere near passing 😕 

https://github.com/easystats/insight/blob/ba944366125d5bfd6c0773154203b7b7dc6f5a8c/tests/testthat/test-get_predicted.R#L51-L68

**Comment by strengejacke** [comment]
I think [in this commit](https://github.com/easystats/insight/commit/e2d3bf027e889f34db4099d88d9d4e54c86552d7) you removed this code:

```r
    if (ci_type == "prediction") {
      se <- sqrt(diag(var_matrix) + get_variance_residual(x))
    } else {
      se <- sqrt(diag(var_matrix))
    }
```

This is what either returned prediction intervals (similar to merTools) or confidence intervals. However, prediction intervals won't be identical to merTools, I think, because merTools does some bootstrapping?

**Comment by DominiqueMakowski** [comment]
It's still there

https://github.com/easystats/insight/blob/ba944366125d5bfd6c0773154203b7b7dc6f5a8c/R/get_predicted.R#L205-L209

I specified "prediction" intervals in the example line 53 to get "closer" to the ones given by lme4::bootmer and merTools, which are even bigger than it (default confidence intervals being smaller than predictions ones)

as far as I tried, no combination of any arguments, both in get_predicted and the comparison packages, led to somewhat close results (i.e., currently get_predicted prediction + confidence intervals are very different from any results given by merTools, bootmer, emmeans and, it seems, the rstanarm version which gives similar results to merTools)

**Comment by strengejacke** [comment]
I'll look into it. Maybe we can find a cleaner re implementation of what I used in ggeffects.

**Comment by strengejacke** [comment]
When not taking random effects into account, this approach is pretty consistent with emmeans / ggeffects, not so with merTools. For including random effects variances, I did something slightly different in ggeffects, results don't match (must see why), however, emmeans seems to ignore sigma?

``` r
library(lme4)
#> Loading required package: Matrix
data("sleepstudy")
m <- lmer(Reaction ~ Days + (1 + Days | Subject), data = sleepstudy)
d <- data.frame(
  Reaction = 0, 
  Days = 1:9,
  Subject = 372
)

p <- predict(m, d, re.form = NA)

vc <- vcov(m)
mm <- model.matrix(terms(m), d)
p_vc <- mm %*% vc %*% t(mm)

ci_low <- p - qnorm(.975) * sqrt(diag(p_vc))
ci_high <- p + qnorm(.975) * sqrt(diag(p_vc))


cbind(p, ci_low, ci_high)
#>          p   ci_low  ci_high
#> 1 261.8724 248.5703 275.1745
#> 2 272.3397 258.4352 286.2442
#> 3 282.8070 267.7046 297.9093
#> 4 293.2742 276.5056 310.0429
#> 5 303.7415 284.9626 322.5205
#> 6 314.2088 293.1738 335.2438
#> 7 324.6761 301.2102 348.1420
#> 8 335.1434 309.1206 361.1662
#> 9 345.6107 316.9387 374.2826

ggeffects::ggpredict(m, "Days [1:9]")
#> # Predicted values of Reaction
#> # x = Days
#> 
#> x | Predicted |           95% CI
#> --------------------------------
#> 1 |    261.87 | [248.57, 275.17]
#> 2 |    272.34 | [258.44, 286.24]
#> 3 |    282.81 | [267.70, 297.91]
#> 4 |    293.27 | [276.51, 310.04]
#> 5 |    303.74 | [284.96, 322.52]
#> 6 |    314.21 | [293.17, 335.24]
#> 7 |    324.68 | [301.21, 348.14]
#> 9 |    345.61 | [316.94, 374.28]
#> 
#> Adjusted for:
#> * Subject = 0 (population-level)

emmeans::emmeans(m, "Days", at = list(Days = 1:9))
#>  Days emmean    SE df lower.CL upper.CL
#>     1    262  6.79 17      248      276
#>     2    272  7.09 17      257      287
#>     3    283  7.71 17      267      299
#>     4    293  8.56 17      275      311
#>     5    304  9.58 17      284      324
#>     6    314 10.73 17      292      337
#>     7    325 11.97 17      299      350
#>     8    335 13.28 17      307      363
#>     9    346 14.63 17      315      376
#> 
#> Degrees-of-freedom method: kenward-roger 
#> Confidence level used: 0.95

merTools::predictInterval(m, d, "fixed", level = .95, stat = "mean")[c("fit", "lwr", "upr")]
#> Registered S3 method overwritten by 'broom.mixed':
#>   method      from 
#>   tidy.gamlss broom
#>        fit      lwr      upr
#> 1 261.5037 212.8201 312.9265
#> 2 272.4806 216.8511 326.1789
#> 3 281.6212 227.9005 338.2900
#> 4 293.1885 235.2686 348.6744
#> 5 304.4379 252.9290 357.1546
#> 6 314.9771 259.5778 366.7699
#> 7 326.3494 265.9145 384.4217
#> 8 336.4021 281.2771 398.1472
#> 9 347.5103 286.4504 406.5773




ci_low <- p - qnorm(.975) * (sqrt(diag(p_vc) + insight::get_variance_residual(m)))
ci_high <- p + qnorm(.975) * (sqrt(diag(p_vc) + insight::get_variance_residual(m)))
cbind(p, ci_low, ci_high)
#>          p   ci_low  ci_high
#> 1 261.8724 209.9795 313.7653
#> 2 272.3397 220.2891 324.3902
#> 3 282.8070 230.4237 335.1902
#> 4 293.2742 240.3865 346.1620
#> 5 303.7415 250.1825 357.3006
#> 6 314.2088 259.8177 368.6000
#> 7 324.6761 269.2995 380.0528
#> 8 335.1434 278.6358 391.6510
#> 9 345.6107 287.8352 403.3862

ggeffects::ggpredict(m, "Days [1:9]", type = "re")
#> # Predicted values of Reaction
#> # x = Days
#> 
#> x | Predicted |           95% CI
#> --------------------------------
#> 1 |    261.87 | [180.02, 343.73]
#> 2 |    272.34 | [190.39, 354.29]
#> 3 |    282.81 | [200.64, 364.97]
#> 4 |    293.27 | [210.79, 375.76]
#> 5 |    303.74 | [220.82, 386.66]
#> 6 |    314.21 | [230.75, 397.67]
#> 7 |    324.68 | [240.57, 408.78]
#> 9 |    345.61 | [259.91, 431.31]
#> 
#> Adjusted for:
#> * Subject = 0 (population-level)
#> 
#> Intervals are prediction intervals.

emmeans::emmeans(m, "Days", at = list(Days = 1:9), sigma = 654)
#>  Days emmean    SE df lower.CL upper.CL
#>     1    262  6.79 17      248      276
#>     2    272  7.09 17      257      287
#>     3    283  7.71 17      267      299
#>     4    293  8.56 17      275      311
#>     5    304  9.58 17      284      324
#>     6    314 10.73 17      292      337
#>     7    325 11.97 17      299      350
#>     8    335 13.28 17      307      363
#>     9    346 14.63 17      315      376
#> 
#> Degrees-of-freedom method: kenward-roger 
#> Confidence level used: 0.95

merTools::predictInterval(m, d, "full", level = .95, stat = "mean")[c("fit", "lwr", "upr")]
#>        fit      lwr      upr
#> 1 275.1470 219.5796 333.5684
#> 2 288.1736 230.8457 339.3763
#> 3 297.8271 245.9751 349.6232
#> 4 311.5600 257.8399 372.8692
#> 5 324.3257 270.5723 380.8902
#> 6 335.5454 278.1409 400.6488
#> 7 346.0719 284.1998 405.7396
#> 8 358.4987 293.2448 421.1427
#> 9 369.5459 304.1219 434.0631
```

So I would personally not compare merTools' results to ours. The approach is also a different one, it's based on simulations by multivariate normal distributions (similar to `parameters::simulate_parameters()`). I would therefore try to implement the approach we already have, also for other models.

**Comment by strengejacke** [comment]
btw, these look similar:

```r
merTools::predictInterval(m, d, "fixed", level = .95, stat = "mean")[c("fit", "lwr", "upr")]
#> Registered S3 method overwritten by 'broom.mixed':
#>   method      from 
#>   tidy.gamlss broom
#>        fit      lwr      upr
#> 1 261.5037 212.8201 312.9265
#> 2 272.4806 216.8511 326.1789
#> 3 281.6212 227.9005 338.2900
#> 4 293.1885 235.2686 348.6744
#> 5 304.4379 252.9290 357.1546
#> 6 314.9771 259.5778 366.7699
#> 7 326.3494 265.9145 384.4217
#> 8 336.4021 281.2771 398.1472
#> 9 347.5103 286.4504 406.5773




ci_low <- p - qnorm(.975) * (sqrt(diag(p_vc) + insight::get_variance_residual(m)))
ci_high <- p + qnorm(.975) * (sqrt(diag(p_vc) + insight::get_variance_residual(m)))
cbind(p, ci_low, ci_high)
#>          p   ci_low  ci_high
#> 1 261.8724 209.9795 313.7653
#> 2 272.3397 220.2891 324.3902
#> 3 282.8070 230.4237 335.1902
#> 4 293.2742 240.3865 346.1620
#> 5 303.7415 250.1825 357.3006
#> 6 314.2088 259.8177 368.6000
#> 7 324.6761 269.2995 380.0528
#> 8 335.1434 278.6358 391.6510
#> 9 345.6107 287.8352 403.3862
```

**Comment by strengejacke** [comment]
@DominiqueMakowski you know we're opening Pandora's Box here? ;-)

**Comment by DominiqueMakowski** [comment]
Haha yeah I know... But that's a challenge we are now ready to face :)

**Comment by strengejacke** [comment]
I think we can use our own function in general, no matter if the predict-functions returns se/ci. This makes maintenance probably easier:

``` r
library(insight)
m <- lm(Sepal.Length ~ Species + Sepal.Width, data = iris)
d <- data.frame(
  Sepal.Length = 0,
  Species = levels(iris$Species),
  Sepal.Width = mean(iris$Sepal.Width)
)

predict(m, newdata = d, se.fit = TRUE, interval = "confidence")$fit
#>        fit      lwr      upr
#> 1 4.708147 4.563053 4.853240
#> 2 6.166890 6.030397 6.303382
#> 3 6.654963 6.531309 6.778618
as.data.frame(get_predicted(m, newdata = d))
#>   Predicted         SE   CI   CI_low  CI_high
#> 1  4.708147 0.07341501 0.95 4.563053 4.853240
#> 2  6.166890 0.06906309 0.95 6.030397 6.303382
#> 3  6.654963 0.06256713 0.95 6.531309 6.778618


predict(m, newdata = d, se.fit = TRUE, interval = "prediction")$fit
#>        fit      lwr      upr
#> 1 4.708147 3.830516 5.585777
#> 2 6.166890 5.290640 7.043139
#> 3 6.654963 5.780622 7.529305
as.data.frame(get_predicted(m, newdata = d, ci_type = "prediction"))
#>   Predicted        SE   CI   CI_low  CI_high
#> 1  4.708147 0.4440672 0.95 3.830516 5.585777
#> 2  6.166890 0.4433685 0.95 5.290640 7.043139
#> 3  6.654963 0.4424032 0.95 5.780622 7.529305
```

<sup>Created on 2021-02-07 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by strengejacke** [comment]
``` r
library(insight)
## Dobson (1990) Page 93: Randomized Controlled Trial :
d <- data.frame(
  treatment = gl(3, 3),
  outcome = gl(3, 1, 9),
  counts = c(18, 17, 15, 20, 10, 20, 25, 13, 12)
)
m <- glm(counts ~ outcome + treatment, family = poisson(), data = d)

nd <- data.frame(
  counts = 0,
  treatment = factor(c(1, 2, 3, 1, 2, 3)),
  outcome = factor(c(1, 2, 1, 2, 1, 2), levels = c(1, 2, 3))
)

pr <- predict(m, newdata = nd, se.fit = TRUE, interval = "confidence", type = "link")
cbind(Predicted = pr$fit,
      CI_low = pr$fit - qnorm(.975)  * pr$se.fit,
      CI_high = pr$fit + qnorm(.975)  * pr$se.fit)
#>   Predicted   CI_low  CI_high
#> 1  3.044522 2.709567 3.379478
#> 2  2.590267 2.206528 2.974007
#> 3  3.044522 2.709567 3.379478
#> 4  2.590267 2.206528 2.974007
#> 5  3.044522 2.709567 3.379478
#> 6  2.590267 2.206528 2.974007
as.data.frame(get_predicted(m, newdata = nd, transform = NULL))
#>   Predicted        SE   CI   CI_low  CI_high
#> 1  3.044522 0.1708987 0.95 2.709567 3.379478
#> 2  2.590267 0.1957890 0.95 2.206528 2.974007
#> 3  3.044522 0.1708987 0.95 2.709567 3.379478
#> 4  2.590267 0.1957890 0.95 2.206528 2.974007
#> 5  3.044522 0.1708987 0.95 2.709567 3.379478
#> 6  2.590267 0.1957890 0.95 2.206528 2.974007
```

<sup>Created on 2021-02-07 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by strengejacke** [comment]
we now might expand the code used in `get_predicted.lm()` and `get_predicted.glm()` to other models, like gam etc. merMod / glmmTMB still need special handling, as well as zero-inflated. I'll look into glmmTMB and hurdle/zi later.

**Comment by DominiqueMakowski** [comment]
I see, so we'd basically have a generic and robust ".get_predicted"  that we use for all models, instead of relying on their respective predict() methods. Indeed, having one core function could tidy up the code and make it easier to build

**Comment by strengejacke** [comment]
>  instead of relying on their respective predict() methods

At least for predictions we rely on their predict method, but the SE / CI are calculated inside insight. We must see, as the support for other packages evolves, if we can leave the call to `predict()` in `.generic_predictions()`, or if these calls are so special that we need it inside the different class methods, and just pass the predicted values to `.generic_predictions()`.

We already have our first exceptions with merMod (at least a little bit different) and glmmTMB.

@DominiqueMakowski for glmmTMB or pscl::hurdle, how do we define the `type = "zi"`, when we only have the `transform` argument? We can have predictions on the response-scale for both only count model or conditioned on zi. Maybe with the `component` argument? Not sure what would be the most elegant way in terms of argument naming for `get_predicted()`.

**Comment by DominiqueMakowski** [comment]
> for glmmTMB or pscl::hurdle

I'm not very familiar with these models, but couldn't we have a `include_zi` (similar to include_random) or `include_components=c("ziz")`? Or is it a different kind of thing?

**Comment by strengejacke** [comment]
For zero inflated models were have types:
- link (count component only)
- response (expected mean taking zero inflation into account)
- zlink / zero (probability of passing the hurdle)

**Comment by DominiqueMakowski** [comment]
😕 mmh but if it's taking something into account, then it's more like the `include_*` args (include_random, include_smooth etc) than on the `transform`, which kind of changes the scale of the output but not what it is?

**Comment by DominiqueMakowski** [comment]
maybe we should actually rename the `transform` arg to like `scale` or `predicted_scale` 🤔

**Comment by strengejacke** [comment]
@DominiqueMakowski what's the state of this issue? can it be closed?

**Comment by DominiqueMakowski** [comment]
I think so
