### ISSUE TITLE
model_info: nobs and link_fun

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#30]
Started working on the formatting function for model type names. In model_info(), $nobs and $link_fun appeared as salient, as I would have expected $n_obs and $link_function. Do you want me to help to change it or do you think it's too much and we should leave it like that ^^?

**Comment by strengejacke** [comment]
It's just changing the names in model_info for the return value, right? Shouldn't be much work.

**Comment by DominiqueMakowski** [comment]
done with #33
