### ISSUE TITLE
get_parameters for cor.test

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#300]
``` r
insight::get_parameters(cor.test(mtcars$mpg, mtcars$vs))
#> Warning: Parameters can't be retrieved for objects of class 'simpleError'.
#> NULL
```

<sup>Created on 2021-02-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by strengejacke** [comment]
I'm not sure we support any htest objects? So I'm not sure if it's a bug, or a "feature"... At least it should work with `model_parameters()`.

**Comment by DominiqueMakowski** [comment]
It stroke me as a convenient way to get that single value across different h tests

**Comment by strengejacke** [comment]
What is the parameter (estimate) for a t-test? The mean difference? the t-value?

**Comment by DominiqueMakowski** [comment]
The difference, since t would be the stat (yeah for t.test the param needs to be diff(x$estimate) I noticed that too)

**Comment by strengejacke** [comment]
You may check for different htests if it works now.

**Comment by DominiqueMakowski** [comment]
Summoning @IndrajeetPatil lord of tests 🙌

**Comment by IndrajeetPatil** [comment]
Seems to work:
(The parameter name for `chisq.test` is unexpected?)

``` r
insight::get_parameters(cor.test(mtcars$mpg, mtcars$vs))
#>                  Parameter  Estimate
#> 1 mtcars$mpg and mtcars$vs 0.6640389

insight::get_parameters(t.test(extra ~ 1, data = sleep))
#>   Parameter Estimate
#> 1     extra     1.54

insight::get_parameters(chisq.test(as.table(mtcars$cyl)))
#>   Parameter Estimate
#> 1 Parameter  15.9798
```

<sup>Created on 2021-02-10 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
