### ISSUE TITLE
get_predicted: add simulate option for freq models?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#307]
Related to https://github.com/easystats/performance/issues/202

Would it makes sense to have a `iterations` argument for `get_predicted()` which, if not NULL for frequentist models, returns simulated draws? But then we'll have to make sure `simulate()` is robust, or at least catch the eventual error. What do you think?

**Comment by strengejacke** [comment]
Well, it sounds like a useful approach. Why not?

**Comment by DominiqueMakowski** [comment]
I'll give it a shot

**Comment by DominiqueMakowski** [comment]
not sure where's the best place to [add the helper](https://github.com/easystats/insight/blob/master/R/get_predicted.R#L613-L628), in generic predictions or under each method?

**Comment by strengejacke** [comment]
ehm... does it matter?

**Comment by DominiqueMakowski** [comment]
well there's probably one solution that is more optimal and elegant...

**Comment by strengejacke** [comment]
I don't quite understand - you have _one_ helper function and want to add it under _each_ method (i.e. copy multiple times)?

**Comment by DominiqueMakowski** [comment]
basically I don't know how to best add that option for freq models since it seems like simulate(...) has to take the arguments from predict(...)

**Comment by strengejacke** [comment]
You can only simulate from a model, so you can't "condition" on fixed parameters (i.e. you can't use `newdata`, or the `vcov*` args). So when `iterations` is _not_ `NULL`, we simply call that helper function. Arguments we can use are just `ci`, I think.

**Comment by DominiqueMakowski** [comment]
This is added, but via `boot` instead of `simulate`, allowing hopefully for a more flexible solution

**Comment by strengejacke** [comment]
Yeah, should work, too, but a millions times slower ;-)

**Comment by strengejacke** [comment]
On the other hand, `simulate()` usually only returns response-values, not predicted values on link, response or other scales.

**Comment by strengejacke** [comment]
Finally, using `simulate()` for `pp_check()` might be more appropriate, since the "deviation" (or variation) of the simulated data should roughly be within the residual standard deviation, so simulations better "fit to the model", which in turn allows you to better compare the observed data against the actual model fit. I bet variation is larger for bootstrapped samples, but that's actually something we should check in some simulations.

**Comment by DominiqueMakowski** [comment]
mmh I thought simulate was some kind of wrapper, didn't know it corresponded to something different

**Comment by strengejacke** [comment]
I guess results may be similar, but bootstrapping takes random samples from the original data, while simulate is (roughly speaking) relying on `rnorm()` with SD = sigma / some variation.

**Comment by DominiqueMakowski** [comment]
Because currently it's quite nice the bootstrapping serves to simulate draws but also serves to compute bootstrapped CIs and all, whereas if we add simulate on top of it it will complexify the API (and my brain hurts already ^^)
