### ISSUE TITLE
model_info(x)$is_gam

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#308]
It'd be useful to check the model for a smooth term (`s(...)`), that can be present in classes such as "gam", "gamm", "list" (gamm4), "stanreg" and "brmsfit"

**Comment by strengejacke** [comment]
Would you like to check for smooth terms, or for smooth terms _and_ if model class is gam/stan? Not sure if there are edge-cases....

**Comment by DominiqueMakowski** [comment]
yes we could probably to `if(!is.null(find_smooth(x)))`, not sure about the edge cases either but it should work for most of the models...
