### ISSUE TITLE
get_variance returns zero for random effect variance for lmer model with general intercept suppressed

### ISSUE THREAD

**Issue by AgroSimi** [easystats/insight#312]
get_variance returns zero for random effect variance for lmer model with general intercept suppressed. Is this a bug or is there a statistical reason behind it? 

Working Example: 

library(lme4)
library(insight)

data("Penicillin")

m1 <- lmer(diameter ~ sample + (1|plate) , data = Penicillin) # model with general intercept for comparison 

summary(m1)

get_variance(m1)

m2 <- lmer(diameter ~ 0 + sample + (1|plate) , data = Penicillin) # suppress general intercept with "0 +"

summary(m2)

get_variance(m2) # all variances the same as above but the random variance is zero

**Comment by strengejacke** [comment]
Thanks, should be fixed.
