### ISSUE TITLE
get_predicted: make it work with log terms

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#314]
``` r
x <- lm(mpg ~ log(hp), data = mtcars)
rez <- insight::get_predicted_new(x)
#> Error in model.matrix.default(model_terms, data = data): model frame and formula mismatch in model.matrix()
```

<sup>Created on 2021-03-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I know you fixed it in the old version, but if I understand it only works with "log" if there's no new data right?

**Comment by DominiqueMakowski** [comment]
- [ ] This leads to this test failing with the new udpate:

https://github.com/easystats/insight/blob/efcdc6e006e09fb53ca8d27621e55ef801679688/tests/testthat/test-glm.R#L7-L10
https://github.com/easystats/insight/blob/efcdc6e006e09fb53ca8d27621e55ef801679688/tests/testthat/test-glm.R#L21

That needs to be uncommented once the issues is fixed

**Comment by strengejacke** [comment]
This should be fixed now...
