### ISSUE TITLE
MIresult object (mitools package) as a new supported class of models

### ISSUE THREAD

**Issue by rdmillergithub** [easystats/insight#325]
I _think_ I'm asking about adding MIresult objects as a supported model class.  But it might help if I explain.

Working with ordinal complex survey data (YRBS), I multiply imputed for missing data, then assembled the imputations into an imputationList (mitools). I used the imputationList to build an svyimputationList design object with survey:svydesign().  Now I'm using the svyimputationList to run sets of svy_vglm models with survey:with( ).   I combine the models in each set with MIcombine (mitools), resulting in an MIresult object.

So my objective is to use Insight to get information about the miresult object. (In particular, I'm interested in marginal effects, by which I mean the different effects of a predictor on different ordinal response categories).  I can see how to use it with a single svy_vglm model, but not the set of models or the combined single MIresult object.

Apologies if I'm asking in the wrong venue!

**Comment by DominiqueMakowski** [comment]
Thanks, would you have a reproducible example of the workflow that we can run to see what can be done?

**Comment by rdmillergithub** [comment]
Thanks. Yes, I will try to write one. (I'm new at this!)

**Comment by strengejacke** [comment]
_bump_
