### ISSUE TITLE
allowing `digits = "scientific"` in `format_value`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/insight#328]
In addition to consistency, this is actually something I often _do_ need.

``` r
library(insight)

format_p(0.0001, digits = "scientific")
#> [1] "p = 1.00000e-04"

format_value(0.0001, digits = "scientific")
#> Error in -digits: invalid argument to unary operator
```

<sup>Created on 2021-03-31 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by strengejacke** [comment]
and how many digits by default?

**Comment by IndrajeetPatil** [comment]
Sorry, was in a lab meeting.

Do you think there is any way to control how many digits are display when `digits = "scientific"`?

So for example, what if I want to have here `1.23e-04` as the output?

``` r
library(insight)

format_p(0.000123, digits = "scientific")
#> [1] "p = 1.23000e-04"

format_value(0.000123, digits = "scientific")
#> [1] "1.23000e-04"
```

<sup>Created on 2021-03-31 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by strengejacke** [comment]
we could add the digits as suffix, like `digits = "scientific5"`.

**Comment by IndrajeetPatil** [comment]
I like this solution 👍
