### ISSUE TITLE
CI for sigma

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#337]
I think the first step for https://github.com/easystats/performance/issues/256 is to add CIs as attributes to get_sigma

```r
confint_sigma <- function(x, conf.level = .95, ...) {
  alpha <- 1 - conf.level
  dev <- deviance(x)
  n <- nobs(x)
  lb <-  dev / qchisq(1 - alpha / 2, n)
  ub <-  dev / qchisq(alpha / 2, n)
  return(
    c(sigma.lower = sqrt(lb), sigma.upper = sqrt(ub))
  )
}
```

**Comment by DominiqueMakowski** [comment]
This has been implemented as follows:

https://github.com/easystats/insight/blob/6b5b0abcc2e394914592e715a4ebccad963b3f23/R/get_sigma.R#L158-L172

@bwiernik @strengejacke can we leave it for all models? Or only run it if say model is linear?

**Comment by bwiernik** [comment]
Bayesian models will usually contain the SDs or intervals for sigma already. This method is appropriate for Gaussian family models.
