### ISSUE TITLE
Systematic testing

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#36]
This night I was thinking about a more systematic and convenient way of testing our functions, and how it was tedious to come up with particular models, fitting them every time in tests and so on.

Then I had the idea of the [circus](https://github.com/easystats/circus) package, basically a repo that would be used only for storing all varieties and particular cases of models. We could just download this package in testing, and run the tests on all the models to see if the functions behave as expected. This could also help with the time-related issues for testing Bayesian models, as the fitting would already be done. We could quickly cover all the models, fitted once and for all.

Do you think this would work?

**Comment by strengejacke** [comment]
Having pre-compiled models would be great, indeed. But why would you put this into a package rather than in a RData file?

**Comment by DominiqueMakowski** [comment]
Stan models are quite heavy, so it seemed easier having them stored aside (clearly findable and reproducible), rather than crammed into the actual packages...

**Comment by strengejacke** [comment]
Yeah, make sense. We should think about it, though I'm not sure at the moment how to implement this properly.

**Comment by strengejacke** [comment]
I think this can be closed, right?
