### ISSUE TITLE
Prepare for `afex` V1

### ISSUE THREAD

**Issue by mattansb** [easystats/insight#362]
In the upcoming `afex` release, the underlying `aov` object will no longer be available by default.
We should update our functions not to rely on this.

**Comment by strengejacke** [comment]
where is it gone?

**Comment by mattansb** [comment]
What do you mean?

**Comment by strengejacke** [comment]
where will we find the aov object in the next update?

**Comment by mattansb** [comment]
Unless the user explicitly sets `aov_ez(..., include_aov = TRUE)`, we won't - we will only have the `"lm"` object (which will either be `lm` to `mlm` for repeated measures.

**Comment by strengejacke** [comment]
Is this resolved?

**Comment by mattansb** [comment]
Should be..
