### ISSUE TITLE
get_priors

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#39]
In the same vein, I have struggled in the past with clean priors extraction. A function to do that would be a nice and useful addition. I started drafting one for stan, but it has to be thoroughly tested and adjusted to potential edge-cases. 

```r
#' @export
get_priors <- function(model, ...) {
  UseMethod("get_priors")
}

#' @export
get_priors.stanreg <- function(model) {
  info <- rstanarm::prior_summary(model)

  info <- model$prior.info

  # Intercept
  df <- .priors_to_df(info$prior_intercept)
  df$parameter <- "(Intercept)"

  # Priors
  priors <- .priors_to_df(info$prior)
  priors$parameter <- tail(insight::find_parameters(model)$conditional, -1)
  df <- rbind(df, priors[names(priors) %in% names(df)])

  # Aux
  aux <- .priors_to_df(info$prior_aux)
  aux$parameter <- aux$aux_name
  df <- rbind(df, aux[names(aux) %in% names(df)])



  df <- df[c("parameter", names(df)[names(df) != "parameter"])]
  names(df) <- gsub("dist", "distribution", names(df))
  names(df) <- gsub("df", "DoF", names(df))
  return(df)
}

#' @keywords internal
.priors_to_df <- function(priors){
  max_length <- max(sapply(priors, length))
  for(i in names(priors)){
    if(length(priors[[i]]) < max_length){
      if(is.null(priors[[i]])){
        priors[[i]] <- NA
      }
      priors[[i]] <- rep_len(priors[[i]], max_length)
    }
  }
  if(max_length == 1){
    priors <- as.data.frame(t(sapply(priors, c)))
  }else{
    priors <- as.data.frame(sapply(priors, c))
  }

  return(priors)
}
```
```r
model <- rstanarm::stan_glm(Sepal.Width ~ Species * Petal.Length, data=iris)
get_priors(model)
```
|parameter                      |distribution |location |scale |adjusted_scale    |DoF |
|:------------------------------|:------------|:--------|:-----|:-----------------|:---|
|(Intercept)                    |normal       |0        |10    |4.35866284936698  |NA  |
|Speciesversicolor              |normal       |0        |2.5   |1.08966571234175  |NA  |
|Speciesvirginica               |normal       |0        |2.5   |1.08966571234175  |NA  |
|Petal.Length                   |normal       |0        |2.5   |0.617270040728345 |NA  |
|Speciesversicolor:Petal.Length |normal       |0        |2.5   |0.536028320794122 |NA  |
|Speciesvirginica:Petal.Length  |normal       |0        |2.5   |0.411970489526739 |NA  |
|sigma                          |exponential  |NA       |NA    |0.435866284936698 |NA  |

**Comment by DominiqueMakowski** [comment]
An initial version of that is currently implemented (and used) by parameters, [here](https://github.com/easystats/parameters/blob/master/R/TEMP_get_priors.R). It mostly needs to be adapted to brms models, and oc tested

**Comment by strengejacke** [comment]
I can implement this, but I would like to work on bayestestR first, so it can be submitted to CRAN somewhere in the near future.
