### ISSUE TITLE
get_predicted: add predict= "response" option

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#397]
Following our big API discussion on that, we know that one "missing" option is to get the prediction in the response's *type*. This mainly concerns GLMs afaik, in which for instance if the outcome is a binary 0-1 vector, the output should be 0s and 1s (depending on the highest probability of the estimated prediction). However, if the output vector is a two-level factor like `c("setosa", "virginica")`, then the predicted vector would also be of the same shape. I believe this'd be super convenient in many cases. 

I think the most straightforward logic, if `predict = "response"`, is to do everything as it `predict = "prediction"` , + at the very end, we pass the predicted data through an additional step in which we transform back to the original response's type.

My questions are:

- What is the most flexible and robust way of doing that; my initial idea would be to manually pass the data through an `ifelse(p > 0.5, 1, 0)` and then retrieve the corresponding response's level, but I know there are functions to pass it through such logit link. naturally which might better.
- Are there any other families for which `predict="response"` would be different from `predict = "prediction`, aside from binomial models?

**Comment by bwiernik** [comment]
Not that it's only 0-1 for Bernoulli models. For binomial models with larger sizes, it will be the expected number of successes.

**Comment by DominiqueMakowski** [comment]
Is there a standardized / robust way to transform predictions into the same shape?

**Comment by bwiernik** [comment]
`round(prob * size)` will work for any binomial distribution. That's really the only distribution where this is a thing.

**Comment by DominiqueMakowski** [comment]
👍 

``` r
data <- droplevels(iris[1:100, ])
x <- glm(Species ~ Sepal.Length, data = data, family = "binomial")
insight::get_predicted(x, predict = "response")
#> Predicted values:
#> 
#>   [1] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"    
#>   [6] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"    
#>  [11] "setosa"     "setosa"     "setosa"     "setosa"     "versicolor"
#>  [16] "versicolor" "setosa"     "setosa"     "versicolor" "setosa"    
#>  [21] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"    
#>  [26] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"    
#>  [31] "setosa"     "setosa"     "setosa"     "versicolor" "setosa"    
#>  [36] "setosa"     "versicolor" "setosa"     "setosa"     "setosa"    
#>  [41] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"    
#>  [46] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"    
#>  [51] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
#>  [56] "versicolor" "versicolor" "setosa"     "versicolor" "setosa"    
#>  [61] "setosa"     "versicolor" "versicolor" "versicolor" "versicolor"
#>  [66] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
#>  [71] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
#>  [76] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
#>  [81] "versicolor" "versicolor" "versicolor" "versicolor" "setosa"    
#>  [86] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
#>  [91] "versicolor" "versicolor" "versicolor" "setosa"     "versicolor"
#>  [96] "versicolor" "versicolor" "versicolor" "setosa"     "versicolor"
#> 
#> NOTE: Confidence intervals, if available, are stored as attributes and can be accessed using `as.data.frame()` on this output.
```

<sup>Created on 2021-07-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I also updated the docstrings so that it's a bit clearer 🤞
