### ISSUE TITLE
get_data.brmsfit doesn't return predictors of auxiliary components

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#398]
`get_data` doesn't return predictors that are only specified for auxiliary components, leading to other errors

```r
library(brms)

f <- brms::brmsformula(
  mpg ~ wt,
  sigma ~ cyl,
  family = exgaussian()
)
model <- brm(f, data = mtcars, refresh = 0)
```

This for instance fails:
```r
insight::get_predicted(model)
```
```
Error: The following variables can neither be found in 'data' nor in 'data2':
'cyl' 
```

Because the data doesn't include `cyl`:

```r
insight::get_data(model)
```
```
                    mpg  wt
Mazda RX4            21 2.6
Mazda RX4 Wag        21 2.9
Datsun 710           23 2.3
Hornet 4 Drive       21 3.2
Hornet Sportabout    19 3.4
Valiant              18 3.5
Duster 360           14 3.6
Merc 240D            24 3.2
Merc 230             23 3.1
Merc 280             19 3.4
```

**Comment by DominiqueMakowski** [comment]
It all stems out of the formula that is not entirely captured I think

```r
> find_predictors(model)
$conditional
[1] "wt"

> find_formula(model)
$conditional
mpg ~ wt
attr(,"nl")
[1] FALSE
attr(,"loop")
[1] TRUE

attr(,"class")
[1] "insight_formula" "list"
```

**Comment by DominiqueMakowski** [comment]
The formulas are correctly stored and can easily be retrieved, 

```r
> stats::formula(model)$pforms
$sigma
sigma ~ cyl
```

It's just that currently we only return these components:

**Comment by DominiqueMakowski** [comment]
@mattansb what do you think? Should we explicitly list and add all the potential components because they are defined and limited or is it not sustainable?

**Comment by mattansb** [comment]
I think we can (should) return a list of formulas when needed. Else we're not really supporting `brmsfit`...

**Comment by strengejacke** [comment]
We have to add those pieces to
https://github.com/easystats/insight/blob/260d964cc9c41db48e6a4756fc9cafead4aebaa5/R/find_formula.R#L1417
