### ISSUE TITLE
Using ENHANCE in DESCRIPTION?

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#40]
Since we enhance existing model classes with new functions, we could (additionally?) add the related packages to the ENHANCE field, if we like. Would you say that this makes sense?

**Comment by DominiqueMakowski** [comment]
What purpose does this field serve in general? 

Hadley [says](http://r-pkgs.had.co.nz/description.html) "*Enhances: packages listed here are “enhanced” by your package. Typically, this means you provide methods for classes defined in another package (a sort of reverse Suggests). But it’s hard to define what that means, so I don’t recommend using Enhances.*"

**Comment by strengejacke** [comment]
Ok. We don't really need to do this. But if your package provides an additional function for a class that original stems from another package, than your package enhances the other package.

This is exactly what _insight_ does (and what is in line with Hadley's description above). We have `find_formula.merMod()` etc., so we have a function for a class from another package.

**Comment by DominiqueMakowski** [comment]
If you think it's useful, go for it :)

**Comment by strengejacke** [comment]
Hm... I don't think it's really absolutely important. And I can't foresee the consequences according to internal CRAN testing etc., maybe we will mess around with unnecessary troubles. I think taking Hadley's quote into consideration, we should not be too experimental here. ;-)
