### ISSUE TITLE
Strange check error

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#404]
Anyone an idea why this error came up recently, and what it means?

> -- Error (test-rstanarm.R:106:5): (code run outside of `test_that()`) ----------
> Error: Error: 'stan_nlmer' requires a named self-starting nonlinear function.
> Backtrace:
>    x
>  1. \-rstanarm::stan_nlmer(...) test-rstanarm.R:106:4

@bwiernik @DominiqueMakowski @IndrajeetPatil @mattansb

**Comment by IndrajeetPatil** [comment]
No clue, sorry.

For what it's worth, I literally copy-pasted that example for testing from the `rstanarm` manual, so not sure why it fails only when testing but not when it's run interactively.

**Comment by IndrajeetPatil** [comment]
I'd vote for skipping it on CRAN.

**Comment by mattansb** [comment]
No idea...

**Comment by bwiernik** [comment]
That's odd because SSlogis() is a named self starting function...

Does `stats::SSlogis()` make it work?

**Comment by strengejacke** [comment]
Disabling that code chunk for now...
