### ISSUE TITLE
`find_terms` can't "look" inside parentheses 

### ISSUE THREAD

**Issue by mattansb** [easystats/insight#405]
``` r
m <- lm(mpg ~ hp * (am + cyl), data = mtcars)

insight::find_terms(m)$conditional
#> [1] "hp" "(am + cyl)"
```

<sup>Created on 2021-07-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment]
Need a regex master here (@bwiernik).

What would be the patttern:

- any of `+`, `*`, `:`, `/`
- followed by zero or more whitespace
- followed by parentheses `( <some content> )`?

In that case, the parentheses should be removed. But *not* in cases like `log(x + 1)` or `as.factor(x)`.

**Comment by strengejacke** [comment]
``` r
pattern <- "[*+:|\\-\\/](?![^(]*\\))" # was: "[\\*\\+:\\-\\|/](?![^(]*\\))"

# should return "hp", "am + cyl", to further separate "am" and "cyl"
f <- "hp * (am + cyl)"
strsplit(split = pattern, x = f, perl = TRUE)
#> [[1]]
#> [1] "hp "         " (am + cyl)"

# should return "hp", "log(x + 1)"
f <- "hp + log(x + 1)"
strsplit(split = pattern, x = f, perl = TRUE)
#> [[1]]
#> [1] "hp "         " log(x + 1)"
```

<sup>Created on 2021-07-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Related code: https://github.com/easystats/insight/blob/8dc1bf3d30f8ae0adfb8006235f98ba24a750809/R/find_terms.R#L124-L133

**Comment by mattansb** [comment]
> any of +, *, :, /

Should also be able to deal with `y ~ (a+b)`

**Comment by mattansb** [comment]
This seems easier...

``` r
.formula_to_terms <- function(ff) {
  attr(terms(ff),"term.labels")
}

.formula_to_terms(~ hp * (am + cyl))
#> [1] "hp"     "am"     "cyl"    "hp:am"  "hp:cyl"

.formula_to_terms(~ (hp * am + cyl))
#> [1] "hp"    "am"    "cyl"   "hp:am"

.formula_to_terms(~ foo(am + cyl)/hp)
#> [1] "foo(am + cyl)"    "foo(am + cyl):hp"
```

<sup>Created on 2021-07-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment]
yes, but only few models have a "terms" attribute. :-/

**Comment by mattansb** [comment]
In my example I'm using the formula, which we extract with `find_formual`:

``` r
m <- BayesFactor::lmBF(mpg ~ cyl, data = mtcars)
terms(m)
#> Error: $ operator not defined for this S4 class
```

But…

``` r
f <- insight::find_formula(m)

f$conditional |>
  terms() |>
  attr("term.labels")
#> [1] "cyl"
```

<sup>Created on 2021-07-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment]
Haha, true, we actually improved the default behaviour with `find_formula()`. That could work.

**Comment by mattansb** [comment]
> we actually improved the default behaviour

It's what we do 😎

**Comment by strengejacke** [comment]
But now we have the problem again that `find_terms()` mimics `find_parameters()`:

``` r
m <- lm(mpg ~ hp * (am + cyl), data = mtcars)
f <- insight::find_formula(m)

f$conditional |>
  terms() |>
  attr("term.labels")
#> [1] "hp"     "am"     "cyl"    "hp:am"  "hp:cyl"

insight::find_parameters(m)
#> $conditional
#> [1] "(Intercept)" "hp"          "am"          "cyl"         "hp:am"      
#> [6] "hp:cyl"
```

<sup>Created on 2021-07-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment]
Not sure, but `find_terms()` should return `"hp"` and `"(am + cyl)"`, or not?

**Comment by mattansb** [comment]
It only mimics in that example:

``` r
m <- lm(mpg ~ log(hp) * (am + factor(cyl)), data = mtcars)
f <- insight::find_formula(m)

f$conditional |>
  terms() |>
  attr("term.labels")
#> [1] "log(hp)"             "am"                  "factor(cyl)"        
#> [4] "log(hp):am"          "log(hp):factor(cyl)"

insight::find_parameters(m)
#> $conditional
#> [1] "(Intercept)"          "log(hp)"              "am"                  
#> [4] "factor(cyl)6"         "factor(cyl)8"         "log(hp):am"          
#> [7] "log(hp):factor(cyl)6" "log(hp):factor(cyl)8"

insight::find_predictors(m)
#> $conditional
#> [1] "hp"  "am"  "cyl"
```

<sup>Created on 2021-07-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

> Not sure, but find_terms() should return "hp" and "(am + cyl)", or not?

I think `find_terms()` should be an enhanced version of `terms()` - `(am + cyl)` is not a term (unless it's `I(am + cyl)`), 
instead `~ hp * (am + cyl)` is expanded to `~ hp + am + cyl + hp:am + hp:cyl`.

**Comment by bwiernik** [comment]
I agree with @mattansb

**Comment by bwiernik** [comment]
Does this current solution work if the grouping parentheses come first?

`lm(mpg ~ (vs + am) * hp, data = mtcars)`

What about with random effects?

`lme4::lmer(mpg ~ (vs + am) * hp + (1|cyl), data = mtcars)`

**Comment by mattansb** [comment]
> What about with random effects?

We split those off in the `find_formula()`, so I think we would have those separately?

**Comment by strengejacke** [comment]
That means we have a breaking change, and `find_terms()` will finally just be:

```r
f <- insight::find_formula(m)

f$conditional |>
  terms() |>
  attr("term.labels")
```

(w/o pipe, of course)

**Comment by strengejacke** [comment]
This would break code in `has_intercept()`:

``` r
m <- lm(Sepal.Length ~ 0 + Petal.Width + Species, data = iris)

# current behaviour includes "0"
insight::find_terms(m)
#> $response
#> [1] "Sepal.Length"
#> 
#> $conditional
#> [1] "0"           "Petal.Width" "Species"

f <- insight::find_formula(m)

# this does not
f$conditional |>
  terms() |>
  attr("term.labels")
#> [1] "Petal.Width" "Species"




m <- lm(Sepal.Length ~ -1 + Petal.Width + Species, data = iris)

# current behaviour includes "-1"
insight::find_terms(m)
#> $response
#> [1] "Sepal.Length"
#> 
#> $conditional
#> [1] "Petal.Width" "Species"     "-1"

f <- insight::find_formula(m)

# this does not
f$conditional |>
  terms() |>
  attr("term.labels")
#> [1] "Petal.Width" "Species"
```

<sup>Created on 2021-07-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment]
We could use this:

``` r
m1 <- lm(Sepal.Length ~ 0 + Petal.Width + Species, data = iris)
m2 <- lm(Sepal.Length ~ -1 + Petal.Width + Species, data = iris)
m3 <- lm(Sepal.Length ~ Petal.Width + Species, data = iris)
m4 <- lm(Sepal.Length ~ Petal.Width + Species + 1, data = iris)

f <- insight::find_formula(m1)
f$conditional |>
  terms() |>
  attr("intercept")
#> [1] 0


f <- insight::find_formula(m2)
f$conditional |>
  terms() |>
  attr("intercept")
#> [1] 0


f <- insight::find_formula(m3)
f$conditional |>
  terms() |>
  attr("intercept")
#> [1] 1


f <- insight::find_formula(m4)
f$conditional |>
  terms() |>
  attr("intercept")
#> [1] 1
```

<sup>Created on 2021-07-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment]
We must check how this would work for multivariate response models, though.

**Comment by strengejacke** [comment]
@IndrajeetPatil @DominiqueMakowski @mattansb Can you check in which way this would affect the packages you maintain?

**Comment by mattansb** [comment]
> We could use this:
...
f <- insight::find_formula(m1)
f$conditional |>
  terms() |>
  attr("intercept")

Looks good to me!

> Can you check in which way this would affect the packages you maintain?

This should have 0 effect on effectsize. `find_terms` is only used in one place, and this change will not affect its performance.

**Comment by IndrajeetPatil** [comment]
This change won't adversely affect any of my packages.

**Comment by strengejacke** [comment]
I have drafted a simplified extraction of terms, as we discussed here (see https://github.com/easystats/insight/commit/dc2abfa4c5d38ecb87d700f984f572dd2b4eaa25#diff-f8ab35376df194059a91ca94679fe78706e0a60387fd32128bfbe64e211a7470R76), however, is this intended for random effects?

``` r
library(insight)

set.seed(1984)
dat <- data.frame(
  y = rnorm(100 * 5, sd = 1 - .20),
  time = rep(1:10, 10 * 5),
  g1 = sort(rep(1:100, 5)),
  g2 = sort(rep(1:10, 10 * 5))
)
dat$g0 <- paste(dat$time, dat$g1)
dat$time1 <- dat$time - 8
dat$post <- 0
dat$post[dat$time >= 8] <- 1
m <- lme4::lmer(y ~ post + time1 + (post + time1 - 1 | g2), data = dat)
#> boundary (singular) fit: see ?isSingular

find_terms(m)
#> $response
#> [1] "y"
#> 
#> $conditional
#> [1] "post"  "time1"
#> 
#> $random
#> [1] "post + time1 - 1 | g2"
```

<sup>Created on 2021-07-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mattansb** [comment]
Hmmm... tough one.

An argument could be made that yes: all random slopes combined for each grouping var are a single term.

@bwiernik , what do you think?

**Comment by strengejacke** [comment]
former behaviour was:

``` r
find_terms(m)
#> $response
#> [1] "y"
#> 
#> $conditional
#> [1] "post"  "time1"
#> 
#> $random
#> [1] "post"  "time1" "g2"
```

<sup>Created on 2021-07-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mattansb** [comment]
That doesn't seem right - I feel some distinction should be made between post/time1 and g2, no?

**Comment by strengejacke** [comment]
We can access random slopes and grouping factors like this:

``` r
find_random(m)
#> $random
#> [1] "g2"
find_random_slopes(m)
#> $random
#> [1] "post"  "time1"
```

Thus, we might leave the behaviour from `find_terms()` as shown [here](https://github.com/easystats/insight/issues/405#issuecomment-887283233)... 

Any thoughts, team? @DominiqueMakowski @IndrajeetPatil

**Comment by strengejacke** [comment]
Hm, offsets are also no longer recognized with the new implementation of `find_terms()`:

``` r
set.seed(123)
N <- 100 # Samples
x <- runif(N, 0, 10) # Predictor
off <- rgamma(N, 3, 2) # Offset variable
yhat <- -1 + x * 0.5 + log(off) # Prediction on log scale
dat <- data.frame(y = NA, x, logOff = log(off))
dat$y <- rpois(N, exp(yhat)) # Poisson process
dat$y <- ifelse(rbinom(N, 1, 0.3), 0, dat$y) # Zero-inflation process

m1 <- pscl::zeroinfl(y ~ offset(logOff) + x | 1, data = dat, dist = "poisson")
insight::find_terms(m1)
#> $response
#> [1] "y"
#> 
#> $conditional
#> [1] "x"
```

<sup>Created on 2021-07-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by bwiernik** [comment]
Maybe for random effects we should return a list with each grouping factor being an element?

**Comment by DominiqueMakowski** [comment]
I don't have a strong opinion about what this set of functions should  / shouldn't return. 

In the packages I maintain I rarely access info at this low level so it should be fine

**Comment by strengejacke** [comment]
Maybe for now, we just have an extra argument that either extract the `term.labels` attribute or keeps the old behaviour.
