### ISSUE TITLE
standardize_names drops the class

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#414]
``` r
insight::standardize_names(parameters::parameters(lm(mpg~wt,data=mtcars)))
#>     Parameter Coefficient       SE   CI    CI_low   CI_high Statistic df
#> 1 (Intercept)   37.285126 1.877627 0.95 33.450500 41.119753 19.857575 30
#> 2          wt   -5.344472 0.559101 0.95 -6.486308 -4.202635 -9.559044 30
#>              p
#> 1 8.241799e-19
#> 2 1.293959e-10
```

<sup>Created on 2021-08-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

`standazrdize_names` removes the class and attributes. Is this expected behaviour for compatibility reasons?

**Comment by DominiqueMakowski** [comment]
Actually the function does not drop the attributes, just the class

**Comment by strengejacke** [comment]
Yes, expected, because names are no longer compatible with the modelparameters class.
