### ISSUE TITLE
Take random effects in gamm and gamm4 into account

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#42]
Let me give an example:

Here's the model fit:

```r
gamm4(y~s(x0)+x1+s(x2),data=dat,random=~(1|fac))
```

and here's the formula for the random part:

```r
formula(br$mer)
#> y.0 ~ X - 1 + (1 | Xr) + (1 | Xr.0) + (1 | fac)
```

I'm not sure how to extract the information properly, and what exactly is needed here. `Xr` were not specified in the random effects formula.

For gamm4, we maybe could work with `getME(br$mer, "flist")`.

**Comment by strengejacke** [comment]
For gamms, it seems like dummy random effects are included, and the question is, which is from the model-formula, and which is used internally only?

It becomes more difficult when the random effect has the same name as the internal dummy variable.

``` r
data(iris)
iris$g <- iris$Species
model <- mgcv::gamm(Petal.Length ~ Petal.Width + s(Sepal.Length), random=list(g = ~1), data = iris)
insight::find_formula(model)
#> $conditional
#> Petal.Length ~ Petal.Width + s(Sepal.Length)
names(model$lme$groups)
#> [1] "g.0" "g"


iris$Xr <- iris$Species
model <- gamm4::gamm4(Petal.Length ~ Petal.Width + s(Sepal.Length), random=~(1|Xr), data = iris)
insight::find_formula(model)
#> $conditional
#> Petal.Length ~ Petal.Width + s(Sepal.Length)
insight::find_formula(model$mer)
#> $conditional
#> y ~ X - 1
#> <environment: 0x000000001e07e598>
#> 
#> $random
#> $random[[1]]
#> ~1 | Xr.0
#> <environment: 0x000000001c35ee00>
#> 
#> $random[[2]]
#> ~1 | Xr
#> <environment: 0x000000001c370bd0>
```

<sup>Created on 2020-12-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
> For gamms, it seems like dummy random effects are included, and the question is, which is from the model-formula, and which is used internally only?

Maybe we could drop all the ones that start with `Xr`.. It's hacky but would still work in most cases?

**Comment by strengejacke** [comment]
gamm4 -> Xr, gamm -> g. But in the above example, it would not work, since the "original" random effects have the same name as the internal dummy variables, and hence the renaming. We can try to the best of luck in such cases, and else just drop "g" or "Xr".

**Comment by strengejacke** [comment]
Not sure if there are more exceptions, though.

**Comment by DominiqueMakowski** [comment]
> it would not work, since the "original" random effects have the same name as the internal dummy variables

Then we could remove  `Xr.0` if exists or `Xr` otherwise to prevent this specific edgecase of a random named Xr. I'll be on the lookout for exceptions as I continue working with GAMMs :)
