### ISSUE TITLE
`get_predicted` arguments: `type` vs. `predict`

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#431]
I am confused by the use (and interaction between) the `type` and `predict` arguments of `get_predicted` (knowing that `type` is only supported implicitly through the ellipsis). In this GLM model, the default output of `get_predicted` is equivalent to calling `predict` with `type="response"`:

``` r
library(insight)
mod <- glm(am ~ factor(cyl), family = binomial, data = mtcars)

predict(mod, type = "response") |> head(1)
# Mazda RX4 
# 0.4285714
get_predicted(mod) |> head(1)
# Mazda RX4 
# 0.4285714
get_predicted(mod, predict = "expectation") |> head(1)
# Mazda RX4 
# 0.4285714
```

## Problem 1

`get_predicted` seems to accept a `type` argument through the ellipsis, but gives incorrect results:

``` r
get_predicted(mod, type = "response")[1] 
# Mazda RX4 
# 0.6055325
predict(mod, type = "response")[1]
# Mazda RX4 
# 0.4285714
get_predicted(mod, type = "link")[1]
# Mazda RX4 
# 0.4285714
predict(mod, type = "link")[1]
#  Mazda RX4 
# -0.2876821
```

## Problem 2

`get_predicted` behaves different for different *combinations* of the `predict` and `type` arguments:

``` r
get_predicted(mod, predict = "expectation", type = "link")[1]
# Mazda RX4 
# 0.4285714

get_predicted(mod, predict = "expectation", type = "response")[1]
# Mazda RX4 
# 0.6055325

# weirdest result
get_predicted(mod, predict = "response", type = "response")[1]
# Mazda RX4 
#         0
```

## Problem 3

I think the `type` should be accessible. I understand that one of the main goals of `insight` is to make things more uniform, but in many use-cases it is important to have access to the `type` argument directly without the abstraction/convenience layer of the uniform categories created by `insight`. For example, I’m currently working on a packages with two primary function. The first relies on `insight::get_predicted` to get prediction. The second has to call `stats::predict` directly because `get_predicted` is too slow. This means that users (and programmers) must learn the names of prediction types in two “languages”: their modeling package’s and insight’s.

## Feature request

Setting `predict=NULL` overrides the `predict` argument and pushes `type` forward to the `stats::predict` calls:

``` r
get_predicted(mod, predict = NULL, type = "response") == predict(mod, type = "response")[1]
> TRUE
```

**Comment by strengejacke** [comment]
@DominiqueMakowski @bwiernik I know you had some discussions related to this issue, right?

**Comment by vincentarelbundock** [comment]
> as of a recent commit that is in the development version, whatever is in the predict argument is passed to the type argument in predict().

@bwiernik This sounds like a great solution, except I’m not convinced this is currently the case…

``` r
library(insight)
mod <- glm(am ~ mpg, family = binomial, data = mtcars)
```

Example 1:

``` r
library(insight)
mod <- glm(am ~ mpg, family = binomial, data = mtcars)

predict(mod, type = "response")[1]
# Mazda RX4 
# 0.4610951
get_predicted(mod, predict = "response")[1]
# Mazda RX4 
#         0
```

Example 2:

``` r
predict(mod, type = "terms")[1]
# [1] 0.2792038
get_predicted(mod, predict = "terms")[1]
# Error in match.arg(predict, choices = c("expectation", "link", "prediction", : 'arg' should be one of "expectation", "link", "prediction", "response", "relation"
```

**Comment by vincentarelbundock** [comment]
To give more details:

+ Any function that calls `.get_predicted_args` will feed `predict` through a `match.arg` call, and so will block "unkown" types. [See here.](https://github.com/easystats/insight/blob/master/R/get_predicted.R#L617)
+ Only known types generate values for `scale` and `ci_type`. These are required for later transformations, which may explain the zeros in my example. [See here.](https://github.com/easystats/insight/blob/master/R/get_predicted.R#L637)
+ [This line](https://github.com/easystats/insight/blob/master/R/get_predicted.R#L121) should probably disallow the `type` argument for safety reasons
+ [This code block] appears to set all predictions to zeros when trying to transform a `predict="response"`. Perhaps there should be a check for `isTRUE(args$transform)`, as there is for the preceding code block in that same function.

**Comment by vincentarelbundock** [comment]
Let me know if you want to take a closer look or if you would like me to give this a shot. I'm happy either way.

**Comment by bwiernik** [comment]
That issue there is that class 'glm' has a dedicated `predict.glm()` method.

**Comment by DominiqueMakowski** [comment]
> Setting predict=NULL overrides the predict argument and pushes type forward to the stats::predict calls:

That sounds like a good option to me, please don't hesitate to make a PR :)

**Comment by bwiernik** [comment]
No, I really think that we should discourage use of `type` entirely. 

We need to ensure that `predict` consistently yields the correct answers.

**Comment by DominiqueMakowski** [comment]
> No, I really think that we should discourage use of type entirely.

Why is that 🤔

**Comment by bwiernik** [comment]
We made our bed with the argument being `predict`. We need to lie in it. Trying to manage these two arguments being accepted simultaneously to yield expected results is going to continue to produce problems.

**Comment by bwiernik** [comment]
The solution here is to ensure that we accept any valid option in `predict` and pass it on to `type` where needed.

**Comment by DominiqueMakowski** [comment]
I think there are two independent issues; one is having the `predict` argument correctly working and eventually making it more flexible, and there is to add the option of setting predict=NULL (which would liberate `type` and `scale`) for users that know what they are doing and that want to use `get_predicted` only for its robustness and convenience (typically @vincentarelbundock's case). I'd normally agree with you and trying to push our (better 🤞) API and standards, but in this very particular case it *seems* like the implementation and maintenance cost is fairly low so it might be a convenient trick without too much potential downsides (afaik). And API-wise I find this solution elegant, setting predict to NULL is like "don't use this argument at all and just eval the others"

**Comment by strengejacke** [comment]
> The solution here is to ensure that we accept any valid option in predict and pass it on to type where needed.

I second that. Thus...

> We need to ensure that predict consistently yields the correct answers.

**Comment by strengejacke** [comment]
I think if `type` is provided (and `predict` is not), we should "backtranslate" it and set the `predict` argument to the specific value. If both are given, we should throw a warning.

**Comment by vincentarelbundock** [comment]
Thanks all for engaging in this thoughtful discussion!

> I think if `type` is provided (and `predict` is not), we should "backtranslate" it and set the `predict` argument to the specific value. If both are given, we should throw a warning.

I assume that by "backtranslate" you just mean set `predict` to the value of `type`, and don't do anything else. Right?

**Comment by DominiqueMakowski** [comment]
(just for the record, the discussion about the rationale and how the predict argument came to be can be found here https://github.com/easystats/insight/issues/310)

**Comment by vincentarelbundock** [comment]
> (just for the record, the discussion about the rationale and how the predict argument came to be can be found here #310)

Thanks. Very interesting discussion.

Would you all like me to put a proposal PR together? Of course, this doesn't imply any commitment on your part to accept it. At least this would help us orient the discussion toward something more concrete. I'm still happy to wait if you have a solution in mind.

**Comment by strengejacke** [comment]
> I assume that by "backtranslate" you just mean set predict to the value of type, and don't do anything else.

Yeah, but I think the arguments do not match 1:1? Not sure, if some models have other values than `"link"` and `"response"` (e.g. glmmTMB or pscl::hurdle/zeroinfl differ I think, and we have to "translate" those values into the ones corresponding to the related `predict`).

**Comment by strengejacke** [comment]
Is this fully addressed by https://github.com/easystats/insight/pull/434, so we can close this?

**Comment by vincentarelbundock** [comment]
Yep, I think so. Thanks for being so receptive and proactive!
