### ISSUE TITLE
`get_predicted(model, predict = "response")`

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#432]
This is a discussion thread about the argument value `predict="response"`, related to issues #431 and #310

Currently, this argument value behaves like this:

>  Finally, `"response"` only differs from the previous option for binomial models where it additionally transforms the predictions into the original response's type (for instance, to a factor)

I would argue that this violates the [principle of least astonishment.](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)

"response" is a well-established value for the `type` argument in *many* `predict` methods. For `predict.glm` and most of the ones I know, setting `type="response"` does *not* round and convert probabilities [as is done here.](https://github.com/easystats/insight/blob/master/R/get_predicted.R#L759)

Moreover, the fact that this conversion applies only to binomial model is likely to cause further astonishment, except for users who read carefully to the end of the long paragraph of documentation.

If the goal is to convert probabilities back into categories, then the more common value is: `type="class"`

What do you think? Should `"response"` be removed as one of the officially supported types?

**Comment by DominiqueMakowski** [comment]
"class" and/or "original" could be suitable alternatives I suppose

**Comment by vincentarelbundock** [comment]
One problem with "class" is: what to do if the user says `get_predicted(predict="class")` and expects the same result as `predict(type="class")`?

We want to encourage people to pass any `type` through `predict`, but this raises ambiguity.

**Comment by vincentarelbundock** [comment]
Beyond the naming convention, I also think there is [a bug in the `.get_predict_transform_response` function](https://github.com/easystats/insight/blob/master/R/get_predicted.R#L713):

``` r
library(insight)
mod <- glm(am ~ hp + factor(cyl), family = binomial, data = mtcars)
get_predicted(mod, predict = "response")
# Predicted values:
# 
#  [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
# 
# NOTE: Confidence intervals, if available, are stored as attributes and can be accessed using `as.data.frame()` on this output.
```

As far as I can tell, this is only call for binomial models, and only supports two levels in the response. Add to that the apparent bug and the naming troubles…

In my humble opinion, we should seriously consider deprecating this option altogether, until someone has a good name, a clear vision, and enough energy to give this more scope.

**Comment by bwiernik** [comment]
Maybe "classification" might be a good api?

**Comment by DominiqueMakowski** [comment]
the long term goal was to match whatever input form, e.g., factor levels when a factor is predicted, etc. 

"class"/"classification" is okay, but perhaps overemphasize the notion of classification as a goal (and has a somewhat ML-vibe to it). Maybe something along the lines of "original" - that would match the original input form, is more transparent?

**Comment by vincentarelbundock** [comment]
Understood.

I updated PR #434 with a bug fix for the all-zeros issue shown above, and the name is now `"original"`. I'm happy to change it to whatever else you all like best.

**Comment by bwiernik** [comment]
Let's go with "classification" I think. It's an appropriate allusion to ML I think. The model is predicting a probability--this step is an additional step to round that probability to a single value. "original" doesn't seem clear to me

**Comment by bwiernik** [comment]
ooh! @DominiqueMakowski a cool visualization for an `estimate_classification()` could be a dot with the 0-1 classification with a line going to the predicted probability. Could illustrate the clarity of the classifications
