### ISSUE TITLE
`get_predicted.default` should return an object of class `get_predicted`

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#435]
When there is no model-specific method defined for `get_predicted`, the default method returns a raw vector instead of a "proper" `get_predicted` object. For consistency, I think the default method should also return an object of that class, even if it is not as "rich" as those produced by other methods.

I'm not 100% sure, but the `as.data.frame.get_predicted` and other methods may need to be adjusted to handle objects with only a vector.

Let me know if you are interested in a PR.

**Comment by bwiernik** [comment]
Yes, the return value from .default should be the same as for other methods. A PR would be great

**Comment by strengejacke** [comment]
I have added a class attribute. Not sure whether more adjustments are needed (like you guessed), maybe we find some examples that could break the code for the methods like `as.data.frame()`?

**Comment by vincentarelbundock** [comment]
Cool cool, thanks!

I'll be using this a lot in the coming months and will report any issue I run into.

When I looked into this yesterday, my plan was to [use the `.get_predicted_out` function](https://github.com/easystats/insight/blob/master/R/get_predicted.R#L816) instead of just assigning a class:

Something like this:

```r
out <- .get_predicted_out(out, args = list("data" = data))
```

The benefits of this is are that (1) if there is any data it gets attached, and (2) we go through the "official" constructor, and benefit automatically if improvements are made to that constructor.

But really, it makes little difference now, and I'm not sure it ever will.

**Comment by strengejacke** [comment]
Ok, that makes sense. I'll look into it.

**Comment by strengejacke** [comment]
ok, I made the changes. Is that sufficient?

**Comment by vincentarelbundock** [comment]
Looks fantastic!
