### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#437]
@DominiqueMakowski Can you look at the rendered GitHub website from _insight_? Looks like the pkg-sticker is rendered way too large: https://easystats.github.io/insight/

@DominiqueMakowski @bwiernik @vincentarelbundock May I ask you to check the details section of the docs from `get_predicted()`? Looks like it's out of date, or I don't quite understand it (https://easystats.github.io/insight/reference/get_predicted.html):

> Note that, when predict = "response", the probabilities are rounded (so that the prediction corresponds to the most likely outcome).

1. We don't support `predict = "response"`
2. and what does "rounded" mean here?

**Comment by vincentarelbundock** [comment]
Thanks for catching this.

`predict = "response"` should be `predict = "classification"`

The rest of the text is exactly as it was, and the behavior of the function has not changed, so I think everything still applies. That said, I do agree that it is a bit confusing. Perhaps we could modify the paragraph as follows:

> When users set the `predict` argument to `"expectation"`, the predictions are returned on the response scale, which is arguably the most convenient way to understand and visualize relationships of interest. When users set the `predict` argument to `"link"`, predictions are returned on the link scale, and no transformation is applied. For instance, for a logistic regression model, the response scale corresponds to the predicted probabilities, whereas the link-scale makes predictions of log-odds (probabilities on the logit scale). Note that in binomial models, the `get_predicted` function will first calculate predictions as if the user had selected `predict="expectation"`. Then, it will round the responses in order to return the most likely outcome.

**Comment by strengejacke** [comment]
That sounds good, I revised the docs. However, I'm still not sure about `predict="expectation"` and rounded probabilities. Shouldn't `predict="classification"` "round" the probabilities to the most likely response value?

**Comment by strengejacke** [comment]
``` r
library(insight)
data(iris)
data <- droplevels(iris[1:100, ])
x <- glm(Species ~ Sepal.Length, data = data, family = "binomial")

pred <- get_predicted(x, predict = "expectation")
head(as.data.frame(pred))
#>    Predicted         SE      CI_low    CI_high
#> 1 0.16579367 0.05943589 0.078854431 0.31573138
#> 2 0.06637193 0.03625646 0.022083989 0.18286787
#> 3 0.02479825 0.01843411 0.005675609 0.10175666
#> 4 0.01498061 0.01261461 0.002839122 0.07513285
#> 5 0.10623680 0.04779474 0.042437982 0.24173444
#> 6 0.48159935 0.07901420 0.333158095 0.63336131
pred <- get_predicted(x, predict = "classification")
head(as.data.frame(pred))
#>   Predicted CI_low    CI_high
#> 1    setosa setosa versicolor
#> 2    setosa setosa versicolor
#> 3    setosa setosa     setosa
#> 4    setosa setosa     setosa
#> 5    setosa setosa versicolor
#> 6    setosa setosa versicolor
```

<sup>Created on 2021-09-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
Does this help?

> Then, it will round outcomes expressed on the response/expectation scale (typically probabilities) in order to return the most likely outcome value (typically a discrete value).

**Comment by vincentarelbundock** [comment]
Sounds like you're pointing to the same terminological ambiguity that made its way into the previous code, where "response" referred to discrete values like "setosa". The point of moving to `"classification"` is to avoid this ambiguity: not use "response"

**Comment by strengejacke** [comment]
Yes, my main point here is that `"expectation"` doesn't round anything, but `"classification"` does. I think I just need to replace expectation by classification here.

**Comment by vincentarelbundock** [comment]
Oh wow, sorry I misunderstood! There's something missing in the last sentence:

> Note that when users select `predict="classification"` in binomial models, the get_predicted function will first calculate predictions as if the user had selected predict="expectation". Then, it will round the responses in order to return the most likely outcome.

**Comment by strengejacke** [comment]
Yes, that looks good! The last sentence didn't make sense before.

**Comment by vincentarelbundock** [comment]
That's what you get from me when I just woke up ;)
