### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#44]
Is there a reason why we have two readme files? And I just saw that `citation("insight")` returns only my name. Is that OK for you? I thought you could probably add your name as well...

**Comment by DominiqueMakowski** [comment]
the "true" README (.md) is generated programmatically by the .rmd README. Also, pkgdown uses the .rmd to generate the welcome page on the docs. I found it actually quite easier to be able to generate the README from markdown, especially when there are examples and outputs and such (not really the case here for now). 

As for citation, I'd include myself with pleasure, but I wasn't sure about your perspective on this. Maybe you could add me the way you like then.

What do you think of the readme?

**Comment by strengejacke** [comment]
I think the readme is ok now! I guess we'll only do minor changes, but this will evolve as the package develops further. Are you ok with changing from list to paragraph (supported models)?

**Comment by DominiqueMakowski** [comment]
yes!

**Comment by strengejacke** [comment]
> the "true" README (.md) is generated programmatically by the .rmd README.
How does this happen?
