### ISSUE TITLE
get_predicted(): formally support 'disp' and 'zi'

### ISSUE THREAD

**Issue by bwiernik** [easystats/insight#454]
We should formally support `predit = 'disp'` and `predict = 'zi'` and related predictions. This is fairly easy for *glmmTMB* and is possible, but more difficult for *brms*. 

Does *brms* provide facilities to extract the posterior predictive distribution for `sigma` or `zi` responses? @paul-buerkner @ASKurz

**Comment by DominiqueMakowski** [comment]
that sounds good

**Comment by bwiernik** [comment]
For *brms*, we could create disp/zi prediction functionality using `hypothesis()` https://paul-buerkner.github.io/brms/articles/brms_distreg.html

**Comment by strengejacke** [comment]
should be resolved in #501 to #503
