### ISSUE TITLE
Vignettes

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#46]
I just discovered that adding new models needs indeed a bit more detailed description, so I would rather like to include vignettes in milestone 0.2

**Comment by strengejacke** [comment]
I have created a vignette-branch, where we can work on vignette related stuff.

**Comment by strengejacke** [comment]
@DominiqueMakowski @pdwaggoner 
I have drafted a vignette (https://github.com/easystats/insight/blob/master/vignettes/function_design.Rmd), maybe you guys can take a quick look at it?

I just wanted to give some examples that make it more clear why we have different functions, or what these functions actually address.

At the bottom, I still need to add a sentence saying something like "we need different functions because it sometimes we need log() and sometimes the clean term" or so...

**Comment by pdwaggoner** [comment]
I just gave this a look and its really great! Very helpful deeper dive into insight and explains the intuition behind the architecture. This is really great. I cleaned up a couple minor grammatical things. 

I have some thoughts on updating the JOSS paper in light of this vignette. I will respond back over there to keep things as organized as possible.

**Comment by strengejacke** [comment]
I think now that we revised the docs/website after JOSS publication, we can close this issue, unless we have the need for more, specific vignettes.
