### ISSUE TITLE
remove `data_reshape.R`?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/insight#465]
I think these functions are the same as `{datawizard}` functions?

https://github.com/easystats/insight/blob/f47d7ec8233ca1284d1ed220ce84b56740844286/R/data_reshape.R

**Comment by strengejacke** [comment]
we need one for internal use, but we can indeed remove those, once we have checked their usage in other packages.

**Comment by IndrajeetPatil** [comment]
We can just re-export the following functions to be backward compatible:

```
export(reshape_ci)
export(reshape_longer)
export(reshape_wider)
export(to_numeric)
```

**Comment by strengejacke** [comment]
But _insight_ doesn't import _datawizard_

**Comment by bwiernik** [comment]
I don't think insight needs this function. It must be an oversight. iIRC, Dom initially put them here before immediately making datawizard

**Comment by IndrajeetPatil** [comment]
Ah, yes! Forgot about that.

Fingers crossed that either we or someone out there is not using them anywhere in their packages! 🤞

**Comment by strengejacke** [comment]
I think the `data_*` / `reshape_*` functions from _insight_ are only used by our own packages. If we already made the transition to _datawizard_ in our other packages, I'd say we can safely remove them here.

Things we have to consider:

- [ ] `reshape_longer()` is used [here](https://github.com/easystats/insight/blob/28a22bf4bf01952e36a0bd93bfb56dad8e9ad115/R/compute_variances.R#L897), need to replace by `stats::reshape()` or an internal version of `reshape_longer()`
- [ ] we use `reshape_ci()` in _bayestestR_ and _parameters_, I think, and should switch to using _datawizard_ here as well.

**Comment by strengejacke** [comment]
ok, let's see what happens...

**Comment by IndrajeetPatil** [comment]
This is creating problems for see package. See the latest builds in master branch.

**Comment by strengejacke** [comment]
Looks rather like a modelbased issue. @DominiqueMakowski can you switch from insight to datawizard before submission?
