### ISSUE TITLE
`get_predicted.brmsfit` draws format

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#468]
I tried to find a discussion about the data structure in which `brms` results are returned, but a quick search didn’t turn up much.

Right now, if we call `get_predicted()` and then `as.data.frame` on a `brmsfit` object, we get a data frame with a number of rows equal to the number of rows in the original dataset. Then we have columns: `Predicted`, `SE`, `CI_low`, `CI_high`, and then a series of columns called `iter_N`, where `N` is a series of numbers from 1 to the number of chains times the number of iterations:

``` r
library(brms)
library(insight)

mod <- brm(hp ~ mpg, data = mtcars)

res <- as.data.frame(get_predicted(mod))

res[1:5, 1:6]
#   Predicted       SE   CI_low  CI_high   iter_1   iter_2
# 1  138.2732 8.201021 122.3942 154.3034 135.1863 145.4200
# 2  138.2732 8.201021 122.3942 154.3034 135.1863 145.4200
# 3  122.4664 8.869781 105.2759 139.4562 117.8535 130.5178
# 4  134.7606 8.291107 118.7836 150.9426 131.3345 142.1084
# 5  158.4708 8.388775 142.6280 175.3145 157.3337 164.4618

dim()
# 32 4004
```

I don’t have a terribly strong opinion on this, but it feels like this may not be the most convenient or “standard” format. For example, say you want to draw a density plot of predicted values. You would have subset the `iter_N` columns, then `pivot_longer`, and then feed the result to `ggplot2` or `hist`.

The `posterior` package (by the Stan team) defines 5 “standard” format in which posterior draws are often returned, and offers handy tools to convert/manipulate/subset them:

<https://mc-stan.org/posterior/articles/posterior.html#draws-formats-1>

Our current format is not like any of those. My question:

Do you think it would make sense to return draws as an attribute of the `get_predicted` data.frame, in one of the formats supported by other packages in the Bayesian `R` ecosystem? 

This would allow our users to plug-and-play our results in all of their normal plotting/analysis workflow and tools.

**Comment by bwiernik** [comment]
Do you have a question? You can use `reshape_draws()` to pivot to a iterations by row format

**Comment by vincentarelbundock** [comment]
Yes, the question in my post was sandwiched between the words "My question is:" and the question mark.

But I was not aware of the `bayestestR::reshape_iterations` function (`reshape_draws` appears to be deprecated), so thanks for that. Very useful!

Part of me still feels like I shouldn't onboard two dependencies (`bayestestR` and `datawizard`) just to get the draws in a "standard" format, but I understand that `easystats` has developed its own philosophy and way of dealing with these kinds of issues. Given all that, I'll close this issue.

Thanks.

**Comment by bwiernik** [comment]
Oh sorry. I'm on the GitHub mobile app and your post was shown cut off after the first few sentences. ![image](https://user-images.githubusercontent.com/4773225/141663769-d6e08dc2-05ed-4099-9b21-4d9515e3b72d.jpeg)

**Comment by vincentarelbundock** [comment]
I've been telling everyone: cell phones are going to ruin the world and all social relations! ;)

**Comment by bwiernik** [comment]
If you just want all of the draws for model parameters, as.data.frame(brms_model)

**Comment by strengejacke** [comment]
Maybe we could have some helper functions, or additional arguments, to preserve compatibility to other packages. That sounds like making sense?

**Comment by bwiernik** [comment]
Honestly, I wonder whether a better approach would be to move to a *posterior* backend for our functions. It's becoming the standard for Stan posterior manipulation and is super robust.

**Comment by vincentarelbundock** [comment]
> Honestly, I wonder whether a better approach would be to move to a *posterior* backend for our functions. It's becoming the standard for Stan posterior manipulation and is super robust. 

I would be willing to invest a little bit of time into this if you decide to go that route. (Maybe not enough to do everything, but certainly help out.)

Also not that this would not require loading `posterior` itself, since all formats use standard arrays, matrices, and data frames.

**Comment by strengejacke** [comment]
> Honestly, I wonder whether a better approach would be to move to a _posterior_ backend for our functions. It's becoming the standard for Stan posterior manipulation and is super robust.

What do you have exactly in mind?

**Comment by strengejacke** [comment]
FYI, the raw draws of the predictions are indeed as attribute from `get_predicted()`, and using `as.data.frame(predictions, keep_iterations = FALSE)` returns the "regular" data frame.

But, how would we modify our API to be compatible with the _posterior_ package? Having an `as_posterior()` helper? And in which places do we need that conversion?

**Comment by vincentarelbundock** [comment]
> FYI, the raw draws of the predictions are indeed as attribute from `get_predicted()`, and using `as.data.frame(predictions, keep_iterations = FALSE)` returns the "regular" data frame.
> 
> But, how would we modify our API to be compatible with the _posterior_ package? Having an `as_posterior()` helper? And in which places do we need that conversion?

Yes, currently the draws are stored in the `iterations` attribute as a data.frame of size NxD, where N is the number of observations and D is the number of draws. Ideally, I think that the `iterations` attribute should be in one of the formats described at the `posterior` link above, rather than a "custom" data frame style. This doesn't matter much in the simple cases, but it might for models with categorical outcomes, for example, where a more standard approach would help.

That said, this is not a big deal at all. I don't think we need the conversion inside `insight`.

Converting to the desired format is a 2-liner, so I don't think it's worth investing in a helper functions (limiting the number of helpers means more maintainability for `insight`).

I'll close this now because I'm not sure this is worth investing much in unless there is new demand or a compelling use case emerges.

**Comment by strengejacke** [comment]
ok. I plan to submit an update of _insight_ the next days, I think remaining `get_predicted()` issues can then be addressed in the beginning of 2022.

**Comment by bwiernik** [comment]
The general structure of posterior data frames IIRC is like our long format. The print method shows the parameters as median +- mad
