### ISSUE TITLE
`get_predicted.brmsfit`: model with `factor()` in formula

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#469]
`get_predicted` raises an error when the formula used in `brms::brm` includes a `factor()` transformation:

``` r
library(brms)
library(insight)

mod <- brm(am ~ mpg + factor(cyl), data = mtcars, family = bernoulli())

get_predicted(mod)
# Error: Variable 'cyl' was originally numeric but is not in 'newdata'.
```

**Comment by strengejacke** [comment]
Should we consider this as an _insight_ issue? In particular with reference grids, it makes sense to treat values as discrete levels when a variable entered a model as factor, and not treat it as numeric? Here are some example of what works and what not:

``` r
library(brms)
library(insight)

data(mtcars)
mtcars$cyl <- as.factor(mtcars$cyl)
m1 <- brm(am ~ mpg + cyl, data = mtcars, family = bernoulli())

data(mtcars)
mtcars$cyl <- as.factor(mtcars$cyl)
levels(mtcars$cyl) <- c("1", "2", "3")
m2 <- brm(am ~ mpg + cyl, data = mtcars, family = bernoulli())

data(mtcars)
m3 <- brm(am ~ mpg + cyl, data = mtcars, family = bernoulli())

data(mtcars)
m4 <- brm(am ~ mpg + factor(cyl), data = mtcars, family = bernoulli())

data(mtcars)

rstantools::posterior_epred(m1, newdata = get_data(m1), ndraws = 10, draws = 10) |> colMeans()
#>  [1] 0.49896535 0.49896535 0.44009455 0.53509890 0.37124695 0.26505459
#>  [7] 0.09386085 0.58757432 0.44009455 0.33618546 0.24928824 0.18903573
#> [13] 0.25741933 0.12449280 0.04016422 0.04016422 0.10595382 0.84916213
#> [19] 0.81799036 0.86760933 0.33002432 0.13776607 0.12449280 0.07156991
#> [25] 0.40573407 0.74096303 0.68772138 0.81799036 0.15286504 0.37696034
#> [31] 0.11657366 0.32316476
rstantools::posterior_epred(m1, newdata = mtcars, ndraws = 10, draws = 10) |> colMeans()
#>  [1] 0.52503596 0.52503596 0.62180625 0.56017775 0.37963805 0.27162873
#>  [7] 0.11642388 0.75028693 0.62180625 0.35969268 0.25230365 0.19863993
#> [13] 0.25812711 0.14351330 0.06772133 0.06772133 0.12722634 0.96254221
#> [19] 0.95366774 0.96595604 0.51565051 0.15500124 0.14351330 0.09614269
#> [25] 0.42606686 0.91046431 0.85908231 0.95366774 0.16793649 0.40545605
#> [31] 0.13659400 0.50771733

rstantools::posterior_epred(m2, newdata = get_data(m2), ndraws = 10, draws = 10) |> colMeans()
#>  [1] 0.58630470 0.58630470 0.56120725 0.62139624 0.33509110 0.30323388
#>  [7] 0.08047098 0.71311394 0.56120725 0.40698037 0.27835480 0.16380042
#> [13] 0.22213433 0.10837745 0.02795354 0.02795354 0.09168316 0.96366119
#> [19] 0.94696974 0.96994437 0.42836903 0.12004105 0.10837745 0.05899482
#> [25] 0.37734718 0.87886210 0.82126513 0.94696974 0.13309242 0.45810410
#> [31] 0.10131121 0.41878613
rstantools::posterior_epred(m2, newdata = mtcars, ndraws = 10, draws = 10) |> colMeans()
#> Error: New factor levels are not allowed.
#> Levels allowed: '1', '2', '3'
#> Levels found: '4', '6', '8'

rstantools::posterior_epred(m3, newdata = get_data(m3), ndraws = 10, draws = 10) |> colMeans()
#>  [1] 0.50480998 0.50480998 0.54038698 0.54629126 0.41070345 0.24292773
#>  [7] 0.11124621 0.69533831 0.54038698 0.32883174 0.22306488 0.21818068
#> [13] 0.28461262 0.14935450 0.03328594 0.03328594 0.12687923 0.97440674
#> [19] 0.95694480 0.98137885 0.41693117 0.16452087 0.14935450 0.08010932
#> [25] 0.46004967 0.88344579 0.81770852 0.95694480 0.18101822 0.37424279
#> [31] 0.13995562 0.40814393
rstantools::posterior_epred(m3, newdata = mtcars, ndraws = 10, draws = 10) |> colMeans()
#>  [1] 0.56410679 0.56410679 0.70151029 0.60662752 0.36623762 0.27867117
#>  [7] 0.08494889 0.83489219 0.70151029 0.37016482 0.25842998 0.17070581
#> [13] 0.23685178 0.11204988 0.03835559 0.03835559 0.09561650 0.97406239
#> [19] 0.96712560 0.97732376 0.57489432 0.12390238 0.11204988 0.06535976
#> [25] 0.41357472 0.93899806 0.90926982 0.96712560 0.13750072 0.42054027
#> [31] 0.10501556 0.56538226

rstantools::posterior_epred(m4, newdata = get_data(m4), ndraws = 10, draws = 10) |> colMeans()
#> Error: Variable 'cyl' was originally numeric but is not in 'newdata'.
rstantools::posterior_epred(m4, newdata = mtcars, ndraws = 10, draws = 10) |> colMeans()
#>  [1] 0.49281257 0.49281257 0.52850982 0.52768852 0.42264724 0.22136765
#>  [7] 0.08656068 0.70999231 0.52850982 0.32246088 0.19848764 0.20753197
#> [13] 0.29197796 0.12528409 0.02350979 0.02350979 0.10174734 0.97301340
#> [19] 0.95406476 0.98130008 0.40110251 0.14222823 0.12528409 0.05921390
#> [25] 0.46259458 0.88697874 0.83056568 0.95406476 0.16152282 0.37144589
#> [31] 0.11520356 0.39276098
```

<sup>Created on 2021-11-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
Thanks for this.

Of those, the only one that might *possibly* be an `insight` issue is the last, where I would expect `newdata=get_data(m4)` to behave exactly as `newdata=mtcars`. t

Frankly, I'm not sure I understand why they do not.

**Comment by strengejacke** [comment]
> Frankly, I'm not sure I understand why they do not.

`get_data()` returns the data that was used to fit the model - in this case, `cyl` was a factor in that model.

**Comment by strengejacke** [comment]
But yes, I just saw, the behaviour in this particular case contradicts the description of the function from `?get_data`.

**Comment by strengejacke** [comment]
@bwiernik @mattansb @DominiqueMakowski @IndrajeetPatil what would you say should be the default behaviour? Should we also convert `factor()` and `as.factor()` back to their original variables?

**Comment by mattansb** [comment]
I tend to agree... But we should try to mitigate any unwanted effects down the line in our functions as much as we can.

**Comment by DominiqueMakowski** [comment]
I guess it's consistent yeah

**Comment by strengejacke** [comment]
> I tend to agree... But we should try to mitigate any unwanted effects down the line in our functions as much as we can.

I think a possibly critical part could be the `visualization_marix`, but we must check.

**Comment by DominiqueMakowski** [comment]
maybe we should think of making visualization_matrix a common insight-level ground (and hence more robust and flexible), it could be possibly useful for marginaleffects (and ggeffects?)

**Comment by vincentarelbundock** [comment]
> maybe we should think of making visualization_matrix a common insight-level ground (and hence more robust and flexible), it could be possibly useful for marginaleffects (and ggeffects?)

That's interesting. But wouldn't it fit better in `datawizard` (or elsewhere)? This seems like a "data manipulation/construction" function, rather than something meant to extract info from models (which is `insights` mission, maybe).

**Comment by DominiqueMakowski** [comment]
> But wouldn't it fit better in datawizard 

good point

**Comment by strengejacke** [comment]
I'm not yet sure how to best handle this. The model frame from brms objects returns a numeric variable, but this can't be used to generate the reference grid for `predict()`, because a factor is required, `get_data()` returns a factor instead of numeric, so it works. But the original variable in the data that was used to fit the model was numeric... ?

``` r
library(brms)

mod <- brm(am ~ mpg + factor(cyl), data = mtcars, family = bernoulli())
mm <- glm(am ~ mpg + cyl, data = mtcars, family = binomial())

nd <- ggeffects::new_data(mm, "mpg")
nd
#>    mpg    cyl
#> 1   10 6.1875
#> 2   12 6.1875
#> 3   14 6.1875
#> 4   16 6.1875
#> 5   18 6.1875
#> 6   20 6.1875
#> 7   22 6.1875
#> 8   24 6.1875
#> 9   26 6.1875
#> 10  28 6.1875
#> 11  30 6.1875
#> 12  32 6.1875
#> 13  34 6.1875

predict(mod, newdata = nd)
#> Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]): contrasts can be applied only to factors with 2 or more levels


nd <- ggeffects::new_data(mod, "mpg")
nd
#>    mpg cyl
#> 1   10   4
#> 2   12   4
#> 3   14   4
#> 4   16   4
#> 5   18   4
#> 6   20   4
#> 7   22   4
#> 8   24   4
#> 9   26   4
#> 10  28   4
#> 11  30   4
#> 12  32   4
#> 13  34   4

predict(mod, newdata = nd)
#> Error: Variable 'cyl' was originally numeric but is not in 'newdata'.
```

<sup>Created on 2021-11-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
since this works with all other models, I _thnik_ this could also be considered as an issue in brms, not insight.

**Comment by vincentarelbundock** [comment]
> since this works with all other models, I *thnik* this could also be
> considered as an issue in brms, not insight.

I’m not 100% convinced.

Thought experiment: what kind of minimal working example – excluding all
`insight` or `ggeffects` calls – would we supply when reporting a bug to
`brms`? If we can’t show them some expectation-breaking behavior with
just their functions, then the problem is probably on our end…

For instance, this feels pretty “normal” to me:

``` r
library(brms)
mod <- brm(am ~ mpg + factor(cyl), data = mtcars, family = bernoulli())

nd <- data.frame(mpg = 20, cyl = c(4, 6, 8))

predict(mod) |> head()
```

    ##      Estimate Est.Error Q2.5 Q97.5
    ## [1,]  0.53000 0.4991616    0     1
    ## [2,]  0.53950 0.4984996    0     1
    ## [3,]  0.54100 0.4983785    0     1
    ## [4,]  0.58800 0.4922566    0     1
    ## [5,]  0.35400 0.4782689    0     1
    ## [6,]  0.27875 0.4484403    0     1

``` r
predict(mod, newdata = mtcars) |> head()
```

    ##      Estimate Est.Error Q2.5 Q97.5
    ## [1,]  0.55300 0.4972452    0     1
    ## [2,]  0.54175 0.4983162    0     1
    ## [3,]  0.53350 0.4989389    0     1
    ## [4,]  0.59200 0.4915246    0     1
    ## [5,]  0.35175 0.4775761    0     1
    ## [6,]  0.27525 0.4466960    0     1

``` r
predict(mod, newdata = nd) |> head()
```

    ##      Estimate Est.Error Q2.5 Q97.5
    ## [1,]  0.31125 0.4630627    0     1
    ## [2,]  0.44250 0.4967448    0     1
    ## [3,]  0.46900 0.4991005    0     1

In contrast, with `ggeffects` we get an error specifically because it
returns `cyl` as a factor instead of a numeric as in the original data:

``` r
nd <- ggeffects::new_data(mod, "mpg")

class(nd$cyl)
```

    ## [1] "factor"

``` r
predict(mod, newdata = nd)
```

    ## Error: Variable 'cyl' was originally numeric but is not in 'newdata'.

**Comment by strengejacke** [comment]
I tried to find out how other packages, in particular _emmeans_, handle this, and it seems that if you pass `data = mtcars` (with numeric `cyl`) to `ref_grid()`, it detects it as a factor and produces a "correct" reference grid, treating `cyl` as a factor.

Thus, this would mean that

1. `get_data()` should return numerics instead of factors for "on-the-fly" conversions of variables.
2. `get_data()` could have an attribute that indicates which variables are numeric in the data, but were used as factors in the model (by on-the-fly conversion)
3. `visualization_matrix()` needs to check numeric variables if these were treated as factors, and then correctly generate the reference grid.

We probably should try to address this before submitting _modelbased_, or what would you say, @DominiqueMakowski @bwiernik ?

**Comment by bwiernik** [comment]
Does *emmeans* do it by using model.matrix() or model.frame() with the model formula and data?

**Comment by bwiernik** [comment]
Those 3 steps look good to me

**Comment by strengejacke** [comment]
> Does _emmeans_ do it by using model.matrix() or model.frame() with the model formula and data?

I think in the case of _brms_

```r
recover_data.brmsfit <- function (object, data, ...)  {
  bt = brms::parse_bf(formula(object))
  if (class(bt) != "brmsterms") 
    stop("This model is currently not supported.")
  mt = attr(model.frame(bt$dpars$mu$fe, data = object$data), "terms")
  recover_data.call(NULL, mt, "na.omit", data = object$data, ...)
}
```

**Comment by strengejacke** [comment]
we could also work with an argument, like `preserve_factors`, which is `TRUE` by default (to keep current behaviour and not break things), and can be `FALSE` when used in `get_predicted()` for brms or so.

**Comment by vincentarelbundock** [comment]
> we could also work with an argument, like `preserve_factors`, which is `TRUE` by default (to keep current behaviour and not break things), and can be `FALSE` when used in `get_predicted()` for brms or so.

I don't have a strong view on this, and would be perfectly happy with any solution you settle on (or no solution at all, for that matter). But just to play devil's advocate:

1. This seems like a small case to justify the addition of a new argument. Minimizing the number of arguments should be a priority.
2. What use-cases do we have where we need the transformed data rather than the original?

**Comment by strengejacke** [comment]
> No solution at all

That's too late, `get_data()` now returns numerics instead of factors (https://github.com/easystats/insight/commit/25651723883802c9717588e2d2db77af8b76a01f).

**Comment by vincentarelbundock** [comment]
> > No solution at all
> 
> That's too late, `get_data()` now returns numerics instead of factors ([2565172](https://github.com/easystats/insight/commit/25651723883802c9717588e2d2db77af8b76a01f)).

haha! Thanks for dealing with this!

**Comment by bwiernik** [comment]
The main case we should check is how this might impact plotting--eg, if we are making a plot in modelbased based on whether the predictor is a factor or not, we should follow how it was modeled

**Comment by strengejacke** [comment]
Yes, I think it most likely affects `visualization_matrix()`.

**Comment by strengejacke** [comment]
Looks like [this commit](https://github.com/strengejacke/ggeffects/commit/3300bbe3a7984756b852546f2756c40ee4e124e8#diff-c0333fc6e976f9d90fa45aa0470902b03632316bed5a83cb7e12773608590d73R3-R8) is the simple fix for _ggeffects_, which is also backwards compatible.

**Comment by strengejacke** [comment]
Ok, was too easy to be true...

**Comment by DominiqueMakowski** [comment]
Is there a way to get a vector, for each variable in the formula, of the potential transformation? If not, maybe we should add that in the attributes of find_formula or find_terms ? That would make it easy to insert the [fix here](  # Deal with factor transformations)

**Comment by strengejacke** [comment]
Do you mean, if `get_data()` indicates which variables were factors? That's implemented, there is an attribute `factors` that has all variable names that were converted to factors on the fly, and each variable that is a factor has a `factor` attribute as well:

``` r
mm <- glm(am ~ mpg + factor(cyl), data = mtcars, family = binomial())
d <- insight::get_data(mm)

attributes(d)$factors
#> [1] "cyl"

isTRUE(attributes(d$cyl)$factor)
#> [1] TRUE

sapply(d, attributes)
#> $am
#> NULL
#> 
#> $mpg
#> NULL
#> 
#> $cyl
#> $cyl$factor
#> [1] TRUE
```

<sup>Created on 2021-12-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DominiqueMakowski** [comment]
``` r
  model <- suppressWarnings(rstanarm::stan_glm(mpg ~ wt * as.factor(gear), data = mtcars, refresh = 0, iter = 200, chains = 2))
  
  attributes(insight::get_data(model))$factors
#> NULL
```

<sup>Created on 2021-12-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Curiously, doesn't seem to work for rstanarm models 🤔

**Comment by strengejacke** [comment]
should be fixed now.
