### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#47]
Following model-objects could be tested as well, but I'm not sure when we should add those tests (maybe later, 0.2 or so?)

- [x] aovlist (see #51)
- [x] logistf
- [x] lm_robust
- [x] glmRob
- [x] lmRob
- [x] lrm

**Comment by DominiqueMakowski** [comment]
Should we add these model types to circus so we can include them in systematic testing?

**Comment by strengejacke** [comment]
Yes, although these model classes are less common, but I think it's good to have these for testing. Maybe I can add them to circus while working on this issue.

**Comment by DominiqueMakowski** [comment]
sounds good let me know if you need any hand :)

**Comment by strengejacke** [comment]
will commit later...

**Comment by strengejacke** [comment]
During testing, I indeed fixed some issues for the above mentioned models, and I also added support for _gamlss_, _mixed_ (pkg **afex**) and *iv_robust* (pkg **estimatr**).
