### ISSUE TITLE
`get_predicted.brmsfit`: explicit `predict` keyword for `posterior_predict`

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#470]
Currently, the `predict` argument of `get_predicted.brmsfit` accepts two values explicitly ([code here](https://github.com/easystats/insight/blob/master/R/get_predicted.R#L799)):

1. "link" retrieves predictions using `rstantools::posterior_linpred`
2. "expectation" retrieves predictions using `rstantools::posterior_epred`
3. Everything else uses `rstantools::posterior_predict`

My understanding is that in random effects, the difference between 2 and 3 is that [the latter does not take into account the residual observation-level variance.](https://github.com/easystats/insight/blob/master/R/get_predicted.R#L819)

A) Should we have an explicit value of the `predict` argument to allow 3? 
B) If so, what should it be called?
C) If not, how can we let users know that they can get this?

I suspect that @bwiernik (and others) will have useful insights into this.

**Comment by bwiernik** [comment]
The distinction between these functions is that linpred gives posterior for the link for the mean function values. epred takes these values and back-transforms them using the inverse link function. posterior_prediction incorporates all of the parts of the model to get actual predicted response values for individuals

**Comment by vincentarelbundock** [comment]
Right, my explanation at the link switched 2 and 3 around. Sorry.

Do you think we should have a distinct `predict` value to "incorporate all of the parts of the model to get actual predicted response values for individuals". I suppose that's "prediction"? 

If so, then the only thing is that relying on `else` would also catch "classification" and everything else, which is slightly dangerous but not a big deal.

**Comment by bwiernik** [comment]
To clarify a few points, in easystats, we identify 4 types of predicted values:

1. Link - linear predictor for the model
1. Expectation - linear predictor back transformed by the inverse link
1. Prediction - individual predicted response values 
1. Classification - for Bernoulli models, rounding Prediction to most likely outcome

**Comment by strengejacke** [comment]
> My understanding is that in random effects, the difference between 2 and 3 is that the latter does not take into account the residual observation-level variance.

That should be possible by using the `include_random` argument, which either sets `re.form` to `NA` or `NULL`.
