### ISSUE TITLE
introduce `standardize_column_order()`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/insight#474]
In `{parameters}`, we are [repeating ourselves a ton](https://github.com/easystats/parameters/search?q=col_order) while reordering columns. 

We can avoid this by introducing a function like `standardize_column_order()`, which would standardize column ordering.

The function signature would be similar to `standardize_names()`:

```r
standardize_column_order(
  data,
  style = c("easystats", "broom"),
  ...
)
```

This way, if someone has adopted `{broom}` naming conventions, they would still be able to standardize column order for their dataframe.

If you think this is a good idea, I can work on it.

**Comment by bwiernik** [comment]
Great idea!

Also this: `col_order[col_order %in% names(out)`

Can be shortened to `intersect(col_order, names(out))`

**Comment by DominiqueMakowski** [comment]
Good idea!

I'd name it "standardize_..." If it's to be an internal function, but of we export it, then maybe why not make it an option of an existing function in datawizard, like "data_reorder(data, style='broom')"
