### ISSUE TITLE
`get_data.selection` does not return the original data

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#477]
The `get_data` methods for `selection` models returns a dataset with weird prefixes instead of the original data:

``` r
library("insight")
library("sampleSelection")
data(Mroz87, package = "sampleSelection")
Mroz87$kids  <- (Mroz87$kids5 + Mroz87$kids618 > 0)

mod1 <- heckit(lfp ~ age + I( age^2 ) + faminc + kids + educ,
               wage ~ exper + I( exper^2 ) + educ + city,
               data = Mroz87)

mod2 <- selection(lfp ~ age + I( age^2 ) + faminc + kids + educ,
                  wage ~ exper + I( exper^2 ) + educ + city,
                  data = Mroz87)

get_data(mod1) |> head(2)
```

    ##       YO imrData$IMR1 XO.(Intercept) XO.exper XO.exper.1 XO.educ XO.city
    ## 1 3.3540    0.7380211              1       14        196      12       0
    ## 2 1.3889    0.7658325              1        5         25      12       1

``` r
get_data(mod2) |> head(2)
```

    ##       YO imrData$IMR1 XO.(Intercept) XO.exper XO.exper.1 XO.educ XO.city
    ## 1 3.3540    0.7380211              1       14        196      12       0
    ## 2 1.3889    0.7658325              1        5         25      12       1

The problem is that `get_data.selection` tries to extract the data by
checking if there is an `lm` object inside the model object:

<https://github.com/easystats/insight/blob/master/R/get_data.R#L188>

This is the case here, but the data in question is not what we want:

``` r
"lm" %in% names(mod1)
```

    ## [1] TRUE

``` r
get_data(mod1[["lm"]]) |> head(2)
```

    ##       YO imrData$IMR1 XO.(Intercept) XO.exper XO.exper.1 XO.educ XO.city
    ## 1 3.3540    0.7380211              1       14        196      12       0
    ## 2 1.3889    0.7658325              1        5         25      12       1

Instead, we could potentially do the same as with other models, that is
look up the `data` element of `call` in the parent:

``` r
new_get_data <- function(x, ...) {
    out <- get(insight:::.safe_deparse(x$call$data), envir = parent.frame())
    out <- out[, find_variables(x, flatten = TRUE), drop = FALSE]
    return(out)
}

new_get_data(mod1) |> head(2)
```

    ##   lfp   wage age faminc kids educ exper city
    ## 1   1 3.3540  32  16310 TRUE   12    14    0
    ## 2   1 1.3889  30  21800 TRUE   12     5    1

``` r
new_get_data(mod2) |> head(2)
```

    ##   lfp   wage age faminc kids educ exper city
    ## 1   1 3.3540  32  16310 TRUE   12    14    0
    ## 2   1 1.3889  30  21800 TRUE   12     5    1

**Comment by strengejacke** [comment]
``` r
library("insight")
library("sampleSelection")
#> Loading required package: maxLik
#> Loading required package: miscTools
#> 
#> Please cite the 'maxLik' package as:
#> Henningsen, Arne and Toomet, Ott (2011). maxLik: A package for maximum likelihood estimation in R. Computational Statistics 26(3), 443-458. DOI 10.1007/s00180-010-0217-1.
#> 
#> If you have questions, suggestions, or comments regarding the 'maxLik' package, please use a forum or 'tracker' at maxLik's R-Forge site:
#> https://r-forge.r-project.org/projects/maxlik/
data(Mroz87, package = "sampleSelection")
Mroz87$kids  <- (Mroz87$kids5 + Mroz87$kids618 > 0)

mod1 <- heckit(lfp ~ age + I( age^2 ) + faminc + kids + educ,
               wage ~ exper + I( exper^2 ) + educ + city,
               data = Mroz87)

mod2 <- selection(lfp ~ age + I( age^2 ) + faminc + kids + educ,
                  wage ~ exper + I( exper^2 ) + educ + city,
                  data = Mroz87)

get_data(mod1) |> head(2)
#>   lfp age educ   wage faminc city exper kids
#> 1   1  32   12 3.3540  16310    0    14 TRUE
#> 2   1  30   12 1.3889  21800    1     5 TRUE

get_data(mod2) |> head(2)
#>   lfp age educ   wage faminc city exper kids
#> 1   1  32   12 3.3540  16310    0    14 TRUE
#> 2   1  30   12 1.3889  21800    1     5 TRUE
```

<sup>Created on 2021-12-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
Thanks!
