### ISSUE TITLE
Use `mgcv::interpret.gam` to find smooth terms in a formula

### ISSUE THREAD

**Issue by hsbadr** [easystats/insight#478]
The default `find_predictors()` method doesn't detect `"smooth_terms"` in a GAM formula:
```r
> insight:::find_predictors(y ~ x0 + s(x1) + s(x2))
$conditional
[1] "x0" "x1" "x2"
```
We can use `mgcv::interpret.gam` to get those terms:
```r
> sapply(mgcv::interpret.gam(y ~ x0 + s(x1) + s(x2))$smooth.spec, function(x) x$term)
[1] "x1" "x2"
```
or their labels:
```r
> sapply(mgcv::interpret.gam(y ~ x0 + s(x1) + s(x2))$smooth.spec, function(x) x$label)
[1] "s(x1)" "s(x2)"
```

**Comment by bwiernik** [comment]
Not sure what you mean. The find_predictors() function returns the original (untransformed) variables used to fit the model. The two variables that are part of smooth terms are returned correctly it seems 

```r
> insight:::find_predictors(y ~ x0 + s(x1) + s(x2))
$conditional
[1] "x0" "x1" "x2"
```

**Comment by hsbadr** [comment]
They should be a `smooth_terms` in the returned list. It should return the smooth terms by:
```r
> insight:::find_predictors(y ~ x0 + s(x1) + s(x2), component = "smooth_terms")
NULL
```
I'd expect that this should return `c("x1", "x2")`.

**Comment by strengejacke** [comment]
Have you tried [`find_smooth()`](https://easystats.github.io/insight/reference/find_smooth.html)?

**Comment by hsbadr** [comment]
> Have you tried [`find_smooth()`](https://easystats.github.io/insight/reference/find_smooth.html)?

Yes, `find_smooth()` does return the labels. If `flatten = FALSE`, it returns them under `conditional` though.
```r
> insight::find_smooth(y ~ x0 + s(x1) + s(x2))
$conditional
[1] "s(x1)" "s(x2)"
```
```r
> insight::find_smooth(y ~ x0 + s(x1) + s(x2), flatten = TRUE)
[1] "s(x1)" "s(x2)"
```

`find_parameters` works as exected:
```r
set.seed(2020)
dat <- mgcv::gamSim(1, n = 400, dist = "normal", scale = 2)
mod <- mgcv::gam(y ~ x0 + s(x1) + s(x2), data = dat)
```
```r
> insight::find_parameters(mod)
$conditional
[1] "(Intercept)" "x0"

$smooth_terms
[1] "s(x1)" "s(x2)"
```
On the other hand:
```r
> insight::find_smooth(mod)
$conditional
[1] "s(x1)" "s(x2)"
```
and
```r
> insight::find_predictors(mod)
$conditional
[1] "x0" "x1" "x2"
```

**Comment by strengejacke** [comment]
``` r
insight:::find_smooth(y ~ x0 + s(x1) + s(x2))
#> $smooth
#> [1] "s(x1)" "s(x2)"
insight:::find_smooth(y ~ x0 + s(x1) + s(x2), flatten = TRUE)
#> [1] "s(x1)" "s(x2)"
```

<sup>Created on 2021-12-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hsbadr** [comment]
@strengejacke What's the intended use of `component` argument in `find_predictors()`? Should each component be a different formula for specific models? Specifically, what would you expect from the following?
```r
insight:::find_predictors(y ~ x0 + s(x1) + s(x2), component = "smooth_terms")
```
Right now, this returns `NULL`.

Also, after 9a5dbec0fe3691953d4e634edf18fe6871b57799, `find_smooth()` returns a list with `"smooth"` component. Should it be `"smooth_terms"` for consistency?
