### ISSUE TITLE
Should `find_response` handle added responses?

### ISSUE THREAD

**Issue by hsbadr** [easystats/insight#479]
I'd expect the output of the following:
```r
> insight::find_response(y1 + y2 ~ x)
[1] "y1 + y2"
```
to be identical to
```r
> all.vars((y1 + y2 ~ x)[[2L]])
[1] "y1" "y2"
```
even though this isn't a typical multivariate formula.

**Comment by bwiernik** [comment]
What's the context in which you want to use a formula like this? Seems prone to mis-parsing

**Comment by hsbadr** [comment]
> What's the context in which you want to use a formula like this?

I don't have an example right now because this isn't a typical formula, but in general, what `find_response()` returns (`"y1 + y2"`) doesn't look right. I think it should be identical to `all.vars((y1 + y2 ~ x)[[2L]])` or:
```r
> tune::outcome_names(y1 + y2 ~ x)
[1] "y1" "y2"
```

This issue is a question for the unfamiliar use of this type of formula in R.

**Comment by hsbadr** [comment]
[Here](https://community.rstudio.com/t/how-to-get-predictions-with-multiple-outcomes-with-knn-model-using-tidymodels/86427)'s an example.

**Comment by strengejacke** [comment]
Does `find_response(x, combine = FALSE)` work?

**Comment by hsbadr** [comment]
> Does `find_response(x, combine = FALSE)` work?

No, it doesn't:
```r
> insight::find_response(y1 + y2 ~ x, combine = FALSE)
[1] "y1 + y2"
```

**Comment by strengejacke** [comment]
``` r
insight::find_response(y1 + y2 ~ x, combine = FALSE)
#> [1] "y1" "y2"
insight::find_response(y1 + y2 ~ x, combine = TRUE)
#> [1] "y1 + y2"
```

<sup>Created on 2021-12-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
