### ISSUE TITLE
Request for h2o model support

### ISSUE THREAD

**Issue by PatrickJohnston** [easystats/insight#48]
This is a very helpful package--thanks for making it! I use the h2o package a lot for my machine learning models. Could the models associated with that package--especially `h2o::h2o.automl`--be integrated into insight? Thanks!

**Comment by DominiqueMakowski** [comment]
@strengejacke any thoughts on this?

**Comment by strengejacke** [comment]
I have installed h2o some time ago for a keras/tensor flow workshop from a R User Group Meeting here in Hamburg. Currently, I have a lot to do (finishing papers etc.), but I will get back to this in March. Then we could give a more detailed perspective on how and if this is possible to implement.

**Comment by PatrickJohnston** [comment]
Thanks! Much appreciate your efforts to date and future work on this package. It's extremely useful.

**Comment by strengejacke** [comment]
Do you have a reproducible example, which is "meaningful"? The example from `?h2o.aml` looks like the "response" variable is `class`, while predictors are `V1` to `V16`, and the data frame / model frame is `votes_hf`. Is that correct?

Furthermore, can such models have more complex formulas or components, or is it just "fixed effects" with `Class ~ V1 + V2 + V3 + V4 + V5...`?

**Comment by strengejacke** [comment]
_bump_

**Comment by strengejacke** [comment]
_bump_

**Comment by strengejacke** [comment]
_bump_

**Comment by PatrickJohnston** [comment]
No. Request withdrawn.
