### ISSUE TITLE
Further features for `get_predicted()`

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#486]
The only two issues that I hoped to address eventually are:

+ `get_predicted.brmsfit`: `random.only` could be supplied manually instead of hard-coded. Look into `names(list(...))`, and if the user supplied it, override the hard-coded value by `include_random`.
+ `get_predicted.coxph`: does not currently accept `type`

Neither seems particularly urgent.

_Originally posted by @vincentarelbundock in https://github.com/vincentarelbundock/marginaleffects/issues/179#issuecomment-1004185329_

**Comment by strengejacke** [comment]
@vincentarelbundock The second point is resolved in #530, but what about the first point?

**Comment by vincentarelbundock** [comment]
The question arises here:

https://github.com/easystats/insight/blob/master/R/get_predicted_mixed.R#L25

Do we want to allow users to override `random.only` by supplying it through `...`, or is it better to do this automatically like now? I'm not sure I have a clear opinion, and I'm not sure if there would be demand for that, so it's probably OK to close this until someone requests it.
