### ISSUE TITLE
`get_data.survival` returns transformed data

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#487]
`get_data.survival` returns transformed data (note the `sex=0` entries) rather than the original data frame:

``` r
library(survival)
library(insight)

dat <- list(
    time = c(4, 3, 1, 1, 2, 2, 3),
    status = c(1, 1, 1, 0, 1, 1, 0),
    x = c(0, 2, 1, 1, 1, 0, 0),
    sex = c(0, 0, 0, 0, 1, 1, 1))
mod <- coxph(Surv(time, status) ~ x + strata(sex),
             data = dat, ties = "breslow")
get_data(mod)
```

    ##   time status Surv(time, status) x   sex
    ## 1    4      1                  4 0 sex=0
    ## 2    3      1                  3 2 sex=0
    ## 3    1      1                  1 1 sex=0
    ## 4    1      0                 1+ 1 sex=0
    ## 5    2      1                  2 1 sex=1
    ## 6    2      1                  2 0 sex=1
    ## 7    3      0                 3+ 0 sex=1

**Comment by strengejacke** [comment]
``` r
library(survival)
library(insight)

dat <- list(
  time = c(4, 3, 1, 1, 2, 2, 3),
  status = c(1, 1, 1, 0, 1, 1, 0),
  x = c(0, 2, 1, 1, 1, 0, 0),
  sex = c(0, 0, 0, 0, 1, 1, 1))
mod <- coxph(Surv(time, status) ~ x + strata(sex),
             data = dat, ties = "breslow")
get_data(mod)
#>   time status Surv(time, status) x sex
#> 1    4      1                  4 0   0
#> 2    3      1                  3 2   0
#> 3    1      1                  1 1   0
#> 4    1      0                 1+ 1   0
#> 5    2      1                  2 1   1
#> 6    2      1                  2 0   1
#> 7    3      0                 3+ 0   1
```

<sup>Created on 2022-01-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
Wonderful, thanks! I swear I intended to handle this, but life got in the way...
