### ISSUE TITLE
gam parameters: what to include?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#49]
rstanarm, when fitting gamm4 like models, returns a number of "parameters" related to the smooth term (in the form `s(smoothterm).1...9`, and I am wondering whether to include these K components into the "parameters" / predictors list. This is also the case for mgcv, for which `find_parameters` returns smooth parameters whereas the summary has a "general" (more interesting for users) smooth parameter.

```
> insight::find_parameters(mgcv::gam(Petal.Length ~ s(Petal.Width), data=iris))
$`conditional`
 [1] "(Intercept)"      "s(Petal.Width).1" "s(Petal.Width).2" "s(Petal.Width).3" "s(Petal.Width).4"
 [6] "s(Petal.Width).5" "s(Petal.Width).6" "s(Petal.Width).7" "s(Petal.Width).8" "s(Petal.Width).9"
```

**Comment by DominiqueMakowski** [comment]
I realise this is a larger question, as get_parameters behaves differently for GAMs of different packages:

```r
# gam
model_1 <- gam::gam(Petal.Length ~ gam::s(Petal.Width, 9), data=iris)
summary(model_1)
insight::find_terms(model_1)
insight::get_parameters(model_1)

# mgcv
model_2 <- mgcv::gam(Petal.Length ~ s(Petal.Width), data=iris)
summary(model_2)
insight::find_terms(model_2)
insight::get_parameters(model_2)

# gamm4
model_3 <- gamm4::gamm4(Petal.Length ~ s(Petal.Width), data=iris)
summary(model_3)
insight::find_terms(model_3)
insight::get_parameters(model_3)

# brms
model_4 <- brms::brm(Petal.Length ~ s(Petal.Width), data=iris)
summary(model_4)
insight::find_terms(model_4)
insight::get_parameters(model_4)

# rstanarm
model_5 <- rstanarm::stan_gamm4(Petal.Length ~ s(Petal.Width), data=iris)
summary(model_5)
insight::find_terms(model_5)
insight::get_parameters(model_5)
```

The parameters of the smooth term are different for get_parameters: 

- The K components  (mgcv, gamm4 and rstanarm)
- only one parameter for the smooth in gam::gam 
- nothing for brms

I think the most appropriate parameter, user-wise, would be the "general" smooth parameters, such as `sds(Smoothterm)` and `sSmoothterm` in brms. For rstanarm, I am not even sure such [parameter exists](https://discourse.mc-stan.org/t/general-parameters-of-smooth-term-in-gams-in-rstanarm/7737).

**Comment by strengejacke** [comment]
I think a first guideline is the `summary()` output. For brms, the smooth term is now returned. I'll check the other model types as well.

**Comment by strengejacke** [comment]
Ok, first step is done:

``` r
library(insight)

# gam
model_1 <- gam::gam(Petal.Length ~ gam::s(Petal.Width, 9), data=iris)
summary(model_1)
#> 
#> Call: gam::gam(formula = Petal.Length ~ gam::s(Petal.Width, 9), data = iris)
#> Deviance Residuals:
#>      Min       1Q   Median       3Q      Max 
#> -1.33542 -0.30347 -0.02955  0.25776  1.39453 
#> 
#> (Dispersion Parameter for gaussian family taken to be 0.2287)
#> 
#>     Null Deviance: 464.3254 on 149 degrees of freedom
#> Residual Deviance: 33.8448 on 148 degrees of freedom
#> AIC: 208.3539 
#> 
#> Number of Local Scoring Iterations: 2 
#> 
#> Anova for Parametric Effects
#>                         Df Sum Sq Mean Sq F value    Pr(>F)    
#> gam::s(Petal.Width, 9)   1 430.48  430.48  1882.5 < 2.2e-16 ***
#> Residuals              148  33.84    0.23                      
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
insight::find_parameters(model_1)
#> $conditional
#> [1] "(Intercept)"
#> 
#> $smooth_terms
#> [1] "gam::s(Petal.Width, 9)"
insight::get_parameters(model_1)
#> $conditional
#>     parameter estimate
#> 1 (Intercept) 1.083558
#> 
#> $smooth_terms
#>                parameter estimate
#> 1 gam::s(Petal.Width, 9)  2.22994

# mgcv
model_2 <- mgcv::gam(Petal.Length ~ s(Petal.Width), data=iris)
summary(model_2)
#> 
#> Family: gaussian 
#> Link function: identity 
#> 
#> Formula:
#> Petal.Length ~ s(Petal.Width)
#> 
#> Parametric coefficients:
#>             Estimate Std. Error t value Pr(>|t|)    
#> (Intercept)  3.75800    0.03102   121.2   <2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Approximate significance of smooth terms:
#>                  edf Ref.df   F p-value    
#> s(Petal.Width) 5.562  6.687 459  <2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> R-sq.(adj) =  0.954   Deviance explained = 95.5%
#> GCV = 0.15093  Scale est. = 0.14433   n = 150
insight::find_parameters(model_2)
#> $conditional
#> [1] "(Intercept)"
#> 
#> $smooth_terms
#> [1] "s(Petal.Width)"
insight::get_parameters(model_2)
#> $conditional
#>     parameter estimate
#> 1 (Intercept)    3.758
#> 
#> $smooth_terms
#>        parameter estimate
#> 1 s(Petal.Width) 5.561587

# gamm4
model_3 <- gamm4::gamm4(Petal.Length ~ s(Petal.Width), data=iris)
summary(model_3)
#>     Length Class   Mode
#> mer  1     lmerMod S4  
#> gam 32     gam     list
insight::find_parameters(model_3)
#> $conditional
#> [1] "(Intercept)"
#> 
#> $smooth_terms
#> [1] "s(Petal.Width)"
insight::get_parameters(model_3)
#> $conditional
#>     parameter estimate
#> 1 (Intercept)    3.758
#> 
#> $smooth_terms
#>        parameter estimate
#> 1 s(Petal.Width) 5.364408
```

<sup>Created on 2019-03-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by strengejacke** [comment]
Two things:

1) Should we always return a list with data frames for model with smooth terms, or also add a `component`-argument?

2) For rstanarm, what is the required parameter to return? `smooth_sd*`?

**Comment by DominiqueMakowski** [comment]
I will skip the k components of the smooth when applicable, as these are rarely used directly. For rstanarm, the answer to [my question](https://discourse.mc-stan.org/t/general-parameters-of-smooth-term-in-gams-in-rstanarm/7737) was not very informative... So I don't know... 

In general, a reasonable solution would be to keep one parameter for the smooth, representing the "wiggliness" (or two, as does brms*, returning wiggliness and the general linear trend)

**Comment by DominiqueMakowski** [comment]
And for the first question, I would tend to think that a component argument is ok

**Comment by strengejacke** [comment]
We need to check vgam as well.

**Comment by strengejacke** [comment]
I have slightly changed the behaviour for smooth term models, to be in line with zero-inflated models. This makes more sense to me, since we usually always have a data frame, and no list (except for random effects from mixed models, but we may think about changing this behaviour as well):

``` r
library(insight)
library(pscl)
library(mgcv)

model_1 <- zeroinfl(art ~ fem + mar| phd + kid5, data = bioChemists)
get_parameters(model_1)
#>           parameter   estimate         group
#> 1 count_(Intercept)  0.8242363   conditional
#> 2    count_femWomen -0.2442357   conditional
#> 3  count_marMarried  0.0445337   conditional
#> 4  zero_(Intercept) -0.8134269 zero_inflated
#> 5          zero_phd -0.2359216 zero_inflated
#> 6         zero_kid5  0.2579755 zero_inflated

model_2 <- mgcv::gam(Petal.Length ~ s(Petal.Width) + Sepal.Length, data=iris)
get_parameters(model_2)
#>        parameter  estimate    component
#> 1    (Intercept) 0.6122537  conditional
#> 2   Sepal.Length 0.5383479  conditional
#> 3 s(Petal.Width) 6.8704889 smooth_terms
```

<sup>Created on 2019-03-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by strengejacke** [comment]
Ok, works with brms now as well, and I made the arguments consistent. The question is for `get_parameters()` for Bayesian models: Should we return the posterior samples (as we do now), or already a mean / median "estimate", as we do for other functions?

**Comment by strengejacke** [comment]
@DominiqueMakowski *ping*

>  for Bayesian models: Should we return the posterior samples (as we do now), or already a mean / median "estimate", as we do for other functions?

**Comment by DominiqueMakowski** [comment]
sorry, 

I would go for the posterior samples, as this is the de facto expected behaviour when dealing with Bayesian analyses, as well as a core difference. Its up to the user to further do whatever they want to summarise the parameters, but the parameters in the Bayesian context *are* the whole the posterior distributions

**Comment by strengejacke** [comment]
Fine, so this one can also be closed. :-)
