### ISSUE TITLE
export parameter string formatting functions from `{insight}`? 

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/insight#491]
A number of these functions are widely used across multiples packages in the ecoyststem, and I am wondering if it might be worth exporting them from `{insight}`. 

https://github.com/easystats/insight/blob/20588c646676baa94f14483e1a5c354ba25f78f7/R/helper_functions.R#L540-L571

These will not be ideal for inclusion in `{datawizard}` though. And, anyway, if we include it there, they can't be used it `{insight}`.

**Comment by DominiqueMakowski** [comment]
sure, should we export them as `text_capitalize()` and `text_remove_backticks(column = "Parameter")` (that would also have a bespoke method for strings and matrices)?

**Comment by IndrajeetPatil** [comment]
@strengejacke What do you think?

**Comment by strengejacke** [comment]
I'm working on it, please no commits to this repo at the moment.

**Comment by strengejacke** [comment]
(there were a lot of files needed to be changed, so I wanted to avoid conflicts)
