### ISSUE TITLE
get_statistic for h-tests error

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#492]
``` r
insight::get_statistic(cor.test(iris$Sepal.Width, iris$Sepal.Length))
#> Error: $ operator is invalid for atomic vectors
```

<sup>Created on 2022-01-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by IndrajeetPatil** [comment]
Yikes! Does this mean we will need to first update `{insight}` on CRAN, and then `{report}`? 😞

**Comment by DominiqueMakowski** [comment]
nah in the end I didn't need it anyway

**Comment by strengejacke** [comment]
This is actually not a bug, because we don't support `get_statistic()` for `htest` objects yet (and never did so far).

**Comment by DominiqueMakowski** [comment]
or at least an informative error saying

![](https://i.redd.it/bluijtpf03961.jpg)

**Comment by IndrajeetPatil** [comment]
> The question is rather: do we want to add support?

Maybe, no?

We can implement these methods only if other users or other developers make this feature request. 

For now, we should just have an informative error message asking the users to file an issue if they want this to be supported.

**Comment by bwiernik** [comment]
The slot is just named "statistic", so it's trivial to support:


```r
get_statistic.htest <- function(x, ...) {
  x$statistic
}
```
