### ISSUE TITLE
revise `get_predicted()`

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#499]
I currently find it particular difficult to follow when predictions are on response scale, when (back-)transformed etc. I suggest revising the underlying functions in a way that

- we always calculate prediction on the link-scale when `predict` is `"expectation"` / `"response"`, so we always need to back-transform.
- CIs are ~ predictions +/- 1.96 * se, on the link scale / scale of linear predictor
- the function to back-transform is _always_ called, and for linear, the link-inverse function is just `"mu"`, so no problem here. we back-transform predictions and CI, and delta-se
- we can then take special cases into account, like zi-prob for glmmTMB etc.

we may streamline the process a bit, to have a simpler API / internal code.

**Comment by strengejacke** [comment]
@vincentarelbundock @bwiernik @DominiqueMakowski what do you think?

**Comment by vincentarelbundock** [comment]
I agree that the process could be streamlined a bit. However, I'm a bit scared by the "default to backtransform" approach. Are we 100% *sure* that we have the capacity to do this accurately for a wide enough variety of models to treat it as a default option? Do we have tests for all of those models and known benchmark results against which to compare our output?

If we can only be 100% confident & tested for `glm()`, `glmmTMB()`, then we should of course do those. But unless we have tests and benchmarks for a given model, then I'd argue that it's best to rely on the developer of the package, even if the output is not as fully-featured (perhaps issuing a note or warning when appropriate).

**Comment by strengejacke** [comment]
Most packages' `predict()` returns the SE on the linear scale, so we need to back-transform anyway...

**Comment by bwiernik** [comment]
I share some of Vincent's concerns. I am also not sure how universally 
~ predictions +/- 1.96 * se, on the link scale / scale of linear predictor will yield accurate intervals. I'd like to incorporate this workflow into models on case by case basis

**Comment by vincentarelbundock** [comment]
> Most packages' `predict()` returns the SE on the linear scale, so we need to back-transform anyway...

Sure. My point is just that "most packages" is not specific enough. If any of the supported models don't return SE on the linear scale, then we risk producing incorrect results unless we have specifically flagged them.

Basically, my view is that `.default` methods are perfectly fine if all we are doing is extracting some information from an object and if we document the output as "raw" info. However, `.default` methods should never be used to apply any kind of transformation.

But maybe I'm paranoid...

**Comment by strengejacke** [comment]
But this is what we already do:
https://github.com/easystats/insight/blob/631446882f8ead1ec6337b58d90ad8627902db6c/R/get_predicted.R#L403

maybe noone realized because of this slightly confusing code ;-)

**Comment by vincentarelbundock** [comment]
> But this is what we already do:
> 
> https://github.com/easystats/insight/blob/631446882f8ead1ec6337b58d90ad8627902db6c/R/get_predicted.R#L403
> 
> maybe noone realized because of this slightly confusing code ;-)

😂 hehe, yes!

But if we're going to re-factor anyway, I think we should move to a safer system.

**Comment by strengejacke** [comment]
I can't imagine how a "safer" way would look like. If we use `predict(type = "response")`, and we get predictions and SE, we would need to backtransform anyway, else we can't compute CI.

**Comment by strengejacke** [comment]
(see https://strengejacke.github.io/ggeffects/articles/technical_stata.html)

**Comment by vincentarelbundock** [comment]
I think I probably don't understand the code well enough.

At this stage, I'll be very happy if you simplify things as you see fit.

I could also sit with the code a bit and make a PR proposal if you want. But feel free to take a stab at it if you have a vision + energy; that would be great.

**Comment by strengejacke** [comment]
I _guess_ the general problem is:

- you get predictions on the response scale
- you get SE's (not sure, if on response or link scale?)
- when both predictions and SE are on the response scale, we need to back-transform both to get proper CIs
- when predictions are on response, SE are not, we need to back-transform SE to get proper CI

my point is that I assume that we need the link / linear predictor scale in general if we want CIs. What would be the alternative if we have predictions and SE only, to get the related CI?

**Comment by vincentarelbundock** [comment]
Yes, that all makes sense.

What I'm saying is that there should be two paths: (1) make 100% sure we know the scale & write a test, or (2) do *not* compute confidence intervals.

That may be what we are doing already, in which case all my previous posts can be ignored.

**Comment by strengejacke** [comment]
Yes, I think this is currently happening. `get_predicted.default()` just calls `predict()`, w/o any CI. So basically, we make the current code a bit cleaner and easier to understand, and then we carefully add methods (and tests) for further model objects.

**Comment by strengejacke** [comment]
> I share some of Vincent's concerns. I am also not sure how universally ~ predictions +/- 1.96 * se, on the link scale / scale of linear predictor will yield accurate intervals. I'd like to incorporate this workflow into models on case by case basis

Ok, I agree. Let's streamline the API and make it work for the "general" case (https://github.com/easystats/insight/pull/501), and then add model by model and decide, whether/which intervals make sense (or at least add a warning why intervals might be inaccurate)

**Comment by vincentarelbundock** [comment]
We can close this, right?

**Comment by strengejacke** [comment]
Yeah, I think so. We have the basics in the PRs and can go on from there.
