### ISSUE TITLE
License

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#5]
Naive question; what motivated the choice of the license?

**Comment by strengejacke** [comment]
What license would you prefer?

**Comment by DominiqueMakowski** [comment]
Got no opinion I asked out of curiosity, the licence/legal stuff is quite nebulous to me...

**Comment by DominiqueMakowski** [comment]
Funnily, this post just popped out on rbloggers:

https://www.r-bloggers.com/how-gpl-makes-me-leave-r-for-python/

I am not sure if there are any practical consequences for us though

**Comment by strengejacke** [comment]
Using MIT would be an alternative, so companies can use our code, integrate it in their proprietary software and release that software as closed source. I'm not aware of the scope of our usership.

But I'm open to less "restrictive" licenses.

**Comment by DominiqueMakowski** [comment]
I don't think it really matters, either way, commercial and non-free stats software are not a serious threat to open-source tools anymore...

**Comment by strengejacke** [comment]
What would you suggest how we proceed with the license?

**Comment by DominiqueMakowski** [comment]
You mean about unifying them... Reading a bit further it seems that it's best to stick with R's default  (i.e., GPL 3.0). Need to change them where it is MIT
