### ISSUE TITLE
Name for function that returns "raw" terms?

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#50]
I would like to add a function similar to `find_terms()`, however, terms should be returned "as is", i.e. as they were used in the formula. Do you have any clever name for this function?

``` r
library(insight)
m <- lm(mpg ~ I(cyl^2) + log(hp), data = mtcars)

find_terms(m)
#> $response
#> [1] "mpg"
#> 
#> $conditional
#> [1] "cyl" "hp"

find_???(m)
#> $response
#> [1] "mpg"
#> 
#> $conditional
#> [1] "I(cyl^2)" "log(hp)"
```

**Comment by strengejacke** [comment]
"feature" sounds too ML to me, but variables indeed sounds good!

**Comment by strengejacke** [comment]
Ok, I implemented `find_variable()` (will commit later from home). But adding tests is horrible, if we really want to cover all tested models...

**Comment by DominiqueMakowski** [comment]
Yes, extensive testing is a pain 😅
