### ISSUE TITLE
merge the `get_predicted` and `get_predicted_ci` docs

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#504]
Suggested here: https://github.com/easystats/insight/issues/497#issuecomment-1025288326

This would make it easier for users to discover the documentation for the `vcov_*` arguments.

**Comment by vincentarelbundock** [comment]
@strengejacke improved the `...` documentation here: https://github.com/easystats/insight/commit/7d8d1ea7dc434c5f223f5ba71057753bb732323f

I still think merging is a good idea, but perhaps less urgent than before? What do people think?

**Comment by strengejacke** [comment]
People would probably rather look for `get_predicted()` than `get_predicted_ci()`, so I'd say merging still makes sense.
