### ISSUE TITLE
`find_variables` and `strata()` in a formula

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#507]
I’m not sure what the best approach is, but it would be nice if
`find_variables()` was able to apply a distinct label to `strata()`
variables:

``` r
library(insight)
library(survival)

dat <- list(time = c(4, 3, 1, 1, 2, 2, 3),
            status = c(1, 1, 1, 0, 1, 1, 0),
            x = c(0, 2, 1, 1, 1, 0, 0),
            sex = c(0, 0, 0, 0, 1, 1, 1))
mod <- coxph(Surv(time, status) ~ x + strata(sex), data = dat, ties = "breslow")

find_variables(mod)
```

    ## $response
    ## [1] "time"   "status"
    ## 
    ## $conditional
    ## [1] "x"   "sex"

**Comment by strengejacke** [comment]
Ok, how do I modify the 2nd regex so that `non_strata` returns `~x`, instead of `~x+`?

``` r
f <- "~ x + strata(sex)"
strata <- gsub("(.*)strata\\((.*)\\)(.*)", "\\2", f)
non_strata <- gsub("(.*)strata\\((.*)\\)(.*)", "\\1\\3", f)

strata
#> [1] "sex"
non_strata
#> [1] "~ x + "
```

<sup>Created on 2022-02-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
Same here, 2nd regex should return `"~ x + x2"`.

``` r
f <- "~ x + strata(sex) + x2"
strata <- gsub("(.*)strata\\((.*)\\)(.*)", "\\2", f)
non_strata <- gsub("(.*)strata\\((.*)\\)(.*)", "\\1\\3", f)

strata
#> [1] "sex"
non_strata
#> [1] "~ x +  + x2"
```

<sup>Created on 2022-02-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
(I think this is a @bwiernik question)

**Comment by vincentarelbundock** [comment]
One option:

``` r
f1 <- "~ strata(sex) + x + x2"
f2 <- "~ x + strata(sex) + x2"
f3 <- "~ x + x2 + strata(sex)"

yes_strata <- ".*strata\\((.*)\\).*"
no_strata <- "strata\\(.*\\)\\s*\\+*|\\+\\s*strata\\(.*\\)"

gsub(yes_strata, "\\1", f1)
    ## [1] "sex"
gsub(yes_strata, "\\1", f2)
    ## [1] "sex"
gsub(yes_strata, "\\1", f3)
    ## [1] "sex"
gsub(no_strata, "", f1)
    ## [1] "~  x + x2"
gsub(no_strata, "", f2)
    ## [1] "~ x  + x2"
gsub(no_strata, "", f3)
    ## [1] "~ x + x2 "
```

**Comment by bwiernik** [comment]
That works. Thanks @vincentarelbundock! Can a survival formula have multiple strata terms?

**Comment by vincentarelbundock** [comment]
I don't this model well, but looks like yes in this format: `strata(x, y, z)` and there can be arguments too. Hmm..

**Comment by bwiernik** [comment]
So we need to split the `yes_strata` match on `,\s*`

**Comment by strengejacke** [comment]
![24900613](https://user-images.githubusercontent.com/26301769/154865752-6fb8b2f2-3724-4500-a9f4-fcc98aecad46.jpg)

**Comment by bwiernik** [comment]
Sometimes you have a problem and you decide to solve it with regex. Then you have two problems

**Comment by vincentarelbundock** [comment]
I'm not sure we need to support every possible function completely in formulas. In this case, we could maybe just include a check for `,` and error out with an informative message. If someone really cares about this functionality in the future they could always come in and PR something better.

**Comment by bwiernik** [comment]
Just pass it to `strsplit()`...

**Comment by vincentarelbundock** [comment]
> Just pass it to `strsplit()`...

`strata` also accepts named arguments (`group`, `shortlabel`, `sep`), so you would then have to check for `=` or for one of these. It's getting a bit complicated for what seems like a niche functionality.

**Comment by bwiernik** [comment]
What's the goal with separating the strata parts?

**Comment by vincentarelbundock** [comment]
> What's the goal with separating the strata parts?

The `find_variables()` and `find_predictors()` functions return a named list of variables. For example, in `lmer` models we can get variables labelled as `"cluster"`. The "strata" category in survival felt analogous to "cluster".

More directly, one of my tests broke because I could not determine if the `strata` variables was a numeric or a categorical:

https://github.com/vincentarelbundock/marginaleffects/issues/215

**Comment by strengejacke** [comment]
> ```r
> "strata\\(.*\\)\\s*\\+*|\
> ```

Is it only about the `+` operator, or can `strata()` variables also be multiplied / divided? If so, we need to take care for those operations, too.

**Comment by vincentarelbundock** [comment]
I couldn't find any examples online with an interaction (after a very quick search), but it does seem to produce different coefficient estimates when we use `*`. Perhaps it would be safer to use these:

``` r
f1 <- "~ strata(sex) * x + x2"
f2 <- "~ x * strata(sex) * x2"
f3 <- "~ x + x2 * strata(sex)"
f4 <- "~ strata(sex) + x + x2"
f5 <- "~ x * strata(sex) + x2"
f6 <- "~ x + x2 + strata(sex)"


yes_strata <- ".*strata\\((.*)\\).*"
no_strata <- "strata\\(.*\\)\\s*[\\+|\\*]*|[\\+|\\*]\\s*strata\\(.*\\)"

gsub(yes_strata, "\\1", f1)
    ## [1] "sex"
gsub(yes_strata, "\\1", f2)
    ## [1] "sex"
gsub(yes_strata, "\\1", f3)
    ## [1] "sex"
gsub(no_strata, "", f1)
    ## [1] "~  x + x2"
gsub(no_strata, "", f2)
    ## [1] "~ x  * x2"
gsub(no_strata, "", f3)
    ## [1] "~ x + x2 "
gsub(no_strata, "", f4)
    ## [1] "~  x + x2"
gsub(no_strata, "", f5)
    ## [1] "~ x  + x2"
gsub(no_strata, "", f6)
    ## [1] "~ x + x2 "
