### ISSUE TITLE
Export `safe_deparse()`, `.n_unique()`, and `.trim()`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/insight#519]
These are used throughout the ecosystem.

Better to have just one copy in _insight_ and export them so that other packages can use this function.

**Comment by strengejacke** [comment]
`.trim()` is only used because I didn't know `base::trimws()`. We could probably replace all `.trim()` with `trimws()`, unless it was introduced in a later R version than 3.4?

**Comment by strengejacke** [comment]
`deparse1()` is actually comparable to `.safe_deparse()`, but introduced in R 4.0, so exporting `safe_deparse()` would make sense. Same to `n_unique()`, but that name is masked by _dplyr_.

**Comment by IndrajeetPatil** [comment]
> We could probably replace all .trim() with trimws(), unless it was introduced in a later R version than 3.4?

If I am reading [this](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/trimws) correctly, it was introduced in 3.6, so maybe we should use our own variant.

> Same to n_unique(), but that name is masked by dplyr.

_dplyr_ has `n_distinct()`, so we can use `n_unique()`.

**Comment by strengejacke** [comment]
hm... https://www.rdocumentation.org/packages/base/versions/3.4.0/topics/trimws ? Is that a proof?

**Comment by strengejacke** [comment]
Maybe since R 3.2: https://www.rdocumentation.org/packages/base/versions/3.2.0/topics/trimws

Other URLs before R 3.2 do not work.

**Comment by strengejacke** [comment]
Anyway, we should use our function:

``` r
x <- "  fdsf dff  "
microbenchmark::microbenchmark(
  insight:::.trim(x),
  trimws(x),
  times = 10000
)
#> Unit: microseconds
#>                expr   min    lq      mean median    uq     max neval cld
#>  insight:::.trim(x)  26.2  27.7  33.30894   28.9  29.9 28203.9 10000  a 
#>           trimws(x) 142.7 144.9 153.56400  147.4 151.5  2391.7 10000   b


x <- rep("  fdsf dff  ", 10)
microbenchmark::microbenchmark(
  insight:::.trim(x),
  trimws(x),
  times = 1000
)
#> Unit: microseconds
#>                expr   min    lq     mean median    uq   max neval cld
#>  insight:::.trim(x)  31.3  32.4  35.2520   33.9  34.7 128.1  1000  a 
#>           trimws(x) 147.4 149.5 157.0298  151.7 156.1 399.3  1000   b
```

<sup>Created on 2022-03-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bwiernik** [comment]
Wow that's slow

**Comment by IndrajeetPatil** [comment]
> Wow that's slow

Possibly due to the base version being more flexible and spending some time in validating the arguments.
But we don't need this flexibility anyway, so nice to have the faster alternative. 

``` r
insight:::.trim
#> function(x) gsub("^\\s+|\\s+$", "", x)
#> <bytecode: 0x00000000195815f0>
#> <environment: namespace:insight>

base::trimws
#> function (x, which = c("both", "left", "right"), whitespace = "[ \t\r\n]") 
#> {
#>     which <- match.arg(which)
#>     mysub <- function(re, x) sub(re, "", x, perl = TRUE)
#>     switch(which, left = mysub(paste0("^", whitespace, "+"), 
#>         x), right = mysub(paste0(whitespace, "+$"), x), both = mysub(paste0(whitespace, 
#>         "+$"), mysub(paste0("^", whitespace, "+"), x)))
#> }
#> <bytecode: 0x0000000015ba6598>
#> <environment: namespace:base>
```

<sup>Created on 2022-03-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by IndrajeetPatil** [comment]
@strengejacke Is it possible to resolve this before the next _insight_ CRAN submission?

Will make the code copy clean-up in the rest of the packages much faster.

**Comment by strengejacke** [comment]
yes.

**Comment by strengejacke** [comment]
If you like, you can add some tests :-)

**Comment by IndrajeetPatil** [comment]
Awesome, will do! :)

**Comment by strengejacke** [comment]
I also added data frame and list methods, where useful.

**Comment by strengejacke** [comment]
``` r
x <- tibble::tibble(a = rnorm(1:10), b = paste0(" ", letters[1:10]), c = c(LETTERS[1:5], LETTERS[1:5]))
x
#> # A tibble: 10 x 3
#>         a b     c    
#>     <dbl> <chr> <chr>
#>  1  0.242 " a"  A    
#>  2  0.613 " b"  B    
#>  3 -2.97  " c"  C    
#>  4  2.17  " d"  D    
#>  5 -0.367 " e"  E    
#>  6  1.09  " f"  A    
#>  7 -1.79  " g"  B    
#>  8 -1.13  " h"  C    
#>  9 -1.62  " i"  D    
#> 10 -0.387 " j"  E

trim_ws(x)
#> Error in trim_ws(x): could not find function "trim_ws"
trim_ws(x, character_only = FALSE)
#> Error in trim_ws(x, character_only = FALSE): could not find function "trim_ws"

n_unique(x)
#> Error in n_unique(x): could not find function "n_unique"
```

<sup>Created on 2022-03-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
