### ISSUE TITLE
get_variances()

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#52]
The internals for `r2()` in pkg _performance_ could go into this package, as official exported function. The different variance-components are useful in different contexts, so it might fit into this pkg.

**Comment by DominiqueMakowski** [comment]
definitely

**Comment by strengejacke** [comment]
Ok, the core functionality is implemented. I would also like to return the random-slope and random-intercept variances as well (see https://strengejacke.github.io/sjstats/reference/re_var.html).

By this, people can easily calculate ICCs for specific levels of mixed models.
