### ISSUE TITLE
get_datagrid: deal with monotonic

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#520]
Need to transform to int / ordered factors when detected. I think you implemented that in ggeffects already if I'm not mistaken

``` r
library(brms)

model <- brm(mpg ~ mo(carb), data = mtcars, refresh = 0)

df <- insight::get_datagrid(model)
insight::get_predicted(model, data = df)
#> Error: Invalid values in variable 'carb': '1.77777777777778', '2.55555555555556', '3.33333333333333', '4.11111111111111', '4.88888888888889', '5.66666666666667', '6.44444444444444', '7.22222222222222'
```

<sup>Created on 2022-03-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DominiqueMakowski** [comment]
https://github.com/strengejacke/ggeffects/issues/216

**Comment by strengejacke** [comment]
I _think_ we can just add the `mo` pattern here:

https://github.com/easystats/insight/blob/1c91a8e9dd43ffdc9e23ac1a1de9ada21290f0b5/R/utils_get_data.R#L235

And should be ok.

**Comment by bwiernik** [comment]
Let's also add `as_factor`, ordered, as.ordered, and as_ordered while we are at it

**Comment by strengejacke** [comment]
ok, doesn't work, because column names don't contain that pattern. Will try something else.
