### ISSUE TITLE
get_predicted brms improvements

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#521]
I was about to write concerning this: https://github.com/paul-buerkner/brms/issues/1309, so that `get_predicted()` automatically sets `re_formula = NA` if random variables of data are `NA`.  

But it seems that it does it already as it doesn't fail on the newest (GH version) brms. However, I noticed a few possible improvements:

``` r
library(brms)

data <- mtcars
data$cyl <- as.character(data$cyl)

model <- brm(cyl ~ mpg * vs + (1 | carb),
             data = data,
             chains = 6,
             iter = 3000,
             algorithm = "meanfield",
             refresh=0,
             family = categorical(link = "logit", refcat = "4"))
#> Compiling Stan program...
#> Start sampling
#> Warning: Pareto k diagnostic value is 0.97. Resampling is unreliable. Increasing
#> the number of draws or decreasing tol_rel_obj may help.

# Carb = NA
newdata <- data.frame(mpg = 20, vs = 0, carb = NA)
```

```r
pred <- insight::get_predicted(model, newdata = newdata)
#> Error in posterior_epred.brmsfit(x, newdata = args$data, re.form = args$re.form, : formal argument "newdata" matched by multiple actual arguments
```

1. Though our argument is named data, I suspect some users might try using `newdata` if they try to simply replace the functions with datawizard.  We should probably run a check on the ellipsis and see whether there is an argument called newdata that would supersedes a null data one (with or without out a warning).

```r
pred <- insight::get_predicted(model, data = newdata)
pred
#> Predicted values:
#> 
#>   Row Response    Predicted
#> 1   1        4 0.0003576466
#> 2   1        6 0.6150440761
#> 3   1        8 0.3845982773
#> 
#> NOTE: Confidence intervals, if available, are stored as attributes and can be accessed using `as.data.frame()` on this output.
```

It says in the docs that `iterations=NULL` returns all iterations, but here it returns the summary 🤔🤔 
```r
pred <- insight::get_predicted(model, data = newdata, iterations = 10)
#> Warning: Argument 'nsamples' is deprecated. Please use argument 'ndraws'
#> instead.
pred
#> Predicted values:
#> 
#>   Row Response    Predicted
#> 1   1        4 8.581724e-05
#> 2   1        6 7.944995e-01
#> 3   1        8 2.054146e-01
#> 
#> NOTE: Confidence intervals, if available, are stored as attributes and can be accessed using `as.data.frame()` on this output.
```

<sup>Created on 2022-03-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Same with iterations specified to a number, + a warning about replacing internally `nsamples` with `ndraws`

**Comment by strengejacke** [comment]
> Though our argument is named data, I suspect some users might try using newdata if they try to simply replace the functions with datawizard. We should probably run a check on the ellipsis and see whether there is an argument called newdata that would supersedes a null data one (with or without out a warning).

We already did that, and copied that value to `data`, but since `...` were passed down to `predict()`, and we already set `newdata = data`, we had the `newdata` argument twice. I'll try for `get_predicted.brmsfit()` to change the call to predict using `do.call()` with an argument list.

**Comment by strengejacke** [comment]
> It says in the docs that iterations=NULL returns all iterations, but here it returns the summary

I'm not sure this ever worked. We have `as.data.frame(keep_iterations = TRUE)` instead. However, this does not return iterations for models with multiple response levels. But this must be something you know better.

**Comment by strengejacke** [comment]
Anything we need to do here? Or can this be closed?

**Comment by DominiqueMakowski** [comment]
Can be closed :)
