### ISSUE TITLE
`get_data()` with returns transformed regressors instead of original data

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#526]
When regressors are transformed in the model formula, `get_data()` appears to return transformed variables rather than the original data:

``` r
library(marginaleffects)

set.seed(1023)
x <- rnorm(1000, sd = 4)
y <- cos(x) + rnorm(1000)
dat <- data.frame(x, y)
mod1 <- lm(y ~ x, data = dat)
mod2 <- lm(y ~ cos(x), data = dat)

insight::get_data(mod1) |> head(2)
    ##           y         x
    ## 1 -3.404049 -2.706045
    ## 2  1.874833  6.566905

insight::get_data(mod2) |> head(2)
    ##           y          x
    ## 1 -3.404049 -0.9066393
    ## 2  1.874833  0.9600210
```

I expected both commands to return the original data:

``` r
eval(mod1$call$data) |> head(2)
    ##           x         y
    ## 1 -2.706045 -3.404049
    ## 2  6.566905  1.874833

eval(mod2$call$data) |> head(2)
    ##           x         y
    ## 1 -2.706045 -3.404049
    ## 2  6.566905  1.874833
```

Is this a bug or the expected behavior?

**Comment by strengejacke** [comment]
Looks like a bug.

**Comment by strengejacke** [comment]
What are the inverse functions of cos/sin etc.?

**Comment by vincentarelbundock** [comment]
Unfortunately, `sin()` et al. are not a one-to-one functions: https://stackoverflow.com/a/63307339/342331

**Comment by bwiernik** [comment]
In this situation, returning the first value in the [0, 2 * pi] interval for that sin/cos seems reasonable

**Comment by bwiernik** [comment]
So the inverse functions are asin() and acos()

**Comment by vincentarelbundock** [comment]
> In this situation, returning the first value in the \[0, 2 \* pi\] interval for that sin/cos seems reasonable

I think I’ll disagree, since this wouldn’t give me the original dataset, and the documentation for `get_data` currently says:

> This functions tries to get the data that was used to fit the model and returns it as data frame.

For what it’s worth, my use-case is that I want to make predictions on the original data. Currently, I get predictions for the wrong values of `x`:

``` r
library(marginaleffects)

x <- seq(-10, 10, length.out = 1000)
y <- sin(x) + rnorm(1000, sd = 4)
dat <- data.frame(x, y)
mod <- lm(y ~ sin(x))

predictions(mod)$predicted |> head()
    ## [1] 0.6751981 0.6579091 0.6402298 0.6221663 0.6037253 0.5849141

predict(mod, newdata = dat) |> head()
    ##         1         2         3         4         5         6 
    ## 0.7066402 0.6865359 0.6661804 0.6455819 0.6247485 0.6036887

**Comment by strengejacke** [comment]
> So the inverse functions are asin() and acos()

I thought that, too, but it doesn't seem like that:

``` r
set.seed(1023)
x <- rnorm(1000, sd = 4)
y <- cos(x) + rnorm(1000)
dat <- data.frame(x, y)

dat$x |> head()
#> [1] -2.706045  6.566905 -0.947961  3.831814 -3.405772 -1.437285
cx <- cos(dat$x)
acos(cx) |> head()
#> [1] 2.7060455 0.2837193 0.9479610 2.4513711 2.8774135 1.4372849
```

<sup>Created on 2022-03-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
Again, such a function *cannot* exist because sine is cyclical and not a one-to-one function. It would be possible to backtransform `x` over some specific ranges, but not for arbitrary values, because there is an infinity of solutions.

**Comment by bwiernik** [comment]
asin(x) still yields a dataset that can reproduce the fitted model. With a non-monotonic transformation, that's the best we can do, and it's better than the status quo. We can add a note to the documentation about non-monotonic transformations

**Comment by strengejacke** [comment]
I now recovered data from environment. This may not perfectly work in some rare occasions, but it returns the original data. Using `acos()` would be more safe, but may not return the exact values from the original data.

**Comment by vincentarelbundock** [comment]
Got it.

Out of curiosity, what was the original rationale for not making the default something simple like `eval(model$call$data)`?

For instance, the first few times I was surprised to notice that `get_data()` returned data *after* list wise deletion, and that some variables (not included in the model) were missing.

**Comment by vincentarelbundock** [comment]
Sorry, posted before seeing @strengejacke 's description of the fix, which I like.

**Comment by strengejacke** [comment]
> eval(model$call$data)

This is not available for "quite a lot" of model classes, and for those cases, the idea was to have an as stable as possible function to recover the data in a different way. Furthermore, when you save a model object, but not the data, the only place where the data is available after reloading your saved model is the model frame. And finally, the data in the environment might be modified after fitting the model, so it's no longer the data set that was used to fit the model.

**Comment by strengejacke** [comment]
The basic idea of `get_data()` is to have a `model.frame()` containing the original data .

**Comment by vincentarelbundock** [comment]
Makes sense. Thanks!
