### ISSUE TITLE
return values for aovlist

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#53]
@DominiqueMakowski Currently, _insight_ returns the elements `$within` and `$between` for `aovlist`-objects (i.e. anova with error term).

I don't work with `aov()`, so I', not sure if this makes sense or not, and it "breaks" current behaviour, where we return `$conditional`, `$random` etc. But from my perspective, these information from `aovlist` (within/between) seems useful, and I think we can make an execption with the names of the returned elements here.

**Comment by DominiqueMakowski** [comment]
I don't work with it either tbh, but yes, I think it's ok to leave the within and between terms. Anyway, functions that want to work with anovas will need to treat them as a special case (I am thinking about `report`)
