### ISSUE TITLE
Remove `model_info$model_terms` list

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/insight#538]
We don't use `model_info$model_terms` list anywhere outside _insight_, so should be safe to get rid of:

https://github.com/search?q=org%3Aeasystats+model_terms&type=code

_Originally posted by @IndrajeetPatil in https://github.com/easystats/parameters/issues/677#issuecomment-1070951871_

**Comment by strengejacke** [comment]
ok, fingers crossed...

**Comment by strengejacke** [comment]
(https://github.com/easystats/insight/commit/f41b0641f34baad171584ef42b759701ecbab13c)
