### ISSUE TITLE
get_data.lm when data is modified in environment fails with poly()

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#541]
Stumbled on an edgecase with poly terms when data is modified in the environment:

``` r
data <- iris
m <- lm(Petal.Length ~ poly(Sepal.Length), data = data)

data <- mtcars
insight::get_data(m)
#> Error in `[.data.frame`(md, , needed.vars, drop = FALSE): undefined columns selected
```

<sup>Created on 2022-03-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bwiernik** [comment]
This should fail even without poly()

Not sure there's anything we can do here except fail more gracefully when the model doesn't store the data and we need to retrieve from the environment

**Comment by DominiqueMakowski** [comment]
it does work without 

``` r
data <- iris
m <- lm(Petal.Length ~ Sepal.Length * Petal.Width, data = data)

data <- mtcars
head(insight::get_data(m))
#>   Petal.Length Sepal.Length Petal.Width
#> 1          1.4          5.1         0.2
#> 2          1.4          4.9         0.2
#> 3          1.3          4.7         0.2
#> 4          1.5          4.6         0.2
#> 5          1.4          5.0         0.2
#> 6          1.7          5.4         0.4
```

<sup>Created on 2022-03-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


> Not sure there's anything we can do

Maybe we should find a way - in case the data is retrieved from the environment - to assess the likelihood that it's the right one

Perhaps by running like a fuzzy matching on the names of the retrieved data and the names in the model-frame; like this even if the names in the parameters are different it should still partially match, but if there is like 0 correspondence, then warn `"we tried to retrieve the data used to fit the model from the environment but it seems different. Make sure you didn't modify in in between!"` or something
