### ISSUE TITLE
Use `getElement()`

### ISSUE THREAD

**Issue by mattansb** [easystats/insight#545]
For example:

Instead of:

```R
cl <- tryCatch({
  x$call
}, error = function(x) {
  NULL
})

if (is.null(cl)) {
  cl <- tryCatch({
    x@call
  }, error = function(x) {
    NULL
  })
}
```

We can 

```R
cl <- getElement(x, "call")
```

**Comment by IndrajeetPatil** [comment]
This exits in base-R?! 🤯

**Comment by strengejacke** [comment]
After <random number from 1 to 100> years of R programming, I still find out new things or learn new base R functions ;-)

**Comment by IndrajeetPatil** [comment]
Someone should start _base-R function a day_ Twitter account 🤗

**Comment by strengejacke** [comment]
This is something for your great twitter comeback in 2024 ;-)
