### ISSUE TITLE
find_parameters() for Stan-models should remove more parameters by default

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#55]
We could think about removing some more parameters by default for Stan-models:

```r
grep("^(prior_|sd_|cor_|lp__|smooth_sd)", x$Parameter)
```

**Comment by DominiqueMakowski** [comment]
Related to #49

**Comment by strengejacke** [comment]
Should we return by default _all_ parameters, or already provide a "default" pattern with some filtering (like shown in my initial post)?

**Comment by DominiqueMakowski** [comment]
I agree with some filtering done by default, as you did it in the first place
