### ISSUE TITLE
`find_variables()` and weights variables

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#550]
Would it be possible for `find_variables()` to extract the weights variable? For example, I would like to know that `carb` is used as weights:

``` r
library(insight)

mod <- glm(
    am ~ mpg * cyl,
    data = mtcars,
    family = binomial(link = "logit"),
    weights = carb)

find_variables(mod)
#> $response
#> [1] "am"
#> 
#> $conditional
#> [1] "mpg" "cyl"
```

Do people ever fit models with something like `weights=1/carb`? If so, that could be tricky…

**Comment by vincentarelbundock** [comment]
Ha! Still discovering new stuff about this *rich* package. Thanks!

**Comment by bwiernik** [comment]
> Do people ever fit models with something like weights=1/carb? If so, that could be tricky…

Yes, for something like `1 / SE` or `1 / vi` in measurement error models, meta-analysis, or ad-hoc WLS solutions to heteroskedasticity (weighting by the 1 / residual^2 from an OLS model).

**Comment by strengejacke** [comment]
> Ha! Still discovering new stuff about this _rich_ package. Thanks!

Next time, please check [this list](https://easystats.github.io/easystats/articles/list_of_functions.html) before asking for functions 😁
