### ISSUE TITLE
`get_varcov.plm` produces unexpected results

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#556]
The results produced by `get_varcov` and `stats::vcov` are very different for `plm` package models (the intercept is the same, but not others):

``` r
library(plm)
library(insight)
data("Grunfeld", package = "plm")
mod <- plm(inv ~ value * capital, data = Grunfeld,
           model = "random", effect = "individual")

get_varcov(mod)
#>                 (Intercept)         value       capital value:capital
#> (Intercept)    9.768005e+02 -7.627061e-02 -1.753418e-01  4.957749e-05
#> value         -7.627061e-02  1.116540e-05  1.369105e-05 -3.871113e-09
#> capital       -1.753418e-01  1.369105e-05  3.929835e-05 -8.899468e-09
#> value:capital  4.957749e-05 -3.871113e-09 -8.899468e-09  9.768006e-06

stats::vcov(mod)
#>                 (Intercept)         value       capital value:capital
#> (Intercept)    9.768005e+02 -1.044335e-01 -1.959250e-01  4.957747e-05
#> value         -1.044335e-01  9.558394e-05  4.697734e-05 -2.428482e-08
#> capital       -1.959250e-01  4.697734e-05  8.037675e-04 -1.562930e-07
#> value:capital  4.957747e-05 -2.428482e-08 -1.562930e-07  4.038625e-11
```

**Comment by vincentarelbundock** [comment]
I see now that the discrepancy arises because we apply `Matrix::nearPD()` via `.fix_negative_matrix()`. Based on my test suite, it looks like this function is being called *a lot* for many different kinds of models.

Out of curiosity, what is our rationale? Are we sure that this test is not too liberal? (I have very little expertise here.)

**Comment by vincentarelbundock** [comment]
I'm asking because my intuition is that if a package developer -- who presumably knows his models better than most people -- decides to implement a `varcov()` method a certain way, we should probably return that output unless we have *very* strong reasons to believe this output is completely inappropriate. I think a good rule of thumb would be that, in most cases, modifying numerical results should require an explicit action by the user and should not happen silently.

**Comment by vincentarelbundock** [comment]
FWIW, the `insight` test does not agree with the `matrixcalc` package:

``` r
library(plm)
data("Grunfeld", package = "plm")
mod <- plm(inv ~ value * capital, data = Grunfeld,
           model = "random", effect = "individual")

V <- stats::vcov(mod)

insight:::.is_negativ_matrix(V)
#> [1] TRUE

matrixcalc::is.positive.semi.definite(V)
#> [1] TRUE

matrixcalc::is.negative.definite(V)
#> [1] FALSE

matrixcalc::is.negative.semi.definite(V)
#> [1] FALSE
```

**Comment by strengejacke** [comment]
The code slightly differs between matrixcalc and insight. I'm not sure where I have the code from to check if a matrix is negativ definite, I think I adopted it from somewhere. I can check this.

If I'm right, negative definite matrices don't allow to compute SE, so in this particular case, I thought correcting the matrix would be beneficial, to return SE values where it else would fail. Would you say changing this behaviour would be better?

**Comment by strengejacke** [comment]
I tweaked the tolerance and changes the code, which is now:

```r
        eigenvalues <- eigen(x, only.values = TRUE)$values
        eigenvalues[abs(eigenvalues) < pd_tolerance] <- 0
        any(eigenvalues < 0)
```

Before, the last line was ` any(eigenvalues <= 0)`, which included zero, but probably shouldn't.

But I'm not sure if the function from matrixcalc is working as expected. The code is:

```r
    if ( any( eigenvalues >= 0 ) ) {
        return( FALSE )
    }
```

which would also return `FALSE` if one or more values are negativ - but I think this should actually return `TRUE` if _any_ value is negative.

**Comment by strengejacke** [comment]
``` r
library(plm)
data("Grunfeld", package = "plm")
mod <- plm(inv ~ value * capital, data = Grunfeld,
           model = "random", effect = "individual")

V <- stats::vcov(mod)

insight:::.is_negativ_matrix(V)
#> [1] FALSE

# always skip test for negative definite matrix
insight:::.is_negativ_matrix(V, pd_tolerance = NULL)
#> [1] FALSE


matrixcalc::is.positive.semi.definite(V)
#> [1] TRUE

matrixcalc::is.negative.definite(V)
#> [1] FALSE

matrixcalc::is.negative.semi.definite(V)
#> [1] FALSE
```

<sup>Created on 2022-04-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
Thanks for looking into this!

> Before, the last line was ` any(eigenvalues <= 0)`, which included zero, but probably shouldn't.

Yep, I think `egenvalues<0` is correct. I had 6 model types where this caused problems in `marginaleffects`, and things seem fine now.

How about raising a warning when `.fix_negative_matrix()` is called? I'm not a big fan of changing numerical results on the fly silently...

**Comment by strengejacke** [comment]
I added a message that is printed when a negative definite matrix is corrected, and provided some more details in the docs. Let me know if this is sufficient, or feel free to reopen.

**Comment by vincentarelbundock** [comment]
Yeah, this looks perfect. Thanks so much!

**Comment by bwiernik** [comment]
An eigenvalue of 0 means that the matrix is only positive _semi_definite, not positive definite. That means the model is somewhat ill-conditioned, but it's not invalid. I agree that we should smooth but default (maybe add an argument to skip that) and give a message when smoothing is done.
