### ISSUE TITLE
`get_predicted()`: nothing instead of warning when Delta method doesn't work

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#558]
In some cases, we are unable to transform the predicted values standard errors from the link scale to the scale that the user requested, most often because we cannot `deriv()` the inverse link function. In those cases, we issue a warning and return the standard error on the link scale instead of the scale defined in `predict`. See here:

https://github.com/easystats/insight/blob/master/R/get_predicted.R#L481

Warnings are useful, but they can be easy to miss. I think that in such cases we should not return any estimates of the standard error at all, since (a) they don't match the scale of the predicted values and (b) the scale of the standard error directly contradicts what the user requested with the `predict` argument.

Optionally, we could print an informative message saying that standard errors and other uncertainy estimates may be available by setting `predict="link"`.

**Comment by vincentarelbundock** [comment]
I can implement this. Just let me know if you agree with the general concept.

**Comment by strengejacke** [comment]
I'd say yes. What do @bwiernik and @DominiqueMakowski say? You were more involved in the initial drafting of this function.

**Comment by bwiernik** [comment]
We should always be able to return a CI because we compute the CI on the link scale and then inverse link transform the bounds (right?). I agree that we should return NA for the SE in case deriv() fails.
