### ISSUE TITLE
Coulour_tools.R in insight

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#57]
BayestestR, report and I believe other packages might want to use these colouring tools. As such, instead of repeating them in all packages maybe we should add them here...?

**Comment by strengejacke** [comment]
Would be _a bit_ out of scope, but since it's a small helper-function, I would say it's ok to put it in here. Especially, since _insight_ is the base for all other packages.

**Comment by DominiqueMakowski** [comment]
Yes, it is definitely out of scope 😅 but indeed, it's mainly for convenience purposes

**Comment by strengejacke** [comment]
color or colo*u*r?
I would add a method called `print_color()` that already uses `cat()`:

```r
print_color <- function(color, text) {
  cat(.colour(colour = color, x = text))
}
```

**Comment by DominiqueMakowski** [comment]
Do we want to sound more british or american? 😃 

the `print_colo(u)r` could be very convenient!

**Comment by strengejacke** [comment]
I'll add an alias, so we have both.

**Comment by DominiqueMakowski** [comment]
ggplot style 😉
