### ISSUE TITLE
`get_predicted.gam` and the `exclude` argument.

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#575]
@strengejacke I see that you fixed some things related to GAM predictions recently. I don’t know exactly what happens, but I’m not sure how to pass the `exclude` argument through to `predict()` to replicate the results of the default method:

``` r
library(mgcv)
library(insight)

dat <- gamSim(1, n = 400, dist = "poisson", scale = .25)
#> Gu & Wahba 4 term additive model
b4 <- gam(
    y ~ s(x0) + s(x1) + s(x2) + s(x3),
    family = poisson,
    data = dat,
    method = "GACV.Cp",
    scale = -1)

# exclude argument should be pushed through ...
p1 <- predict(b4, type = "response", exclude = "s(x1)")
p2 <- get_predicted(b4, predict = "expectation", exclude = "s(x1)", include_smooth = TRUE)
p3 <- get_predicted(b4, predict = "expectation", exclude = "s(x1)", include_smooth = FALSE)
head(p1)
#>         1         2         3         4         5         6 
#> 11.235492  8.052003  9.662359  5.250049  3.213511  4.837699
head(p2)
#>         1         2         3         4         5         6 
#>  4.695356  7.662066 12.540029  4.397427  4.410961  4.725942
head(p3)
#>        1        2        3        4        5        6 
#> 6.220924 6.220924 6.220924 6.220924 6.220924 6.220924

# exclude argument should be pushed through ...
p1 <- predict(b4, type = "link", exclude = "s(x1)")
p2 <- get_predicted(b4, predict = "link", exclude = "s(x1)", include_smooth = TRUE)
p3 <- get_predicted(b4, predict = "link", exclude = "s(x1)", include_smooth = FALSE)
head(p1)
#>        1        2        3        4        5        6 
#> 2.419078 2.085921 2.268238 1.658237 1.167364 1.576439
head(p2)
#>        1        2        3        4        5        6 
#> 1.546574 2.036282 2.528926 1.481020 1.484093 1.553067
head(p3)
#>        1        2        3        4        5        6 
#> 1.827918 1.827918 1.827918 1.827918 1.827918 1.827918
```

Things work OK without the `exclude` paramter:

``` r

p1 <- predict(b4, type = "response")
p2 <- get_predicted(b4, predict = "expectation")
p3 <- predict(b4, type = "link")
p4 <- get_predicted(b4, predict = "link")
head(p1)
#>         1         2         3         4         5         6 
#>  7.559488  8.840597 17.362548  3.308216  2.031163  3.276114
head(p2)
#>         1         2         3         4         5         6 
#>  7.559488  8.840597 17.362548  3.308216  2.031163  3.276114
head(p3)
#>         1         2         3         4         5         6 
#> 2.0228035 2.1793544 2.8543155 1.1964090 0.7086087 1.1866579
head(p4)
#>         1         2         3         4         5         6 
#> 2.0228035 2.1793544 2.8543155 1.1964090 0.7086087 1.1866579
```

<sup>Created on 2022-06-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Aariq** [comment]
It's also not clear from the documentation whether `...` is supposed to get passed to `predict.gam()` or not.

This is the description for `...` for **both** `get_predicted()` **and** `get_predicted_ci()`

... | Other argument to be passed, for instance to get_predicted_ci().
-- | --

**Comment by vincentarelbundock** [comment]
> It's also not clear from the documentation whether `...` is supposed to get passed to `predict.gam()` or not.
> 
> This is the description for `...` for **both** `get_predicted()` **and** `get_predicted_ci()`
> ... 	Other argument to be passed, for instance to get_predicted_ci().

I believe the intent is to pass it to *both* and agree this should be clarified.

**Comment by strengejacke** [comment]
I'm not sure why this isn't working. When I debug the code, `exclude` is obviously passed to `predict()`, but the result from `do.call(stats::predict, compact_list(predict_args))` differs compared to using `predict()` with manually arguments entered (and all are identical to `predict_args`). This shouldn't be the case.

**Comment by Aariq** [comment]
See relevant code here: https://github.com/vincentarelbundock/marginaleffects/issues/365

I think the dots are missing in that last line.

**Comment by vincentarelbundock** [comment]
@strengejacke The problem was this:

**Comment by vincentarelbundock** [comment]
The problem was a small typo in this chunk:

```r 
   predict_args <- list(x, newdata = data, type = args$type, re.form = args$re.form,
                         unconditional = FALSE, se.fit = TRUE, dot_args)
```

To concatenate the lists we need:

```r
predict_args <- list(x, newdata = data, type = args$type, re.form = args$re.form,
                         unconditional = FALSE, se.fit = TRUE)
    predict_args <- c(predict_args, dot_args)
```

I think this should work again with https://github.com/easystats/insight/commit/a4442622bb9fd0a4ed0aae48c301ac81137a648c
