### ISSUE TITLE
`get_data` should not recover data from global environment

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#576]
Sometimes, there may be no other option, but in general it is unsafe to recover the dataset from the global environment. For example, a user may assign a new data frame to the same variable name after fitting the model. `get_data` would then recover the wrong data.

`get_data.default` calls `model.frame` before `.recover_from_environment`, so that's probably fine: https://github.com/easystats/insight/blob/master/R/get_data.R#L54

However, there are model classes where `.recover_from_environment` is the first and only option. We should review those object types to see if the data is stored in the object for us to retrieve directly.

**Comment by bwiernik** [comment]
Agreed

**Comment by strengejacke** [comment]
I think this is already the case, but there might be some cases we have missed.

**Comment by vincentarelbundock** [comment]
> I think this is already the case, but there might be some cases we have missed.

That's good news, thanks!

I'll investigate a bit and see if I find some cases.

**Comment by bwiernik** [comment]
Let's leave a comment in the code where environment-recovery is needed to alert future folks thinking the same thing as @vincentarelbundock

**Comment by vincentarelbundock** [comment]
I checked 3 model types and, indeed, they did not store the original data in the model object. I left comments in the code for those: 574aa7b7

Unfortunately, I don't have time to check all the model objects, but at least now there are a few comments and more people are aware of the situation. 

Thanks!

Closing.

**Comment by bwiernik** [comment]
Thanks!
