### ISSUE TITLE
Add codecov back?

### ISSUE THREAD

**Issue by etiennebacher** [easystats/insight#577]
Apparently, `insight` is the only easystats package not covered by codecov (see [here](https://app.codecov.io/gh/easystats)). I see that it was available before but removed in https://github.com/easystats/insight/commit/1d0ccc1e048d5007ff4ce4e8bbf06b161399d75a. Is it possible to put it back to have more info about the package test coverage?

**Comment by strengejacke** [comment]
I think there were technical issues so that codecov always failed, maybe GH actions are more robust now or it's better working now - feel free to add it back! (I'm not really that familiar with codecov and GH actions)

**Comment by IndrajeetPatil** [comment]
Closed in #582
