### ISSUE TITLE
Change  `format_bf()` default to `exact = TRUE`

### ISSUE THREAD

**Issue by mattansb** [easystats/insight#589]
Since BFs are translational, BF<sub>A vs B</sub> / BF<sub>C vs B</sub> = BF<sub>A vs C</sub>

However, with the current default behavior of `format_bf(..., exact = FALSE)` information is lost and this property of BFs cannot be used.
(I just saw “BF \> 1000” in a paper along with other `{report}` text, so I’m tracing this back to here.)

``` r
library(insight)
library(bayestestR)

m1 <- lm(mpg ~ 1, mtcars)
m2 <- lm(mpg ~ hp, mtcars)
m3 <- lm(mpg ~ cyl, mtcars)

Bfs <- bayesfactor_models(m2, m3, denominator = m1)
```

Can’t infer that `m3` is supported over `m2`

``` r
format_bf(exp(Bfs$log_BF))
#> [1] "BF > 1000" "BF > 1000" "BF = 1.00"
```

Can infer that `m3` is supported over `m2`

``` r
format_bf(exp(Bfs$log_BF), exact = TRUE)
#> [1] "BF = 4.54e+05" "BF = 1.77e+08" "BF = 1.00"
```

<sup>Created on 2022-07-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
We should set `exact = TRUE` in the related packages, not change the default here, at least not this release cycle where it will break other packages. We'll probably have a very close deadline to submit _insight_ after the CRAN hiatus, and I'm not sure if we have too much time pressure waiting for reverse dep checks and explain that failing tests are expected...

**Comment by strengejacke** [comment]
And for _bayestestR_, the default is already `TRUE` in all instances.

**Comment by strengejacke** [comment]
@mattansb ? Any objections?

**Comment by mattansb** [comment]
Nope, sounds good to me.

**Comment by mattansb** [comment]
@strengejacke Can I change it here too?

https://github.com/easystats/insight/blob/d106130e4b37a7928fbe680e1448a6875d237ba3/R/format_table.R#L499

(This is the last place in all of easystats to change this...)

**Comment by strengejacke** [comment]
Good question. We could either pass dots, add the `exact` argument, or set it to exact by default.
