### ISSUE TITLE
Unexpected line breaks with `insight::format_message`

### ISSUE THREAD

**Issue by rempsyc** [easystats/insight#610]
In the context of my easystats/performance#443 PR, I’ve experienced a difficulty using `insight::format_message`, so I am moving the discussion here.

I initially wrapped the coloured messages in `insight::format_message` since they can get pretty long with many methods. However, it seems like it is giving strange line break behaviours like jumping random line when less than half of my console is used for the total printed string line and when my console is more than 3/4 of my screen. For example,

``` r
library(insight)
cat(insight::format_message("x outliers detected: cases 1, 2, 3.
- Based on the following methods and thresholds: A, B, C.
- For variables:", paste(names(mtcars[1]), collapse = ", ")))
#> x outliers detected: cases 1, 2, 3.
#> - Based on the following methods and
#>   thresholds: A, B, C.
#> - For variables:
#>   mpg
```
![format_message](https://user-images.githubusercontent.com/13123390/184502042-d5e027f8-3987-4a37-b7f1-86ca724f266e.png)

Whereas I would have expected to see all on their own lines:

``` r
cat(c("x outliers detected: cases 1, 2, 3.
- Based on the following methods and thresholds: A, B, C.
- For variables:", paste(names(mtcars[1]), collapse = ", ")))
#> x outliers detected: cases 1, 2, 3.
#> - Based on the following methods and thresholds: A, B, C.
#> - For variables: mpg
```
![format_message_2](https://user-images.githubusercontent.com/13123390/184502051-0029ada7-4e30-465c-a3f4-a0975099ee84.png)

Documentation explains that

> Line length is adjusted to maximum length of the console, if the width can be accessed.

So I understand that it shouldn’t make a line break so early, but that perhaps it does because it cannot access the width? I see that the default line_length option is:

``` r
0.9 * options()$width
#> [1] 72
```

So 88 (reprex differs on this), which should be perfect for my needs! Let’s try it. Same result. So the default is working, but maybe it’s the 0.9 that I don’t like?

``` r
cat(insight::format_message("x outliers detected: cases 1, 2, 3.
- Based on the following methods and thresholds: A, B, C.
- For variables: ", paste(names(mtcars[1]), collapse = ", "),
                            line_length = options()$width))
#> x outliers detected: cases 1, 2, 3.
#> - Based on the following methods and
#>   thresholds: A, B, C.
#> - For variables: 
#>   mpg
```
![format_message_3](https://user-images.githubusercontent.com/13123390/184502057-389076c4-5b63-4ec1-ae10-d05f5388d969.png)

So seems better with full width, however now the second line after the dash has a line break… same for content after a colon. Let’s try to jack it.

``` r
cat(insight::format_message("x outliers detected: cases 1, 2, 3.
- Based on the following methods and thresholds: A, B, C.
- For variables: ", paste(names(mtcars[1]), collapse = ", "),
                            line_length = 100))
#> x outliers detected: cases 1, 2, 3.
#> - Based on the following methods and thresholds: A, B, C.
#> - For
#>   variables: 
#>   mpg
```
![format_message_4](https://user-images.githubusercontent.com/13123390/184502060-8cc061e3-be15-4b08-8770-9b94d2465f08.png)

Even with width supposedly larger than my console, the second sentence is being separated on all different lines.

While writing this I also realized from the example that
> Further strings that will be concatenated as indented new lines.

And that therefore to avoid this, they should be collapsed beforehand, as such (this takes care of the "mpg" after the colon):

``` r
cat(insight::format_message(paste0("x outliers detected: cases 1, 2, 3.
- Based on the following methods and thresholds: A, B, C.
- For variables: ", paste(names(mtcars[1]), collapse = ", ")),
                            line_length = 100))
#> x outliers detected: cases 1, 2, 3.
#> - Based on the following methods and thresholds: A, B, C.
#> - For
#>   variables: mpg
```
![format_message_5](https://user-images.githubusercontent.com/13123390/184502064-0ab72c26-5ec5-4748-a7f1-e8991123dbaa.png)

That’s getting better! But second line somehow still breaking.

``` r
sessionInfo()
#> R version 4.2.1 (2022-06-23 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19044)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_Canada.utf8  LC_CTYPE=English_Canada.utf8   
#> [3] LC_MONETARY=English_Canada.utf8 LC_NUMERIC=C                   
#> [5] LC_TIME=English_Canada.utf8    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] insight_0.18.2 reprex_2.0.1  
#> 
#> loaded via a namespace (and not attached):
#>  [1] rstudioapi_0.13   knitr_1.39        magrittr_2.0.3    R.cache_0.16.0   
#>  [5] rlang_1.0.4       fastmap_1.1.0     fansi_1.0.3       stringr_1.4.0    
#>  [9] styler_1.7.0      highr_0.9         tools_4.2.1       xfun_0.31        
#> [13] R.oo_1.25.0       utf8_1.2.2        cli_3.3.0         clipr_0.8.0      
#> [17] withr_2.5.0       htmltools_0.5.3   yaml_2.3.5        digest_0.6.29    
#> [21] tibble_3.1.8      lifecycle_1.0.1   purrr_0.3.4       R.utils_2.12.0   
#> [25] vctrs_0.4.1       fs_1.5.2          glue_1.6.2        evaluate_0.15    
#> [29] rmarkdown_2.14    stringi_1.7.8     compiler_4.2.1    pillar_1.8.0     
#> [33] R.methodsS3_1.8.2 pkgconfig_2.0.3
```

<sup>Created on 2022-08-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rempsyc** [comment]
Perhaps a workaround is to make repeated calls to `insight::format_message`, along pasting strings that should not be on different line breaks, so the following produces the expected result:

``` r
cat(insight::format_message(
  "x outliers detected: cases 1, 2, 3 \n"),
insight::format_message(
  "- Based on the following methods and thresholds: A, B, C. \n"),
insight::format_message(
  paste0("- For variables: ", paste(names(mtcars[1]), collapse = ", "))))
#> x outliers detected: cases 1, 2, 3 
#>  - Based on the following methods and thresholds: A, B, C. 
#>  - For variables: mpg
```
![format_message_6](https://user-images.githubusercontent.com/13123390/184502716-66596cf5-1dde-4033-925b-3e6188b0d33d.png)

<sup>Created on 2022-08-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
You create just one string, and for this string, line breaks are inserted. Since the string already contains line break from construction, you see this weird behaviour:

``` r
s <- "x outliers detected: cases 1, 2, 3.
- Based on the following methods and thresholds: A, B, C.
- For variables:"

s
#> [1] "x outliers detected: cases 1, 2, 3.\n- Based on the following methods and thresholds: A, B, C.\n- For variables:"
```

<sup>Created on 2022-08-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

If you want multiple lines, just add each string comma separated:

``` r
cat(insight::format_message(
  "x outliers detected: cases 1, 2, 3.",
  "- Based on the following methods and thresholds: A, B, C.",
  sprintf("- For variables: %s", paste(names(mtcars[1:3]), collapse = ", "))))
#> x outliers detected: cases 1, 2, 3.
#>   - Based on the following methods and thresholds: A, B, C.
#>   - For variables: mpg, cyl, disp
```

<sup>Created on 2022-08-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
For subsequent lines, there's an automatically indention of two whitespace. We could add an argument to change this behaviour, e.g. `indention = "  "`, and users can use any string for indention.

**Comment by strengejacke** [comment]
See latest commit:

``` r
message(insight::format_message(
  "x outliers detected: cases 1, 2, 3.",
  "- Based on the following methods and thresholds: A, B, C.",
  sprintf("- For variables: %s", paste(names(mtcars[1:3]), collapse = ", "))))
#> x outliers detected: cases 1, 2, 3.
#>   - Based on the following methods and thresholds: A, B, C.
#>   - For variables: mpg, cyl, disp

message(insight::format_message(
  "x outliers detected: cases 1, 2, 3.",
  "- Based on the following methods and thresholds: A, B, C.",
  sprintf("- For variables: %s", paste(names(mtcars[1:3]), collapse = ", ")),
  indention = ""
))
#> x outliers detected: cases 1, 2, 3.
#> - Based on the following methods and thresholds: A, B, C.
#> - For variables: mpg, cyl, disp
```

<sup>Created on 2022-08-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rempsyc** [comment]
Ah... of course, that makes sense now, thanks! The transition to the easyverse is not always straightforward hehe, though I'm slowly getting there. I will adapt the other PR accordingly then. And nice for the optional argument to specify the indentation! Does this mean we can close this issue?

Also, I saw that you are using `sprintf` instead of `paste`. Is there a strong reason I should attempt to prioritize this as well, or is it just personal preference? Because I find paste easier to use (and a bit shorter), since you have to worry about object types (sorta) but maybe it's just because I'm still relatively inexperienced.

**Comment by strengejacke** [comment]
`sprintf()` was just in case of multiple values, where `paste()` will repeat the complete string:

``` r
sprintf("- For variables: %s", paste(names(mtcars[1:3]), collapse = ", "))
#> [1] "- For variables: mpg, cyl, disp"

paste("- For variables:", names(mtcars[1:3]), collapse = ", ")
#> [1] "- For variables: mpg, - For variables: cyl, - For variables: disp"
```

<sup>Created on 2022-08-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
Yes, I think we can close this.

**Comment by rempsyc** [comment]
What about naming the argument `indent`? Because I thought it should be `indentation` rather than `indention`, which looks like a typo to me, but English is not my first language, and it might be a regional/cultural difference. Also, it is shorter.

**Comment by bwiernik** [comment]
Yes, `indent` is better. intention isn't an English word
