### ISSUE TITLE
Formulas in docs

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#62]
@DominiqueMakowski 

No real issue, just wanted to show that in the course of providing statistical details for the docs of `get_variance()`, I played a bit around with formatted equation in the docs and PDF. Here's the result:

![image](https://user-images.githubusercontent.com/26301769/54599516-16f21300-4a3b-11e9-9740-473a46956fba.png)

and...

![image](https://user-images.githubusercontent.com/26301769/54599580-35580e80-4a3b-11e9-8666-09897109cedf.png)

🥂

**Comment by DominiqueMakowski** [comment]
That's awesome!! (Although I'me quite bad with equations and mathematical symbols), but it looks absolutely great (and is very informative) ☺️
