### ISSUE TITLE
this currently doesn't work...

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#621]
https://github.com/easystats/insight/blob/7d48161bc76870f65d88372eee74b61f8b7b929c/R/get_predicted_se.R#L51

**Comment by strengejacke** [comment]
(just testing Todo Tree extension)

**Comment by strengejacke** [comment]
Nice, the extension also show a light-bulb into the source code editor:

![image](https://user-images.githubusercontent.com/26301769/187070450-0242b92b-5076-4072-ac80-f69305cdae2e.png)

Clicking on it creates this issue here, and adds the issue number into the source code:

![image](https://user-images.githubusercontent.com/26301769/187070486-a1ddffee-64c2-4218-85b4-5cf1954a3c57.png)

**Comment by strengejacke** [comment]
<sup><i>(anyone still using RStudio?)</i></sup>
![image](https://user-images.githubusercontent.com/26301769/187070563-da2de05e-14ed-49fa-b45b-c71286224721.png)

**Comment by strengejacke** [comment]
Nice overview in the sidebar:

![image](https://user-images.githubusercontent.com/26301769/187070620-c712b857-1bb9-4fcc-8beb-f519df70ffed.png)

grouped by tags or files:

![image](https://user-images.githubusercontent.com/26301769/187070633-e242dd50-c191-4fac-83d1-64e8c354b28c.png)

**Comment by vincentarelbundock** [comment]
While we're here, did we ever check if repeating the standard errors works in `multinom` models? I vaguely remember that we checked for `polr`, but wonder for the others:

https://github.com/easystats/insight/blob/main/R/get_predicted_se.R#L110)](https://github.com/easystats/insight/blob/main/R/get_predicted_se.R#L110

**Comment by strengejacke** [comment]
Yeah, I remember we had some discussion where this approach did not work as expected - but I think, we just removed computation of SE/CI in that case?

**Comment by strengejacke** [comment]
hm, we added the "correct" way to clm: https://github.com/easystats/insight/commit/dfcfde30673415667f567063f18f48672359dc4a

Not sure about multinom, though.

**Comment by vincentarelbundock** [comment]
I don't seen any test with external benchmark, so if we're not sure perhaps we should remove support. No?
