### ISSUE TITLE
Improve `get_data.fixest()` to find dataset

### ISSUE THREAD

**Issue by ngreifer** [easystats/insight#629]
Currently, `get_data.fixest()` relies on `.recover_data_from_environment()` to find the original dataset used in fitting the`fixest` model, which, as of now, does not include the original data in its output. `.recover_data_from_environment()` searches in the parent environment of the call and the global environment, but I recently learned that the original data exists in the parent environment of the `$call_env` component of the `fixest` object, as demonstrated [here](https://github.com/lrberge/fixest/issues/340#issuecomment-1235511329). Although searching for the dataset using the name stored in the model's function call can be dangerous as noted earlier in that thread, it might at least be useful for `get_data()` to look in the right place to find the data if it is going to use that strategy.

**Comment by vincentarelbundock** [comment]
Could you show me a 3-liner for how to retrieve from the correct environment? If it's easy I'll prep a commit.

**Comment by ngreifer** [comment]
Sure, very similar to `.recover_data_from_environment()`'s implementaton:
```
model_call <- get_call(x)
dat <- eval(model_call$data, envir = parent.env(x$call_env))
```
where `x` is the model fit object.

**Comment by strengejacke** [comment]
Thanks, should be fixed!
