### ISSUE TITLE
Improve `get_data.gee()` to find dataset in `geeglm` objects from `geepack::geeglm()`

### ISSUE THREAD

**Issue by ngreifer** [easystats/insight#630]
The output of `geepack::geeglm()` is an object that inherits from classes `"geeglm"`, `"gee"`, `"glm"`, and `"lm"`. Unlike `gee` objects resulting from `gee::gee()`, `geeglm` objects store the original dataset used to fit the model, just like `glm` objects do, so `model.frame()` works out of the box. Currently, `get_data()` dispatches to `get_data.gee()` for `geeglm` objects, and this uses the less reliable `.recover_data_from_environment()` because `gee` objects from `gee:gee()` do not store the original dataset. I think it makes sense to instead dispatch `get_data.default()` for `geeglm` objects.

**Comment by strengejacke** [comment]
The model frame does not contain all variables, I must see how to access, e.g., ID variables.
