### ISSUE TITLE
Symbol "Fei" misaligned with `export_table()`

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#642]
@mattansb @bwiernik any idea?

``` r
x <- data.frame(phi_adjusted = .3, Glass_delta = .4, Fei = .3, Epsilon2 = .7, R2 = 0.4)

insight::format_table(x, use_symbols = TRUE) |> 
  insight::export_table()
#> ϕ (adj.) | Glass' Δ |     פ‎ |   ϵ² |   R²
#> ------------------------------------------
#> 0.30     |     0.40 | 0.30 | 0.70 | 0.40


x <- data.frame(phi_adjusted = .3, Glass_delta = .4, Epsilon2 = .7, R2 = 0.4)

insight::format_table(x, use_symbols = TRUE) |> 
  insight::export_table()
#> ϕ (adj.) | Glass' Δ |   ϵ² |   R²
#> ---------------------------------
#> 0.30     |     0.40 | 0.70 | 0.40
```

<sup>Created on 2022-09-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mattansb** [comment]
Might need another rtl character in there. Let me take a look.
Where is the code for this?

**Comment by strengejacke** [comment]
Ok, Fei indeed seems to have two chars?

`names(x)[names(x) == "Fei"] <- "\u05E4\u200E"`

**Comment by strengejacke** [comment]
``` r
nchar("\u05E4\u200E")
#> [1] 2
```

**Comment by IndrajeetPatil** [comment]
I am not sure if nchar() is UTF-aware. Try with _cli_ instead. 

![image](https://user-images.githubusercontent.com/11330453/191508418-e26b7ced-90eb-4eee-86ce-a41c4155fc1d.jpeg)

**Comment by mattansb** [comment]
Yes, it's two chars because of the rtl stuff... 
Weird that this doesn't happen with printing in effectsize..

**Comment by mattansb** [comment]
Okay, in effectsize this doesn't happen because Fei is the first column :/
But why would that make a difference?

``` r
library(effectsize)

options(es.use_symbols = TRUE)

m <- lm(mpg ~ am + cyl, mtcars)
e <- eta_squared(m)

# Second column
colnames(e)[2] <- "Fei"
e
#> # Effect Size for ANOVA (Type I)
#> 
#> Parameter |      ‏פ‎ |       95% CI
#> -----------------------------------
#> am        | 0.60 | [0.40, 1.00]
#> cyl       | 0.62 | [0.43, 1.00]
#> 
#> - One-sided CIs: upper bound fixed at [1.00].

# First column
e[[1]] <- NULL
e
#> # Effect Size for ANOVA (Type I)
#> 
#> ‏פ‎    |       95% CI
#> ---------------------
#> 0.60 | [0.40, 1.00]
#> 0.62 | [0.43, 1.00]
#> 
#> - One-sided CIs: upper bound fixed at [1.00].
```

<sup>Created on 2022-09-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mattansb** [comment]
This is what we need!

```R
nchar("\u05E4\u200E", type = "width")
#> 1
```

**Comment by bwiernik** [comment]
The second character is the left to right mark. We can probably remove that since any console will already be left to right? https://stackoverflow.com/questions/51813129/decoding-u200e-to-string

**Comment by mattansb** [comment]
Nope :/

Welcome to the world of RTL LTR mixing! YAY!

```R
x <- effectsize::fei(c(10, 30))

print(x, use_symbols = TRUE)
#> ‏פ‎    |       95% CI
#> ---------------------
#> 0.50 | [0.24, 1.00]
#> 
#> - Adjusted for uniform expected probabilities.
#> - One-sided CIs: upper bound fixed at [1.00].

colnames(x)[1] <- "\u05E4"
print(x, use_symbols = TRUE)
#> פ    |       95% CI
#> -------------------
#> 0.50 | [0.24, 1.00]
#> 
#> - Adjusted for uniform expected probabilities.
#> - One-sided CIs: upper bound fixed at [1.00].
```

**Comment by strengejacke** [comment]
> ```r
> x <- data.frame(phi_adjusted = .3, Glass_delta = .4, Fei = .3, Epsilon2 = .7, R2 = 0.4)
> 
> insight::format_table(x, use_symbols = TRUE) |> 
>   insight::export_table()
> ```

Cool! Just wondering whether we need to change _every_ instance? `type="width"` refers to printing with `cat()`, but to make `substr()` work properly, I probably shouldn't add `type="width"`?

**Comment by mattansb** [comment]
I don't think we have any other non printing characters anywhere else, so probably not (:
But going forward, probably the safest to do this eventually.

**Comment by strengejacke** [comment]
Ok, the case where I use `substr()` and `nchar()` combined is to remove any trailing newline-characters. Looks like I should _not_ add `type = "width"` here (assuming the last character is no unicode character):

``` r
out <- "abc\n\u05E4\u200E"
nchar(out)
#> [1] 6
nchar(out, type = "width")
#> [1] 4

# last character is unicode, last char won't be removed
# when *not* using type = "width"
print(out)
#> [1] "abc\nפ‎"
substr(out, 1, nchar(out) - 1)
#> [1] "abc\nפ"
substr(out, 1, nchar(out, type = "width") - 1)
#> [1] "abc"

out <- "abc\u05E4\u200Eef\n"
nchar(out)
#> [1] 8
nchar(out, type = "width")
#> [1] 6

# last character is *not* unicode, last char is removed
# correctly when not using type = "width"
print(out)
#> [1] "abcפ‎ef\n"
substr(out, 1, nchar(out) - 1)
#> [1] "abcפ‎ef"
substr(out, 1, nchar(out, type = "width") - 1)
#> [1] "abcפ‎"
```

<sup>Created on 2022-09-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mattansb** [comment]
Yes, because there *is* a character there, it is just 0-width when printing.

**Comment by mattansb** [comment]
Don't you want to use `trimws()` instead here?

``` r
(out <- trimws("abc\u05E4\u200Eef\n", which = "right"))
#> [1] "abcפ‎ef"
nchar(out)
#> [1] 7
nchar(out, type = "width")
#> [1] 6

(out <- trimws("abcde\u05E4\u200E\n", which = "right"))
#> [1] "abcdeפ‎"
nchar(out)
#> [1] 7
nchar(out, type = "width")
#> [1] 6
```

<sup>Created on 2022-09-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mattansb** [comment]
Or `sub()`?

``` r
(out <- sub("\\n$", "", "abc\u05E4\u200Eef\n"))
#> [1] "abcפ‎ef"
nchar(out)
#> [1] 7
nchar(out, type = "width")
#> [1] 6

(out <- sub("\\n$", "", "abcde\u05E4\u200E\n"))
#> [1] "abcdeפ‎"
nchar(out)
#> [1] 7
nchar(out, type = "width")
#> [1] 6
```

<sup>Created on 2022-09-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
What an evil character:
![image](https://user-images.githubusercontent.com/26301769/191541945-94bd875c-ce87-4593-a4c3-b9475be21701.png)

**Comment by mattansb** [comment]
Looks fine on rstudio 😜

**Comment by strengejacke** [comment]
r what?

**Comment by strengejacke** [comment]
Indeed, looks good in vscode, too:
![image](https://user-images.githubusercontent.com/26301769/191546380-91e46a54-6449-4ff4-ad29-5aee3c94479b.png)

seems to be a GitHub issue
