### ISSUE TITLE
Display issues with RStudio Visual Editor

### ISSUE THREAD

**Issue by jmgirard** [easystats/insight#644]
I am using RStudio's visual editor to teach novices about R and want to teach them about easystats as well. An issue I'm running into however is that the insight tables are often too wide to display correctly (see below). I know I can use `print_md()` to get better formatting here but I'd prefer not to have to teach them another function and it also doesn't look great with a dark color theme (see below) although I usually do teach with the default, light background theme.

Open RStudio, create new RMarkdown (or Quarto) document, change to Visual Editor view.

    ---
    output: html_document
    ---
    
    ```{r}
    fit <- aov(
      formula = Petal.Length ~ Species,
      data = iris
    )
    mp <- parameters::model_parameters(fit)
    mp
    ```
    
    ```{r}
    parameters::print_md(mp)
    ```

![image](https://user-images.githubusercontent.com/6829033/191579372-9cfdff8c-6d1a-4d52-acaa-ec0d979fe0e6.png)

**Comment by strengejacke** [comment]
My best suggestion in this case would be: switch to [vscode](https://code.visualstudio.com/) 😃 
The window management is rather different from that in RStudio, but once you get used to it, you can easily (via shortcut) resize panels/windows quickly. I often use this when I get wide tables, then I just press a shortcut and the terminal panel is maximized etc. (You can do this with RStudio as well, but imho less smooth).

Anyway, I don't think that switching is your preferred option. Another way could be to limit the table width. This is not very prominently documented, but below is an example where the table is split at a certain width.

``` r
fit <- aov(
  formula = Petal.Length ~ Species,
  data = iris
)
mp <- parameters::model_parameters(fit)
print(mp, table_width = 40)
#> Parameter | Sum_Squares |  df
#> -----------------------------
#> Species   |      437.10 |   2
#> Residuals |       27.22 | 147
#> 
#> Parameter | Mean_Square |       F |      p
#> ------------------------------------------
#> Species   |      218.55 | 1180.16 | < .001
#> Residuals |        0.19 |         |       
#> 
#> Anova Table (Type 1 tests)
```

Another thing might be the markdown rendering. Not sure if you can easily define the default font color?

(Again, vscode automatically selects a visible color based on the theme you use by default)

![image](https://user-images.githubusercontent.com/26301769/191583221-ea81860c-b10f-4e2b-80a5-235cd24ebd53.png)

Finally, you could also try `print_html()` instead md, which formats the table differently:

![image](https://user-images.githubusercontent.com/26301769/191583484-5627aaf5-8f8d-4c62-8804-cfc1a1eda4c2.png)

**Comment by strengejacke** [comment]
If you prefer to use text output, you could of course rename columns:

``` r
fit <- aov(
  formula = Petal.Length ~ Species,
  data = iris
)
mp <- parameters::model_parameters(fit)
mp |> datawizard::data_rename(
  pattern = c("Sum_Squares", "Mean_Square"),
  replacement = c("Sum Sq.", "Mean Sq.")
)
#> Parameter | Sum Sq. |  df | Mean Sq. |       F |      p
#> -------------------------------------------------------
#> Species   |  437.10 |   2 |   218.55 | 1180.16 | < .001
#> Residuals |   27.22 | 147 |     0.19 |         |       
#> 
#> Anova Table (Type 1 tests)
```

or you select only certain columns:

``` r
fit <- aov(
  formula = Petal.Length ~ Species,
  data = iris
)
mp <- parameters::model_parameters(fit)
mp |> print(select = c("Parameter", "Mean_Square", "p"))
#> Parameter | Mean_Square |      p
#> --------------------------------
#> Species   |      218.55 | < .001
#> Residuals |        0.19 |       
#> 
#> Anova Table (Type 1 tests)
```

Does any of these approaches solve your issue?

**Comment by jmgirard** [comment]
For teaching purposes, I will probably go with either teaching them about `print_md()` or teaching them `print(..., table_width = 40)`. For my own purposes, I will check out vscode. I already use that for web development so it would be great to consolidate. Do you have any tips/suggested readings on getting started using vscode to do R?

**Comment by strengejacke** [comment]
> Do you have any tips/suggested readings on getting started using vscode to do R?

No, it mostly ends up with the same couple of websites. I have set up a gist, where I try to write down and summarize several things that _might_ be useful when starting VS Code with R: https://gist.github.com/strengejacke/82e8d7b869bd9f961d12b4091c145b88

But back on topic: what about `Ctrl+Shift+1` to zoom in/out the source window? That could be a way to fix you problem (or `Ctrl+Shift+0` for the console)

**Comment by jmgirard** [comment]
Actually, this may be the easiest solution for teaching: https://community.rstudio.com/t/visual-editor-too-narrow/112336

**Comment by strengejacke** [comment]
Ah, I see. The _visual_ editor isn't affected by resizing the panel.

![image](https://user-images.githubusercontent.com/26301769/191672179-edff3447-6969-4da2-88bc-6fe4376489c6.png)

But than we can consider this issue as resolved? I'm not sure what we can further do from our side (except the printing-tips we discussed above)?

**Comment by bwiernik** [comment]
Personally, one of the first things I taught my students to do was to disable in-line output from notebooks and instead send output to the console. They found that a lot easier to see what the code was doing when they weren't shown output that changed format regularly (eg, text table vs html table)

**Comment by strengejacke** [comment]
@jmgirard I'm closing this issue as solved. Feel free to reopen if there's something we can do from _insight_ side.
