### ISSUE TITLE
`find_formula` fails when applied to `lme` inside `lapply`

### ISSUE THREAD

**Issue by iago-pssjd** [easystats/insight#658]
I come here from https://github.com/vincentarelbundock/modelsummary/issues/559.
I adapt the reprex
```r
library(insight)
library(nlme)
models <-lapply(c("", " + Sex"), \(.x) lme(as.formula(paste0("distance  ~ age", .x)), random = ~ 1, data = Orthodont))
lapply(models, find_formula)
Error in paste0("distance  ~ age", .x) : object '.x' not found
```
I would say that this seems to be a duplicate of issue #309, but next line works
```r
find_formula(lme(as.formula(paste0("distance  ~ age", "")), random = ~ 1, data = Orthodont))
$conditional
distance ~ age
<environment: 0x55c02e144f78>

$random
~1
<environment: 0x55c02e144f78>

attr(,"class")
[1] "insight_formula" "list"         
```

Thanks!

**Comment by iago-pssjd** [comment]
Maybe solvable changing `eval(x$call$fixed) ` in
https://github.com/easystats/insight/blob/6fdc6016313f49caeeba5feb2643be6ad2623a1d/R/find_formula.R#L1198-L1200
with `formula(x$terms)`?

**Comment by vincentarelbundock** [comment]
> @strengejacke I don't see your point. I only modify the fixed effects part of `find_formula.lme`

One question is: if the random part is something like `random=~x1+x2`, will your change properly classify those as "random", or will it stuff the "x1" and "x2" variables in the "fixed" part by mistake?

**Comment by strengejacke** [comment]
Ah ok, didn't test with the PR.

**Comment by iago-pssjd** [comment]
@vincentarelbundock 
Let's see with the example:
```r
library(insight)
library(nlme)
models <-lapply(c("", " + Sex"), \(.x) lme(as.formula(paste0("distance  ~ age", .x)), random = ~ Sex, data = Orthodont))
find_formula(models[[1]])
$conditional
distance ~ age
<environment: 0x55a163099e58>

$random
~Sex
<environment: 0x55a163aea038>

attr(,"class")
[1] "insight_formula" "list"      
```
In this case, it seems to work. I may try some more complex example.

**Comment by vincentarelbundock** [comment]
Great!

But I bet the code breaks if the lapply modifies the random component instead of the fixed.

Is that a big deal?

**Comment by iago-pssjd** [comment]
@vincentarelbundock 
> if the lapply modifies the random component 
I am not sure what do you mean, but maybe you refer if I use the `as.formula x paste` combination in the random component. Indeed, this part is not solved with this PR, it behaves like until now, the only information about random formula contained in `lme` object is that in `call`, which is the used by `find_formula.lme`, so the issue would persist for the random part.

**Comment by iago-pssjd** [comment]
I close the issue, since th PR to solve the fixed effects part was merged and I do not see there is any chance to solve the random effects part as described in previous comments above.

**Comment by strengejacke** [comment]
thanks, we can always open a new issue if needed.
