### ISSUE TITLE
reduce usage of `perl = TRUE` in regex, where possible

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#663]
Currently, we use `perl = TRUE` in several instances where we have regular expression. However, this is very slow. If possible, we should remove it. Can anyone help judging the patterns and see if `perl = TRUE` is really needed?

https://github.com/easystats/insight/search?q=%22perl+%3D+TRUE%22

@IndrajeetPatil @bwiernik @vincentarelbundock

**Comment by strengejacke** [comment]
Yeah, probably you're right. I think the `find_*()` functions are called multiple times. And I have already replaced a lot of instances, e.g. also using `startsWith()` / `endsWith()` or adding `fixed = TRUE`. Maybe in total, this might give a noticeable difference?

**Comment by strengejacke** [comment]
In general, I'm curious if this pattern `"^(?!sd_|cor_)(.*)"` works w/o `perl = TRUE`?

**Comment by vincentarelbundock** [comment]
> In general, I'm curious if patterns like this one `"^(?!sd_|cor_)(.*)"` works w/o `perl = TRUE`?

Ya, I'm pretty sure that look-ahead and look-behinds do *not* work with the base R regexes, so we need `perl=TRUE` in those cases.

**Comment by strengejacke** [comment]
Ok. But maybe here:

```r
.grep_non_smoothers <- function(x) {
  grepl("^(?!(s\\())", x, perl = TRUE) &
    # this one captures smoothers in zi- or mv-models from gam
    grepl("^(?!(s\\.\\d\\())", x, perl = TRUE) &
    grepl("^(?!(ti\\())", x, perl = TRUE) &
    grepl("^(?!(te\\())", x, perl = TRUE) &
    grepl("^(?!(t2\\())", x, perl = TRUE) &
    grepl("^(?!(gam::s\\())", x, perl = TRUE) &
    grepl("^(?!(gam::s\\.\\d\\())", x, perl = TRUE) &
    grepl("^(?!(VGAM::s\\())", x, perl = TRUE) &
    grepl("^(?!(mgcv::s\\())", x, perl = TRUE) &
    grepl("^(?!(mgcv::s\\.\\d\\())", x, perl = TRUE) &
    grepl("^(?!(mgcv::ti\\())", x, perl = TRUE) &
    grepl("^(?!(mgcv::te\\())", x, perl = TRUE) &
    grepl("^(?!(brms::s\\())", x, perl = TRUE) &
    grepl("^(?!(brms::t2\\())", x, perl = TRUE) &
    grepl("^(?!(smooth_sd\\[))", x, perl = TRUE)
}
```

we could instead use `!startsWith()`?
