### ISSUE TITLE
Problems with `get_data()` in `testthat` environments

### ISSUE THREAD

**Issue by ngreifer** [easystats/insight#666]
I've been having a lot of trouble with `insight::get_data()` in `testthat` environments, which makes it hard to test my functions that rely on it. I know `testthat` does something crazy and (to me) opaque with environments, but at the same time I would expect `get_data()` to be intelligent about where to look for the dataset. Lately I've been having this problem with models whose `get_data()` method relies on `.recover_data_from_environment()`, including `tobit` models from `AER`. A reproducible example below:

```r
d <- data.frame(y = rnorm(100),
                x = rnorm(100))
d$y[d$y > 1.5] <- 1.5

fit <- AER::tobit(y ~ x, data = d, right = 1.5)

test_that("get_data() works", {
  expect_equal(nrow(insight::get_data(fit)), 100)
})
```
If you save that in a script and run `devtools::test_active_file()`, you should find that it fails the test because `get_data()`returns `NULL`. (Note that simply running the lines does not result in a failure.) This doesn't occur in your tests for `tobit` models because the dataset used for testing is loaded into the global environment using `data()`. If you were to construct a dataset in the testing environment or load it using, e.g., `read.csv()` or `readRDS()`, I think you would also find that `get_data()` fails.

**Comment by strengejacke** [comment]
We could solve this in most cases using `<<-` when assigning data.

Can you try

```r
out <- data.frame(y = rnorm(100),
                x = rnorm(100))
out$y[out$y > 1.5] <- 1.5

d <<- out
```

**Comment by ngreifer** [comment]
That does solve it in the tests, but it makes the tests no longer self-contained (they produce objects in the global environment), and I feel like it misses that `get_data()` is not looking in the right place to find the original dataset. It might be useful to have it search in the environment of the model formula in the model call or the model formula if present. This doesn't work for every model (e.g., `fixest` models do a transformation on the formula that changes which environment it belongs to), but for more straightforward models like `tobit` it might be more effective than simply looking in the global environment and the parent frame.

**Comment by strengejacke** [comment]
Is this straightforward? Do you have any ideas how to solve this issue? I must say I'm not that familiar with this environment stuff.

**Comment by ngreifer** [comment]
Sure, so in `.recover_data_from_environment()`, you have

```r
dat <- tryCatch(
    {
      eval(model_call$data, envir = parent.frame())
    },
    error = function(e) {
      NULL
    }
  )
```

But you could replace `parent.frame()` with `environment(model_call$formula)` (perhaps after checking to see if there is such a formula). You could add this version of it before or after the current version, only running if the first returns `NULL`, e.g.,

```r
dat <- tryCatch(
    {
      eval(model_call$data, envir = environment(model_call$formula))
    },
    error = function(e) {
      NULL
    }
  )

if (is.null(dat)) {
  dat <- tryCatch(
      {
        eval(model_call$data, envir = parent.frame())
      },
      error = function(e) {
        NULL
      }
    )
}
```
(Other functions serving related purposes could use similar edits.) You might have a utility function that searches for a model's calling environment that you can use, e.g., `.get_env()`, which returns it for use in functions that require it, like this one. This would reduce the reliance on everything being in a specific environment (i.e., the global environment or the parent frame of the `get_data()` call), instead using information from the model object itself to direct the search.

**Comment by vincentarelbundock** [comment]
Nothing specific to add, but I'd be *delighted* if this worked, because this issue has been a considerable source of pain...

Thanks all for your work on this!

**Comment by strengejacke** [comment]
I have checked and it looks like most function call `.recover_data_from_environment()`, which includes the proposed fixed. Only a very few exceptions (like `get_data.fixest()`) have their own solution. So hopefully #667 now has edits for all relevant occurrences.
