### ISSUE TITLE
CRAN package insight fails

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#669]
> Dear maintainer,
>
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_insight.html>.
>
> Apparently your package fails its checks in a strict Latin-1* locale,
> e.g. under Linux using LANG=en_US.iso88591 (see the debian-clang
> results).
> 
> Please correct before 2022-10-29 to safely retain your package on CRAN.

Similar issue as in _effectsize_. Any ideas how to resolve? Disabling code chunks on Linux?

@IndrajeetPatil @mattansb @bwiernik

**Comment by DominiqueMakowski** [comment]
remove all non-ascii characters 

![](https://media.giphy.com/media/dtGIRL0FDp6nnOPGb5/giphy.gif)

**Comment by mattansb** [comment]
Trying a fix here: https://github.com/easystats/effectsize/pull/521
