### ISSUE TITLE
support for Tweedie-family in get_variance()

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#68]
Moved here from https://github.com/strengejacke/sjstats/issues/46

@mebrooks I (re-)opened this issue here, because due to the re-organization of some packages, all "get-model-information" related stuff is now in the _insight_-package.

**Comment by strengejacke** [comment]
@mebrooks
I found [this comment](https://github.com/glmmTMB/glmmTMB/issues/293#issuecomment-359987345) and wonder if this is the correct way to calculate the tweedie-variance? If so, it would be easy to implement...

_Originally posted by @bbolker in https://github.com/glmmTMB/glmmTMB/issues/293#issuecomment-359987345_

**Comment by mebrooks** [comment]
Yes. I brought that up while we were [working on the last release](https://github.com/glmmTMB/glmmTMB/issues/382).

**Comment by strengejacke** [comment]
Ok, I think then this issue is closed with [this PR](https://github.com/easystats/insight/commit/4ba3ce56a42c5a9e50a2ce4a4e6ccee0a888944d). I checked the code with both approaches shown in Ben's comment, all the same results.

Once this package is updated on CRAN, the _performance_ package will follow, which now takes over the `r2()` function from sjstats.
