### ISSUE TITLE
`get_data()` produces incorrect results with transformations

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#689]
When a model formula includes transformations, `get_data()` returns incorrect results:

``` r
library(insight)

x <- abs(rnorm(100, sd=5)) + 5
y <- exp(2 + 0.3 * x + rnorm(100, sd=0.4))
dat <- data.frame(y, x)
mod <- lm(log(y) ~ log(x), data = dat)

head(insight::get_data(mod))
              y             x
    1  62.01648  0.000000e+00
    2  21.08598  8.881784e-16
    3  41.99490  8.881784e-16
    4  28.51719  8.881784e-16
    5 289.96846  1.776357e-15
    6 120.86293 -1.776357e-15

head(dat)
              y         x
    1  69.07015  7.053672
    2  26.25120  5.165226
    3  49.20110  7.206200
    4  34.23304  5.715846
    5 301.20648 11.238027
    6 129.50084  8.637918
```

I know recovering from environment is not always ideal, but should we change `get_data()` to always try to do that first before falling back on `model.frame`? This would ensure that the actual original data gets returned in most cases.

**Comment by bwiernik** [comment]
What does `model.frame()` return here?

**Comment by vincentarelbundock** [comment]
`model.frame()` returns the logged version, which isn't what we want (I think).

``` r
library(insight)

set.seed(1024)

x <- abs(rnorm(100, sd=5)) + 5
y <- exp(2 + 0.3 * x + rnorm(100, sd=0.4))
dat <- data.frame(y, x)
mod <- lm(log(y) ~ log(x), data = dat)

head(insight::get_data(mod), 2)
             y x
    1 89.32396 0
    2 42.38241 0

head(dat, 2)
             y        x
    1 98.21727 8.893314
    2 49.32979 6.947382

head(model.frame(mod))
        log(y)   log(x)
    1 4.587182 2.185300
    2 3.898528 1.938365
    3 6.348238 2.719253
    4 5.582090 2.293733
    5 4.032195 1.830892
    6 6.784617 2.742086
```

**Comment by strengejacke** [comment]
Strange, we have some code to back-transform data for quite a long time:
https://github.com/easystats/insight/blob/654252dca5697b147f2f6df9796a26178742fcd3/R/utils_get_data.R#L51

And this should recognize column names of the model frame:
https://github.com/easystats/insight/blob/654252dca5697b147f2f6df9796a26178742fcd3/R/utils_get_data.R#L794

Will look into this tomorrow...

**Comment by vincentarelbundock** [comment]
Thanks for attacking this so quickly, I really appreciate it!

Above I asked if it wouldn’t be wise to recover from the environment first, and only try to backtransform as a last resort. The motivation was that this function is super cool and impressive, but that it feels quite dangerous to me:

https://github.com/easystats/insight/blob/45cf4fbc0e96e3ed317140088851ed07ee288cbb/R/utils_get_data.R#L793

Basically, that function reads column names with regexes, guesses the proper backtransform, and applies it. It seems like we have to put a lot of trust in our regexes and in the idea that we’ve inventoried and tested all reasonable/possible transformations.

With your new PR, the `log` example now works well, but here are two examples that don’t work as well. Of course, we could fix those two specific examples, but I brought them up to illustrate the more general fact that the range of potential transformations is very very large. In an "infrastructure" package like this, it may be a good idea to look for a safer strategy, rather than try to be clever with regexes.

``` r
x <- abs(rnorm(100, sd=5)) + 5
y <- exp(2 + 0.3 * x + rnorm(100, sd=0.4))
dat <- data.frame(y, x)

mod <- lm(log(y) ~ log(log(x + 1)), data = dat)

head(insight::get_data(mod), 2)
             y        x
    1 38.40796 6.288154
    2 36.94057 7.500643
head(dat, 2)
             y        x
    1 38.40796 5.288154
    2 36.94057 6.500643

mod <- lm(asinh(y) ~ asinh(x), data = dat)
head(insight::get_data(mod), 2)
      asinh(y) asinh(x)        x
    1 4.341581 2.367439 5.288154
    2 4.302641 2.570912 6.500643
head(dat, 2)
             y        x
    1 38.40796 5.288154
    2 36.94057 6.500643
```

**Comment by strengejacke** [comment]
I agree with the current approach, we do a lot of effort to recreate the data used to fit the model, and it's probably prone to errors in some edge cases. But we also had the discussion about recovering data from the environment, which can also be problematic, when data has changed between model fitting and the call to `get_data()` - are there any possibilities how we can include sanity checks?

**Comment by strengejacke** [comment]
_if_ we go that route, I suggest:

1. All `get_data.*()` methods will be renamed into internals, `.get_data.*()`
2. `get_data()` is a single function, that tries to recover data from environment.
3. If 2.) fails, we call `.get_data.<class>()`, which applies the former way of reconstructing the data frame (which we use now).
4. When 2) works, we have to find all variables in the model (`find_variables()`?) and select only columns used in the model. We don't want a data frame wirh 1000 variables when only 10 were used in the model.

- That would mean that usually, this function will be _much_ faster, but we must hope that the data in the environment is still the same data used to fit the model.
- I think since we evaluate the `data` argument, we *should* get the correct data (like `data = dplyr::filter(iris, Species == "versicolor")`), but are there exceptions?

**Comment by strengejacke** [comment]
I think changing all `get_data()` into internals does not work, since we have special handling for some models, so we can't in general try to recover data from environment, I think. For now, I revise every `get_data()` method.

**Comment by vincentarelbundock** [comment]
> But we also had the discussion about recovering data from the environment, which can also be problematic, when data has changed between model fitting and the call to `get_data()` - are there any possibilities how we can include sanity checks?

Yep, you're 100% right: this is the big big big tradeoff.

I go back and forth on this, but currently feel that it may be easier to set clear expectations for users, with documentation that is easy to understand and applies to all models. The function description and `@return` entry could state explicitly that the function tries to extract the data from the environment, and include a strongly worded warning that if the data has been reassigned, the return value may be inconsistent with the model.

Overall, speed, consistency. clarity. and no unforseen edge cases seem like good things here. And if we modularize as you describe, we can always revisit eventually if this causes too many problems in downstream packages.

In terms of sanity checks, we could compare the number of rows, but that's obviously quite limited. I don't really see what else...

**Comment by vincentarelbundock** [comment]
BTW, I'm traveling next week, but if you need some help with this I can put some time in when I come back.

**Comment by strengejacke** [comment]
I think #691 should now close this issue, but probably we should have more tests... Actually, we should have a test for (almost) every model we support 😬 

I now did following:

Almost all `get_data.*()` methods first try to recover data from environment:

```r
  # try to recover data from environment
  model_data <- .get_data_from_environment(x)

  if (!is.null(model_data)) {
    return(model_data)
  }

  # fall back to extract data from model frame
  <...> # former code from `get_data()` method comes here...
```

Recovering from environment also includes adding weights and offsets, if found. See code here:
https://github.com/easystats/insight/pull/691/files#diff-0cff55d8e87e16af8ef9f26202e2af098937cd40dd71d60d72d78144d5b91d08

If this fails, the "old" behaviour applies. Recovering data from environment includes a call to `find_variables()`, which _should_ filter the data when we use `effects` or `component` argument. We need tests for these, too.

But first let's see if current tests all pass - I'm afraid we will have this environment issue with _testthat_, that data is not found in test environments...

**Comment by strengejacke** [comment]
I'll merge #690 in either case, because it's a bug fix / improvement to the current situation. We can then carefully review #691 and see if that approach generally works.

**Comment by vincentarelbundock** [comment]
Very cool. Let me know when you want to test the new PR. I'll install locally and run the `marginaleffects` test suite, which makes very heavy use of `get_data` for 50+ model types, inside functions, etc etc.

**Comment by strengejacke** [comment]
Only 50+ models? That's just the half of what in principal _should_ be supported by insight... 😄 
Ok, let me see if there are some obvious issues in #691, and once I could iron them out and tests pass, I'll let you know you can run tests.

**Comment by strengejacke** [comment]
@IndrajeetPatil How can we add PR 691 as remotes to the other easystats packages, so they test with the _insight_ version from that PR?

**Comment by strengejacke** [comment]
what would you expect here as response data? This is what currently is returned, however, following our new approach with recovering data from environment, we would probably have the two columns `vs` and `cyl`?

```r
 data(mtcars)

  m1 <- suppressWarnings(glmer(
    vs / cyl ~ disp + (1 | cyl),
    data = mtcars,
    family = binomial(link = "logit")
  ))

  test_that("get_response", {
    expect_equal(head(get_response(m1)), c(0, 0, 0.25, 0.16667, 0, 0.16667), tolerance = 1e-2)
  })
```

**Comment by vincentarelbundock** [comment]
Yes, exactly: I would expect two columns. As in the original.

**Comment by strengejacke** [comment]
> @IndrajeetPatil How can we add PR 691 as remotes to the other easystats packages, so they test with the _insight_ version from that PR? Something like `Remotes: easystats/insight@691`?

ping @IndrajeetPatil

**Comment by IndrajeetPatil** [comment]
Sorry, missed this because I was traveling and distracted.

You can do:

```r
Remotes: easystats/insight@revise_get_data
```

**Comment by strengejacke** [comment]
Do you know what to do here?

https://github.com/easystats/datawizard/actions/runs/3581012714/jobs/6023643966
