### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#7]
Do you think we should keep these [datasets](https://github.com/easystats/insight/tree/master/data) in the package?

**Comment by strengejacke** [comment]
I don't know the base datasets well, that's why I'm using my own datasets, or datasets that have been useful for testing. But we can replace them with any other datasets

**Comment by strengejacke** [comment]
Sounds good to me! I'll commit some changes (to master-branch, I have no version control here at work, but R-files sync via Cloud with my home pc, where I have GitHub etc. installed) later, then we may revise the tests and examples.

I need to find a working setup for me, that, when I'm working on the package at work, I can do this in an own branch. I _could_ sync all files via cloud, including the GitHub hidden subdir, but that means really syncing a lot of files, unfortunately... Hm...

**Comment by DominiqueMakowski** [comment]
No problem we can still update dev from master if it's ahead. I can help you in replacing some tests with native datasets if needed. Also, I believe you can make the commits directly to the dev branch in the web browser github (although it's a bit tedious I agree)

**Comment by DominiqueMakowski** [comment]
I've replaced on dev the two occurrences of `efc` use in testing by iris and replaced the use of `fish` by its direct download. I think that we can remove the datasets from this package (unless you want to keep them).

**Comment by DominiqueMakowski** [comment]
However I haven't check the docstrings example
