### ISSUE TITLE
BayesFactor support

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#70]
Related to [this](https://github.com/easystats/bayestestR/issues/49), it would be good having insight support for BayesFactor objects. I'll look into it.

**Comment by strengejacke** [comment]
I have not used BayesFactor so far (and I'm not really a fan of Bayes Factors in general, but that's a different thing ;-)), but if you have some experiences with that package, feel free to file a first draft.

I have looked at your PR, for me I can't get `find_formula()` working. I think with the BayesFactor package we have similar problems as with the `htest`-class from `t.test()` etc. The necessary information is not completely available, or very difficult to extract. Thus I think this might be something, which probably won't make it into the 0.2.0-release? But I don't want to be too pessimistic ;-)

**Comment by DominiqueMakowski** [comment]
Right, BayesFactor returns quite convoluted objects with no clear identifier for different models type. This will make it quite hard to implement general methods. Thus, I believe the first thing would be to start by the creating of some internal classifying function that tells whether it is a correlation, a t-test, an anova or such. Then, we could hook that to `model_info`, and then to other methods which behaviour would depend on model info features.

I will look try looking into it again.

**Comment by strengejacke** [comment]
The difficulty is to extract the formula, on which many other functions depend on. But maybe we should think of a different implementation of such objects (like htest), where we focus on other information and for which we don't provide _all_ methods insight has. Better a "limited" support than no support, and regarding _report_, it's nice to have at least some kind of support in insight.

**Comment by DominiqueMakowski** [comment]
I can't agree more

**Comment by DominiqueMakowski** [comment]
https://github.com/easystats/insight/blob/1ec68bd2a6e0ad06f2ea916011f032863b2ec8fa/R/model_info.R#L832

I've added a small internal `classifier` for BayesFactor objects. Could you help me create a small `model_info` function for it (so that the `is_ttest` and `is_correlation` works similarly to regular ttests and correlations ). This would help to further support in parameters and bayestestR

**Comment by DominiqueMakowski** [comment]
🎉 thanks!

**Comment by strengejacke** [comment]
Please take a look at these lines, starting from
https://github.com/easystats/insight/blob/master/R/model_info.R#L768

Are all "types" captured here? What would be "meta"? "linear" should already be captured by default.

**Comment by DominiqueMakowski** [comment]
meta is for some  Meta-analytic t tests... I feel like it is too specific for having its own "classifier" in model_info, but on the other hand, we cannot classify it under regular ttests. I don't know what to do with it 😕

**Comment by strengejacke** [comment]
well, it's returned "silently" anyway and not yet officially documented, so we can keep it for now...
