### ISSUE TITLE
`compact_list()` produces error

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/insight#709]
If I turn warnings into errors, `compact_list()` usage produces the following error:

```r
Caused by error in `length(i) == 0L || is.null(i) || (length(i) == 1L & is.na(i))`:
! (converted from warning) 'length(x) = 2 > 1' in coercion to 'logical(1)'
```

This is coming from `(length(i) == 1L & is.na(i))` here:

https://github.com/easystats/insight/blob/1c0da826bd68cbd07df0b24dc3634a13c140e642/R/utils_compact.R#L13

Is there an `any()`/`all()` missing?

**Comment by strengejacke** [comment]
Do You have a reproducible example?

**Comment by IndrajeetPatil** [comment]
``` r
library(performance)
options(warn = 2L)

npk2 <- within(npk, foo <- rnorm(24))
m_manova <- manova(cbind(yield, foo) ~ block + N * P * K, npk2)
model_performance(m_manova)
#> Error in length(i) == 0L || is.null(i) || (length(i) == 1L & is.na(i)): (converted from warning) 'length(x) = 2 > 1' in coercion to 'logical(1)'
```

<sup>Created on 2023-01-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
minimal reprex:

```r
options(warn = 2L)
x <- list(a = 1, b = c(1, 2))
insight::compact_list(x, remove_na = TRUE)
```

**Comment by IndrajeetPatil** [comment]
TBH, there is no need for even a minimal reprex, just static analysis would tell you that this is going to be an error in `R 4.3`.

Vector logical operators like `&`/`|` in `if` without `any()`/`all()` are always going to be problematic.

**Comment by strengejacke** [comment]
In this case, the minimal example helped finding out which metric is failing, _and_ it is useful to write test units, if the code is short :-)
