### ISSUE TITLE
lfe-update breaks insight

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#72]
See https://cran.r-project.org/web/checks/check_results_insight.html
The package-update somehow completely changed the behaviour. I'll dig into this.

**Comment by DominiqueMakowski** [comment]
In the current dev branch, there are also several tests that didn't pass for me, don't know if they are the same. And for me bayestestR still fails, despite being updated... I wonder if there is something off going between our systems that could cause these discrepancies.

**Comment by strengejacke** [comment]
Have you updated all packages? brms 2.8.0 introduced some changes that are already accounted for in bayestestR.

For `lfe`, it's pretty clear why it breaks our package. From the new:

> A felm-object now works as expected with formula().

I've revised the code and running checks and tests now. This could be a chance to submit insight earlier than planned, because fixing check-issues is always welcomed by the CRAN team.

**Comment by strengejacke** [comment]
closed in https://github.com/easystats/insight/commit/1259f624ed95b40b99fcbef0c0c25c76310e16ee
