### ISSUE TITLE
find_ and get_ methods with models of multiple formula components like clm() & lme()

### ISSUE THREAD

**Issue by MrJerryTAO** [easystats/insight#727]
Hi @strengejacke, I spotted some leaving-out-variable issues with find_...() and get_...() in certain model objects with multiple formula components, especially in the following functions

- find_predictors()
- find_variables()
- find_weights()
- get_data()

which causes issues in other packages that depend one {insight}. 

With nlme::lme(), variables in the weight = varFunc() are not retained. The resolution may require an update to the insight:::find_weights.default() method or adding a new method to find_weights(); or rather treat variables in weight = varFunc() as predictors and update the insight:::find_predictors.default() method or adding a new method to find_predictors().
```r
summary(Model <- lme(
  distance ~ age, data = Orthodont, 
  random = ~ 1 | Subject, 
  weights = varIdent(form = ~ 1 | Sex)))
summary(Model <- lme(
  distance ~ age, data = Orthodont, 
  random = ~ Sex | Subject))
find_predictors(Model)
'$conditional
[1] "age"'
find_variables(Model)
'$response
[1] "distance"
$conditional
[1] "age"
$random
[1] "Subject"'
find_weights(Model) # Did not extract Sex as a variable
'"varIdent(form = ~1 | Sex)"'
class(find_weights(Model)) # "character"
names(get_data(Model)) # Sex was left out
'"distance" "age"      "Subject" '
```
I think the weights argument in lme() may behave very differently from those in other models, as it is not a numeric vector by which all variables are divided nor an integer vector of observation counts but a function modeling the heteroscedasticity. This is why I suspect that a good solution is to get the variable names through find_predictors() instead of find_weights(). The lme() document shows that weights is

> an optional [varFunc](http://127.0.0.1:33931/help/library/nlme/help/varFunc) object or one-sided formula describing the within-group heteroscedasticity structure. If given as a formula, it is used as the argument to [varFixed](), corresponding to fixed variance weights. See the documentation on [varClasses]() for a description of the available [varFunc]() classes. Defaults to NULL, corresponding to homoscedastic within-group errors.

With ordinal::clm(), variables in the scale = ~ ... and nominal = ~ ... formulae are not retained. The resolution may require an update to the insight:::find_predictors.default() method or adding a new method to find_predictors().
```r
summary(Model <- clm( # nominal + scale effects
  cyl ~ wt, scale = ~ vs, nominal = ~ hp, 
  data = mtcars %>% mutate(cyl = factor(cyl))))
coef(summary(Model))
"                     Estimate   Std. Error       z value  Pr(>|z|)
4|6.(Intercept) 96990.6137075 8.972213e+08  1.081011e-04 0.9999137
6|8.(Intercept) 16987.7165352 4.252071e+11  3.995163e-08 1.0000000
4|6.hp           -772.5798577 7.137124e+06 -1.082481e-04 0.9999136
6|8.hp             -9.4092060 1.757182e+09 -5.354714e-09 1.0000000
wt               4591.3466175 4.280643e+07  1.072583e-04 0.9999144
vs                 -0.3962198 1.837861e+04 -2.155874e-05 0.9999828"
find_variables(Model)
'$response
[1] "cyl"
$conditional
[1] "wt"'
find_predictors(Model)
'$conditional
[1] "wt"'
find_weights(Model) # NULL
names(get_data(Model)) # only "cyl" "wt" got picked
```

**Comment by strengejacke** [comment]
@vincentarelbundock I guess it would be good to have this issue resolved before the next CRAN submission?

**Comment by vincentarelbundock** [comment]
Yes, would be great, but I'm not sure I'll have much time in the coming weeks, unfortunately.

**Comment by strengejacke** [comment]
`find_weights()` now correctly extracts the name of the related weight-variable:

``` r
library(insight)
library(nlme)
data(Orthodont)
Orthodont$w <- abs(rnorm(nrow(Orthodont)))

m1 <- lme(
  distance ~ age, data = Orthodont, 
  random = ~ 1 | Subject, 
  weights = varIdent(form = ~ 1 | Sex))

m2 <- lme(
  distance ~ age, data = Orthodont, 
  random = ~ 1 | Subject)

m3 <- lme(
  distance ~ age,
  data = Orthodont,
  random = ~ 1 | Subject,
  weights = ~w
)

find_weights(m1)
#> [1] "Sex"
find_weights(m2)
#> NULL
find_weights(m3)
#> [1] "w"
```

<sup>Created on 2023-03-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
I think the clm-issues are also resolved:

``` r
library(insight)
library(ordinal)
data(mtcars)
m2 <- suppressWarnings(clm( # nominal + scale effects
  cyl ~ wt,
  scale = ~vs, nominal = ~hp,
  data = transform(mtcars, cyl = factor(cyl))
))

find_formula(m2)
#> $conditional
#> cyl ~ wt
#> 
#> $scale
#> ~vs
#> 
#> $nominal
#> ~hp
#> 
#> attr(,"class")
#> [1] "insight_formula" "list"

find_variables(m2)
#> $response
#> [1] "cyl"
#> 
#> $conditional
#> [1] "wt"
#> 
#> $scale
#> [1] "vs"
#> 
#> $nominal
#> [1] "hp"

head(get_data(m2))
#>                   cyl    wt vs  hp
#> Mazda RX4           6 2.620  0 110
#> Mazda RX4 Wag       6 2.875  0 110
#> Datsun 710          4 2.320  1  93
#> Hornet 4 Drive      6 3.215  1 110
#> Hornet Sportabout   8 3.440  0 175
#> Valiant             6 3.460  1 105

find_predicors(m2)
#> Error in find_predicors(m2): could not find function "find_predicors"

head(get_predictors(m2))
#>                      wt vs  hp
#> Mazda RX4         2.620  0 110
#> Mazda RX4 Wag     2.875  0 110
#> Datsun 710        2.320  1  93
#> Hornet 4 Drive    3.215  1 110
#> Hornet Sportabout 3.440  0 175
#> Valiant           3.460  1 105

get_parameters(m2)
#>         Parameter      Estimate
#> 1 4|6.(Intercept) 96990.6137075
#> 2 6|8.(Intercept) 16987.7165352
#> 3          4|6.hp  -772.5798577
#> 4          6|8.hp    -9.4092060
#> 5              wt  4591.3466175
#> 6              vs    -0.3962198

parameters::model_parameters(m2, effects = "all", components = "all")
#> # Intercept
#> 
#> Parameter       | Log-Odds |       SE |                       95% CI |         z |      p
#> -----------------------------------------------------------------------------------------
#> 4|6 (Intercept) | 96990.61 | 8.97e+08 | [       -1.76e+09, 1.76e+09] |  1.08e-04 | > .999
#> 6|8 (Intercept) | 16987.72 | 4.25e+11 | [       -8.33e+11, 8.33e+11] |  4.00e-08 | > .999
#> 4|6 hp          |  -772.58 | 7.14e+06 | [       -1.40e+07, 1.40e+07] | -1.08e-04 | > .999
#> 6|8 hp          |    -9.41 | 1.76e+09 | [       -3.44e+09, 3.44e+09] | -5.35e-09 | > .999
#> 
#> # Location Parameters
#> 
#> Parameter | Log-Odds |       SE |                   95% CI |        z |      p
#> ------------------------------------------------------------------------------
#> wt        |  4591.35 | 4.28e+07 | [   -8.39e+07, 8.39e+07] | 1.07e-04 | > .999
#> 
#> # Scale Parameters
#> 
#> Parameter | Log-Odds |       SE |                95% CI |         z |      p
#> ----------------------------------------------------------------------------
#> vs        |    -0.40 | 18378.61 | [-36021.82, 36021.02] | -2.16e-05 | > .999
#> 
#> Uncertainty intervals (equal-tailed) and p-values (two-tailed) computed
#>   using a Wald z-distribution approximation.
#> 
#> The model has a log- or logit-link. Consider using `exponentiate =
#>   TRUE` to interpret coefficients as ratios.
```

<sup>Created on 2023-03-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
@vincentarelbundock can you check if https://github.com/easystats/insight/pull/729 fixes the marginal effects issues?

**Comment by MrJerryTAO** [comment]
Great. Just a heads-up: in clm() and other discrete choice models, when scale effects are included, coefficients in location and intercept parameters no longer measure log-odds directly, and exp(coef) are no longer odds ratios. So the following parameter interpretation can be misleading. 
> Parameter | Log-Odds |       SE |                   95% CI |        z |      p

**Comment by vincentarelbundock** [comment]
@strengejacke it looks like it is working for `ordinal::clm`, but I won't know if it works with `lme` until I try to add full support for it. For that, I at least need to wait for the functionality to be merged in `insight` master, so don't wait for a review of those before merging.

Thanks for the updates!

**Comment by MrJerryTAO** [comment]
Hi @vincentarelbundock, 
For lme() model objects, find_weights() does find all variable names used in weights = ... and get_data() retrieve all variables as expected. However, because weight = varFunc() can contain multiple terms, it might be better to treat it as a predictor or formula component to be listed in find_variables() instead. Otherwise, it has caused problems like https://github.com/strengejacke/ggeffects/issues/295 in other packages that expect one single character from find_weights().

**Comment by strengejacke** [comment]
Do you have an example where it fails for multiple predictors in `find_weights()`? From a conceptional perspective, I'm a bit hesitant to include all weight-predictors in the output of `find_variables()`.

**Comment by MrJerryTAO** [comment]
See https://github.com/strengejacke/ggeffects/issues/295#issuecomment-1466028273. The problem is in other packages that expect one single character from find_weights().

**Comment by strengejacke** [comment]
So what does this mean for `get_weights()` for this example:

```r
lme( distance ~ 1, data = Orthodont,  weights = varConstPower(form = ~ age | Sex))
```

1. Should it return `NULL`, and only work when `weights` is a one-sided formula indicating an actual weight-variable in the data?
2. Should it return a data frame with variables `age` and `Sex`? (and their original values from the data frame)
3. Should it return a vector of weights that is saved as attribute?

**Comment by vincentarelbundock** [comment]
What does the function return for all other models? Just a numeric vector, right? If that's irrelevant, I vote for raising an informative error. But I don't have an especially strong view, except against proposals like "returning coefficients of the variance function", which would be very different from what we have now.

**Comment by strengejacke** [comment]
> Just a numeric vector, right?

Yes. that's what usually is returned.

**Comment by MrJerryTAO** [comment]
> Yes. that's what usually is returned. 
> Right, so I would say return a numeric vector or an error. But again, I can't have a strong view because I don't know if/when that's a relevant data structure.

The current resolution seems the best before some more work is done to extract estimated variance functions from lme() as a regular function like w = function(x, coef){} where coef is estimated in lme(). I tried but couldn't figure out how to form a function w. There are multiple different varFunc classes and each seems to behave differently. Once done, it would be possible to calculate SE for prediction intervals by making an additive term to fixed-effect SE. Or customize predict.lm(..., weights = 1/w) when generating prediction intervals, because predict.lm() does allow weights to be a user-supplied function of variables supplied in newdata. 

> Should it return NULL, and only work when weights is a one-sided formula indicating an actual weight-variable in the data?

No. When weights is a one-sided formula, it is still a varFunc class, and the variable could be assessed very differently depending on the specific varFunc used, as shown https://fw8051statistics4ecologists.netlify.app/gls.html#variance-increasing-with-x_i

> Should it return a data frame with variables age and Sex? (and their original values from the data frame)

Not sure. This is stored in the attribute() though. 

> Should it return a vector of weights that is saved as attribute?

Seems best. Not sure how other functions and packages use the weights. In WLS and GLS models, weight are mostly useful to get the correct vcov estimates. But since vcov() can easily extract the already estimated vcov, I don't know if weights can be useful again. But perhaps when making in-sample prediction intervals, where sigma/weights of lme() and gls() can be used to adjust SE and CI over the sample ranges. But it won't work correctly (or as intended) for newdata where weights-variables are given but actual weights cannot be evaluated to find the prediction variance.
