### ISSUE TITLE
Vignette fails to render on R-devel

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/insight#739]
cf. https://cloud.r-project.org/web/checks/check_results_insight.html

I think this is coming from https://github.com/easystats/effectsize/issues/580. 
So, once that's resolved, this issue will also resolve itself.

**Comment by strengejacke** [comment]
Anything we can do about this? Looks like a tibble issue?

**Comment by IndrajeetPatil** [comment]
Yes, definitely a _tibble_ issue: https://cran.r-project.org/web/checks/check_results_tibble.html

Maybe we can skip evaluation of the problematic code chunks to update on CRAN. Otherwise, our submission will get stuck because of this issue.

**Comment by IndrajeetPatil** [comment]
cf. https://github.com/easystats/effectsize/issues/580#issuecomment-1475165338
