### ISSUE TITLE
Tests failing in random order (again)

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/insight#757]
@etiennebacher Do you want to have a look at it?

**Comment by etiennebacher** [comment]
I use the same script and the same seed but I don't have the same file order. For example, [here](https://github.com/easystats/insight/actions/runs/4691910035/jobs/8316979135):

* the first is `test-ivreg.R` but mine is `test-ivreg_AER.R`
* then it's the same until `test-format_table.R` which for me is `test-format_table_ci.R`
* etc.

So I can't reproduce all of these failures

**Comment by IndrajeetPatil** [comment]
Hmm, maybe because you are on Windows, and we run the check on Ubuntu for our CI/CD. On macOS, I can reproduce two failures.

I have changed the workflow so that the tests run on Windows. Let's see if we still see any test failures.

**Comment by IndrajeetPatil** [comment]
Yeah, failures are also seen on Windows: https://github.com/easystats/insight/actions/runs/4697252164/jobs/8328125120

Note that the seed is going to be different for each run.

**Comment by etiennebacher** [comment]
> Hmm, maybe because you are on Windows, and we run the check on Ubuntu for our CI/CD. On macOS, I can reproduce two failures.

The problem is not with due to this, it's that before running the tests I can't get the same order as you even if I use exactly the same seed (and I don't know why)

**Comment by strengejacke** [comment]
I see this warning:
> Package `logistf` is loaded and breaks `mmrm::mmrm()` (1)

**Comment by etiennebacher** [comment]
It's not a warning, it's just a skip message. It's because of namespace conflict, cf https://stackoverflow.com/questions/72533745/loading-logistf-breaks-mcmcglmm/72536046

I made a PR upstream but no answer so far https://github.com/georgheinze/logistf/pull/54
