### ISSUE TITLE
Suggestion of new function: `install_if_not_installed()`

### ISSUE THREAD

**Issue by rempsyc** [easystats/insight#799]
# Context

During the review of my rempsyc paper at JOSS, it was pointed out that having to install suggested packages midway through the tutorials was throwing off their workflow, and that there should be a way to install all of them in a single step, indicated at the beginning of the tutorial/vignette. I thought for sure `insight` had such a function, but I could not find it?

So I made a very simple `install_if_not_installed` for convenience.

For example, in one of my tutorial, I use this way:

``` r
# Load necessary libraries
library(performance)
library(see)
# Note: if you haven't installed the packages above,
# you'll need to install them first by using:
install_if_not_installed(c("performance", "see"))
```

This could also be useful when sharing scientific scripts where this could be part of the workflow when sourcing the script, instead of having to manually run the usually commented lines.

---

**Comment by vincentarelbundock** [comment]
I appreciate that this might be useful in some cases, but in general I feel that such functions (like `pacman::p_load()` encourage very bad practice. 

IMHO, a script should never install stuff on the runner's computer automatically (especially not without confirmation).

Plus, people who need this can always write a 2-line function (calling `check_if_installed`) if they really need it for some helper script.

**Comment by etiennebacher** [comment]
You could suggest users to install all dependencies (including suggested packages) with `install.packages("rempsyc", dependencies = TRUE)`, the downside being that you have to download a ton of packages that are not necessarily useful (`insight` has dozens of suggested packages).

**Comment by rempsyc** [comment]
Thanks Vincent, you are making a good point. Etienne I use this workaround in my readme with a warning that it will probably install way more packages than they need, but for the tutorials I was hoping for a piece-meal solution. Daniel you are correct that perhaps the only real difference is the (as Vincent points out, desirable) intermediary step of asking permission, so I’ll close this issue as it would be redundant. Thanks all
