### ISSUE TITLE
model_terms() should return a list

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#8]
See https://github.com/easystats/insight/issues/1#issuecomment-459187565

And maybe get a `flatten`-argument to mimic current behaviour.

**Comment by DominiqueMakowski** [comment]
I'm not sure if I named vector could be a compromise. It's more informative than an unnamed vector, but it's still a bit tedious to retrieve the right value by name:

```r
terms <- c("predictors"=c("A", "B"), "response"="Y")
terms[1] # works as expected
terms$predictors # doens't work
terms[terms="predictors1"]
```

A flatten argument would be an alternative. I am wondering if people that would use the "general" function instead of the specific ones (i.e., find_terms instead of find_predictors) would expect, by default, a list or a vector of terms

**Comment by strengejacke** [comment]
I have revised the functions (will commit later), and some other functions as well.

The problem occurs with mixed models and models with zero inflation part (or combinations). You can now decide whether to retrieve information from fixed, random or all effects. And from conditional, zero inflated, dispersion or all components. I think it makes sense to return this information as list by default.

But what if someone asks for info from zero inflation, model has no such part and returns only info for the conditional model. Should this return a vector then? Or a list with empty elements?

**Comment by DominiqueMakowski** [comment]
I was not aware of this edge case (no experience with zi models), which is indeed important. I'll try to read a bit more about zi models and how the zi formula part can be "confounded" (if I understand correctly) with the random part. Does it make sense to have a `find_zi()` in addition with a `find_random()` (which itself would be different from `find_predictors`?) Or maybe `find_predictors` should return a list with fixed and random sublists? I realise the handling of the rhs is not that clear nor simple in my head...

**Comment by strengejacke** [comment]
This was a rather large commit, implementing some new features and renaming the functions... I'll set up a small rmd-file (maybe RPubs?) to show how functions work. We may add this later as vignette.
