### ISSUE TITLE
Test failure on CRAN

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/insight#801]
Seen only on one platform, so not sure how reliable this failure is.

cf. https://cloud.r-project.org/web/checks/check_results_insight.html

```r
     ══ Failed tests ════════════════════════════════════════════════════════════════
     ── Error ('test-get_varcov.R:10:3'): informative error in get_varcov.default ───
     Error: Unable to extract a variance-covariance matrix for model object of class
     `lmerMod`. Different values of the `vcov` argument trigger calls to the
     `sandwich` or `clubSandwich` packages in order to extract the matrix
     (see `?insight::get_varcov`). Your model or the requested estimation
     type may not be supported by one or both of those packages, or you were
     missing one or more required arguments in `vcov_args` (like `cluster`).
     Backtrace:
     ▆
     1. ├─testthat::expect_equal(...) at test-get_varcov.R:10:2
     2. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
     3. │ └─rlang::eval_bare(expr, quo_get_env(quo))
     4. ├─insight::get_varcov(mod, vcov = "CR0")
     5. └─insight:::get_varcov.default(mod, vcov = "CR0")
     6. └─insight:::.get_varcov_sandwich(...)
     7. └─insight::format_error(msg)
     8. └─insight::format_alert(..., type = "error")
    
     [ FAIL 1 | WARN 0 | SKIP 46 | PASS 2780 ]
```

**Comment by strengejacke** [comment]
hm, none of the directly involved packages have been updated recently. So it seems like it's not an issue of an update that was first build on the Linux system and will continue to fail on other systems, too (I think so).

**Comment by strengejacke** [comment]
Strange, now it's failing on another system, with a completely different error: https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/insight-00check.html

**Comment by IndrajeetPatil** [comment]
Let's give it a couple of days and see if these failures persist. Maybe they are transitory and resolve themselves.

**Comment by strengejacke** [comment]
There seems to be an issue with vcov/crossprod related stuff in the dev-version?
https://github.com/easystats/insight/actions/runs/6130914318/job/16640457172

**Comment by strengejacke** [comment]
Seems resolved from CRAN side.
