### ISSUE TITLE
test code needs glmmTMB

### ISSUE THREAD

**Issue by mebrooks** [easystats/insight#806]
I'm using `revdepcheck` to get ready for a new release of `glmmTMB` and it tells me there's a new error in this package, but I don't see why it would be new (details below). I think the fix is either to add `glmmTMB::` before the call to the function and before`glmmTMBControl` in [this](https://github.com/easystats/insight/blob/6e78a4b5456da6080cf7946e9db4bfb1823bc131/tests/testthat/test-get_variance.R#L299) section of testing, or load the package `glmmTMB` prior to the section.

<details>

* Version: 0.19.5
* GitHub: https://github.com/easystats/insight
* Source code: https://github.com/cran/insight
* Date/Publication: 2023-09-13 13:20:02 UTC
* Number of recursive dependencies: 382

Run `revdepcheck::revdep_details(, "insight")` for more info

</details>

## Newly broken

*   checking tests ...
    ```
      Running ‘testthat.R’
     ERROR
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
      ══ Failed tests ════════════════════════════════════════════════════════════════
      ── Error ('test-get_variance.R:298:3'): fixed effects variance for rank-deficient models, #765 ──
      Error in `glmmTMB(z ~ x1 + x2 + x3 + x4 + (1 | re), data = dd, control = glmmTMBControl(rank_check = "adjust"))`: could not find function "glmmTMB"
      Backtrace:
          ▆
       1. └─testthat::expect_message(...) at test-get_variance.R:298:2
       2.   └─testthat:::expect_condition_matching(...)
       3.     └─testthat:::quasi_capture(...)
       4.       ├─testthat (local) .capture(...)
       5.       │ └─base::withCallingHandlers(...)
       6.       └─rlang::eval_bare(quo_get_expr(.quo), quo_get_env(.quo))
      
      [ FAIL 1 | WARN 2 | SKIP 44 | PASS 2801 ]
      Error: Test failures
      Execution halted
    ```

**Comment by strengejacke** [comment]
Will this line in the DESCRIPTION:

```
Remotes: glmmTMB/glmmTMB/glmmTMB
```

run the correct version from GitHub that will be submitted?

**Comment by strengejacke** [comment]
From our side, you can submit to CRAN. When rev-dep checks fail, just mention that we're informed and have prepared an update that we'll submit once glmmTMB is on CRAN.

**Comment by mebrooks** [comment]
The new version is on CRAN now.
