### ISSUE TITLE
`find_transformation` incorrectly detects power transformations

### ISSUE THREAD

**Issue by bbolker** [easystats/insight#812]
The `find_transformation()` function is looking for a regex  `"I\\((.*)\\^\\s*2\\)"` to identify a power transformation

* transformations of the *response variable* in a formula do not need to be protected by `I()`; the special interpretation of operators `*+^/` only applies to the right-hand side of a formula
* even so, I don't understand the regex here: we need an `I()`-protected quantity raised to a power that ends in 2??
* I don't know how flexible a regex you want, exactly; should probably allow for `^` followed by a quantity that might be in parentheses, `+-`, possible `/`, digits ... decimal points (in case some decides to raise to the 0.5), ... ??? It might be useful to include the rules in the documentation ...

```
library(insight)
find_transformation(lm(Sepal.Length^(1/2) ~ Species, data = iris))
## [1] "identity"
find_transformation(lm(Sepal.Length^2~ Species, data = iris))
## [1] "identity"
find_transformation(lm(I(Sepal.Length^(1/2)) ~ Species, data = iris))
## NULL
 find_transformation(lm(I(Sepal.Length^3) ~ Species, data = iris))
## NULL
find_transformation(lm(I(Sepal.Length^2) ~ Species, data = iris))
## [1] "power"
```

**Comment by strengejacke** [comment]
Now that I have co-pilot and co-pilot chat installed in vscode, I can ask for such a regex pattern ;-) Before, every limitation was due to my lacking regex-skills.

**Comment by strengejacke** [comment]
Relaxing the pattern would increase matches, but are there any cases where this regex pattern returns a false positive?

``` r
m1 <- lm(Sepal.Length^(1 / 2) ~ Species, data = iris)
m2 <- lm(Sepal.Length^2 ~ Species, data = iris)
m3 <- lm(I(Sepal.Length^(1 / 2)) ~ Species, data = iris)
m4 <- lm(I(Sepal.Length^3) ~ Species, data = iris)
m5 <- lm(I(Sepal.Length^2) ~ Species, data = iris)

rv <- insight::find_terms(m1)[["response"]]
grepl("(.*)\\^\\s*\\d+", rv)
#> [1] FALSE

rv <- insight::find_terms(m2)[["response"]]
grepl("(.*)\\^\\s*\\d+", rv)
#> [1] TRUE

rv <- insight::find_terms(m3)[["response"]]
grepl("(.*)\\^\\s*\\d+", rv)
#> [1] FALSE

rv <- insight::find_terms(m4)[["response"]]
grepl("(.*)\\^\\s*\\d+", rv)
#> [1] TRUE

rv <- insight::find_terms(m5)[["response"]]
grepl("(.*)\\^\\s*\\d+", rv)
#> [1] TRUE
```

<sup>Created on 2023-09-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
