### ISSUE TITLE
is_singular with lme models uses a lot of memory

### ISSUE THREAD

**Issue by alejandrocorbellini-ac** [easystats/insight#824]
hi!

I just wanted to report a memory usage issue when calling `get_variance` with a linear mixed effects models. I'm new to R and mixed effects models in general, so sorry if something doesn't make sense.

I noticed that calling `r2_nakagawa` from the `performance` package ends up calling `is_singular` in [helper_functions](https://github.com/easystats/insight/blob/026b973242a39831bd7b8731475086bbd6787a0a/R/helper_functions.R#L302)

In my code, this is the call chain:

`r2_nakagawa -> insight::get_variance -> compute_variances -> is_singular`

This ends up using a lot of memory when creating the diagonal matrix, although I don't know how to fix it. This also affects sjPlot::tab_model when passing an lme model, since internally they also seem to call r2_nakagawa.

Thanks!

**Comment by strengejacke** [comment]
Do you have a reproducible example? Is it in general, or with many parameters or large data sets only?

**Comment by strengejacke** [comment]
_bump_

**Comment by strengejacke** [comment]
Closing for now, please re-open if this issue persists and if a reproducible example can be posted here.
