### ISSUE TITLE
ICC for brms Beta model: returning NA

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#846]
ICC for Beta models just returns NA (no warning or error)

- Works with linear

```r
d <- mtcars
d$wt <- datawizard::normalize(d$wt, include_bounds = FALSE)


m1 <- brms::brm(wt ~ mpg + (1|cyl), data=d)
performance::icc(m1)
```
```
# Intraclass Correlation Coefficient

    Adjusted ICC: 0.438
  Unadjusted ICC: 0.191
```

```r
performance::icc(m1, by_group=TRUE)
```
```
# ICC by Group

Group |   ICC
-------------
cyl   | 0.438
```

- Doesn't with Beta
```r
m2 <- brms::brm(wt ~ mpg + (1|cyl), data=d, family=brms::Beta)

performance::icc(m2)
```
```
NA
```

```r
performance::icc(m2, by_group=TRUE)
```
```
NA
```

**Comment by strengejacke** [comment]
I think the issue is fixed, but not sure whether beta-models work well? See following result:

```r
$var.fixed
[1] 1.408707

$var.random
[1] 0.1716262

$var.residual
[1] NaN

$var.distribution
[1] NaN

$var.dispersion
[1] 0

$var.intercept
      cyl
0.1716262

Warning messages:
1: Model's distribution-specific variance is negative. Results are not
  reliable.
2: In log1p(cvsquared) : NaNs produced
```

**Comment by mattansb** [comment]
> I suppose inverse link transformations won't do the trick?

No, I don't think there's an easy solution that isn't based on a posterior simulation.

**Comment by DominiqueMakowski** [comment]
Just tested again with glmmTMB and 

> Model's distribution-specific variance is negative. Results are not reliable

is thrown too so it might be a general Beta-related problem

**Comment by strengejacke** [comment]
Yes, that's the new message you get for brms as well when you install the PR

**Comment by DominiqueMakowski** [comment]
So this issue can be closed insofar that the brms-related specific issue has been fixed (thanks Daniel!) 
but we should maybe wrote in the ICC docs that for some reason it doesn't work for Beta regressions (regardless of the package)

**Comment by strengejacke** [comment]
`$var.distribution` is negative, sqrt returns NaN then.
The related code starts here:
https://github.com/easystats/insight/blob/6909196509327314b54ae74569aa4cc22da3b6b5/R/compute_variances.R#L601

**Comment by strengejacke** [comment]
See also https://github.com/easystats/insight/issues/764

There are some distributions that are not perfectly validated and may return inaccurate results (or fail)
