### ISSUE TITLE
`insight::find_variables()`: error with `brms` and `mm()`

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#859]
`mm()` is used for multi-membership grouping terms in `brms` models. `insight::find_variables()` sometimes fails with models that include this specification.

Example:

``` r
library(brms)
library(insight)

mtcars$w <- 1
fit <- brm(mpg  ~ 1 + hp  + (1|cyl)  +
                (1|carb:am :hp ) +
                (1|mm(carb, am , weights = cbind(w, w), scale=FALSE)) +
                (1|mm(carb:cyl, am :cyl, weights = cbind(w, w), scale=FALSE)),
              data = mtcars, family = gaussian, chains = 4,
              iter = 100, control = list(adapt_delta = 0.99, max_treedepth = 15),
              cores = 4, seed = 12345,
              backend = "cmdstanr")

find_variables(fit)
```

    Error in if (grepl("gr\\((.*)\\)", re)) {: the condition has length > 1

**Comment by strengejacke** [comment]
Thanks for reporting. If you search for "multimembership", you find some fixme and Todo comments in the code:
https://github.com/search?q=repo%3Aeasystats%2Finsight%20membership%20&type=code

This issue could be related to this, in particular since we have weights.

Let me see if it's easy to fix meanwhile.

**Comment by strengejacke** [comment]
ggpredict(fit, "hp")

**Comment by strengejacke** [comment]
``` r
library(insight)
load("c:/Users/DL/Desktop/fit.RData")
find_variables(fit)
#> $response
#> [1] "mpg"
#> 
#> $conditional
#> [1] "hp"
#> 
#> $random
#> [1] "cyl"  "carb" "am"   "hp"   "w"
```

<sup>Created on 2024-03-20 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

sometimes, `all.vars()` is just magic ;-)
Unfortunately, I cannot use it for `clean_names()` in general, because it splits interaction terms, which is not desired.

**Comment by vincentarelbundock** [comment]
base R for the win (yet again)!

Thanks!

**Comment by strengejacke** [comment]
Unfortunately, this issue just missed the recent submission (three or four days ago), so this patch won't be on CRAN very soon.

**Comment by vincentarelbundock** [comment]
No rush at all. As always, thanks for your great work!

**Comment by strengejacke** [comment]
(p.s. you don't need to close these issues, they'll be closed automatically once I merge the PR 😉)

**Comment by strengejacke** [comment]
Managing GitHub completely from VScode is really amazing

**Comment by vincentarelbundock** [comment]
that's convenient!
