### ISSUE TITLE
`get_priors` for `BFBayesFactor`

### ISSUE THREAD

**Issue by mattansb** [easystats/insight#86]
All `BFBayesFactor` priors are:
- Cauchy distribution
- Location = 0
- Scales can be found [here](https://doi.org/10.1016/j.jmp.2012.08.001) and in e.g., `BFBayesFactor_model@numerator[[model_n]]@prior`.

The **real problem** is that the parameter names (returned by `BayesFactor::posterior`) are weirdly formatted, and thus hard to march to the correct scale.

**Comment by strengejacke** [comment]
Do you have a reprex where it makes sense to extracts priors from `BFBayesFactor`?

**Comment by mattansb** [comment]
I'd have to think about some actual practical uses 😅

Maybe it could be useful to:

1. Extract some parameter posterior from a `BFBayesFactor` with `BayesFactor::posterior`,
1. See what its prior was with `get_priors`,
1. Simulate that prior (e.g., `rcauchy(10000, 0, 0.707)`,
1. Test the posterior against the prior with `bayesfactor_savagedickey`?

Or am I thinking too big?

**Comment by strengejacke** [comment]
No, I meant a running code that generates a BFBayesFactor object with priors, that can be extracted with `get_priors()`, so I have something where I can work on and test the implementation.

**Comment by mattansb** [comment]
Ohh... I have a [`sample_from_priors`](https://github.com/mattansb/BFEffects/blob/master/R/inferBF-utility.R#L3) function that I was trying to build to extract and sample from priors. That could be a good place to start. Feel free to steal any part of it 😊

You can also check out my [discussion with Richard D. Morey on the topic](https://github.com/richarddmorey/BayesFactor/issues/131).

Note that `BFBayesFactor_model@numerator[[model_n]]@prior` is the standardized prior, that would need to be "un-standardized" for any practical use.

**Comment by strengejacke** [comment]
I don't want code that extracts priors, I simply need some BFBayesFactor objects with priors ;-)

**Comment by mattansb** [comment]
It seems you both misunderstood me :)
I merely meant that you can take a look at my `sample_from_priors` function to see how I find in there the correct Cauchy standardized scale (lines 8-11), and how I find the un-standardizing factors for continuous predictors (lines 38-43) and the un-standardizing factor for the DV (line 57).
I hope that was more clear :)

**Comment by strengejacke** [comment]
Yes, I understood everything, yet I need something like a "sample model" where I can write something test-units... :-) Nevertheless. I'll take a look at your code.

**Comment by mattansb** [comment]
``` r
library(BayesFactor)
#> Loading required package: coda
#> Loading required package: Matrix
#> ************
#> Welcome to BayesFactor 0.9.12-4.2. If you have questions, please contact Richard Morey (richarddmorey@gmail.com).
#> 
#> Type BFManual() to open the manual.
#> ************

data(puzzles)
BF_RT <- anovaBF(RT ~ shape*color + ID, data = puzzles, whichRandom = "ID")

data(attitude)
BF_rating <- regressionBF(rating ~ ., data = attitude)
```

<sup>Created on 2019-04-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

How's that?

**Comment by strengejacke** [comment]
Very good! :-D That was what I was looking for.

**Comment by DominiqueMakowski** [comment]
``` r
library(BayesFactor)

model <- BayesFactor::correlationBF(iris$Sepal.Length, iris$Sepal.Width)
insight::get_priors(model)
#> Error in data.frame(parameters = names(prior), distribution = "Cauchy", : arguments imply differing number of rows: 0, 1
```

<sup>Created on 2019-05-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Seems to be broken for correlations
