### ISSUE TITLE
checking diagonal elements of a covariance matrix is insufficient to diagnose singularity

### ISSUE THREAD

**Issue by bbolker** [easystats/insight#878]
`insight` has a [helper function](https://github.com/easystats/insight/blob/026b973242a39831bd7b8731475086bbd6787a0a/R/helper_functions.R#L287) that claims to check singularity of mixed effect models. It does it by checking to see if any of the diagonal elements of the random effects covariance matrix are less than a tolerance value.

This is insufficient for "unstructured" (general positive definite) covariance matrices with dimension > 2 (and maybe >1, I'm not sure).

See https://github.com/easystats/performance/pull/684

* The most general (but least efficient) check is to extract the covariance matrice(s) and see if any of their eigenvalues are less than a tolerance.
* for `lme4`, which parameterizes the covariance matrices by their Cholesky factor, checking the diagonal elements is sufficient
* if the covariance structure is known to have a special form (e.g. diagonal!) then one may be able to check more easily.

```[tasklist]
### Tasks
```

**Comment by strengejacke** [comment]
We have an improved implementation in the _performance_ package: https://github.com/easystats/performance/blob/main/R/check_singularity.R

Maybe we should this code instead?

**Comment by bwiernik** [comment]
That's a good idea

**Comment by bbolker** [comment]
in `compute_variances`, [here](https://github.com/easystats/insight/blob/24c23c4cb970bd3149e25206f3bdcb5d3b1b5617/R/compute_variances.R#L39)

**Comment by strengejacke** [comment]
I re-opened after merging the PR, because I still want to add some tests.

**Comment by strengejacke** [comment]
I think it's ok to rely on tests in _performance_, since _insight_ now just calls `performance::check_singularity()`.

**Comment by bbolker** [comment]
For it's worth it's not obvious why [this line](https://github.com/easystats/performance/blob/106a665e59a4b433b5b7caf296985a08a2eda976/R/check_singularity.R#L140) uses `abs()` in  `any(abs(theta[diag.element]) < tolerance)`, as these elements are guaranteed to be non-negative ... (harmless though)
