### ISSUE TITLE
`find_formula` random inconstancy

### ISSUE THREAD

**Issue by mattansb** [easystats/insight#88]
When there is more that one random variable, `find_formula()$random` is a list of formulas, but when there is only one, it is a formula.
``` r
library(lmerTest)
#> Loading required package: lme4
#> Loading required package: Matrix
#> 
#> Attaching package: 'lmerTest'
#> The following object is masked from 'package:lme4':
#> 
#>     lmer
#> The following object is masked from 'package:stats':
#> 
#>     step
mo1 <- lmer(Sepal.Length ~ (1|Species), data = iris)
mo2 <- lmer(Sepal.Length ~ (1|Species) + (1|Petal.Length), data = iris)

insight::find_formula(mo1)
#> $conditional
#> Sepal.Length ~ (1 | Species)
#> <environment: 0x000000001498b450>
#> 
#> $random
#> ~1 | Species
#> <environment: 0x00000000149a4560>
insight::find_formula(mo2)
#> $conditional
#> Sepal.Length ~ (1 | Species)
#> <environment: 0x0000000014a22008>
#> 
#> $random
#> $random[[1]]
#> ~1 | Species
#> <environment: 0x0000000014a4f828>
#> 
#> $random[[2]]
#> ~1 | Petal.Length
#> <environment: 0x0000000014a56d00>
```

<sup>Created on 2019-04-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Is it possible to have it always be a list? (in the case of a single random variable, a list of length 1?)

I'm trying to use this function internally in the [bayesfactor functions](https://github.com/easystats/bayestestR/issues/80), and I can't seem to figure a way to generalize to both cases. Any ideas?

**Comment by strengejacke** [comment]
Yes, it's a bit annoying sometime, but having a list in a list for just one element looks strange to me...
Currently, what you can do is to check for a list:

`is.list(find_formula(model)$random)`, this is also the way how it's checked for `find_random()`.

**Comment by mattansb** [comment]
Ah, that works perfect! Thanks!
