### ISSUE TITLE
replace zi by component

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#9]
functions like `model_predictors()`, that have a `zi`-argument, could get a `component`-argument instead, so the user can either return values _excluding_ zi-part, _only_ zi part or from both conditional and zi-part of a model.

**Comment by DominiqueMakowski** [comment]
To be honest I've never really worked with zero-inflated models so I don't think I can bring anything valuable :/ (but a parameter named `component` sounds more explicit than `zi` (it might also be me that particularly doesn't like very short shortcuts :))
