### ISSUE TITLE
expected behaviour for null-models

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#92]
@DominiqueMakowski @mattansb @pdwaggoner 

Currently, `find_terms()` returns a `"1"` for null-models, and `clean_names()` does so, too. For `find_terms()`, I think it makes sense because it indicates that there is only an intercept, for `clean_names()` it makes less sense to me...

What do you think? Which behaviour is desirable?

``` r
# the very latest GitHub, clean_names was revised to not return "1"
library(insight)
m <- lm(mpg ~ 1, data = mtcars)

clean_names(m)
#> [1] "mpg"

find_terms(m)
#> $response
#> [1] "mpg"
#> 
#> $conditional
#> [1] 1
```

<sup>Created on 2019-05-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Should:

1) `clean_names()` return `"mpg"` _and_ `"1"`?
2) `find_terms()` _not_ return `"1"`?
3) keep it as in the above example?

**Comment by strengejacke** [comment]
`find_predictors()` would also return `1`:

``` r
library(insight)
m <- lm(mpg ~ 1, data = mtcars)

find_predictors(m)
#> $conditional
#> [1] 1
```

<sup>Created on 2019-05-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by strengejacke** [comment]
ok, "1" is not a predictor... So I would change this behaviour

**Comment by mattansb** [comment]
I think `clean_names` shouldn't as I think its primary function would be to locate variables (e.g., in data frames), and "1" will never be a variable to be located.

Regarding non null-models, I would maybe argue that "1" should always be returned by `find_terms` and `find_predictors`. I,  for one, would expect these to return something different:

``` r
library(insight)
m0cyl <- lm(mpg ~ 0 + cyl, data = mtcars)
m1cyl <- lm(mpg ~ cyl, data = mtcars)
  
clean_names(m0cyl)
#> [1] "mpg" "cyl"
clean_names(m1cyl)
#> [1] "mpg" "cyl"

find_terms(m0cyl)
#> $response
#> [1] "mpg"
#> 
#> $conditional
#> [1] "cyl"
find_terms(m1cyl)
#> $response
#> [1] "mpg"
#> 
#> $conditional
#> [1] "cyl"
```

<sup>Created on 2019-05-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by strengejacke** [comment]
I think this is perfect in line with the terminology. Both models have _one predictor_, but the first model has _one_ **parameter**, while the second model has _two_ **parameters**.

**Comment by DominiqueMakowski** [comment]
I agree.

**Comment by mattansb** [comment]
Oh, sorry, didn't realize we have `find_parameters`!

But still think clean_names shouldn't return "1" (:

**Comment by strengejacke** [comment]
to have more convenient checks, I added to methods:
[`is_nullmodel()`(https://easystats.github.io/insight/reference/is_nullmodel.html) and [`has_intercept()`](https://easystats.github.io/insight/reference/has_intercept.html).

**Comment by pdwaggoner** [comment]
Sorry to be late here, but I too agree with @mattansb re: `clean_names`. 1 is never a predictor.

**Comment by strengejacke** [comment]
Yes, I think all functions are now in line with this "design" decision...
