### ISSUE TITLE
get_variance() returns NULL when modeling variance in brms

### ISSUE THREAD

**Issue by matschmitz** [easystats/insight#924]
The get_variance() function returns NULL when used with brms models that include a formula for modeling variance (e.g., sigma ~ cyl). 

```
library(brms)
library(insight) #v0. 20.4

m <- brm(bf(mpg ~ hp + (1 | cyl), sigma ~ cyl),
         data = mtcars, seed = 123)
get_variance(m)  # Unexpectedly returns NULL
```

**Comment by mattansb** [comment]
When `sigma` is modeled, there is no longer a sigma parameter - but a group of parameters that, given a set of $X$s can give a conditional sigma (in your example, conditional on `cyl`).

You can get those parameter with `get_parameters()`:

```R
get_parameters(m, parameters = "b_sigma") |> head()
#>   b_sigma_Intercept b_sigma_cyl
#> 1          2.022491 -0.11308296
#> 2          1.888756 -0.10069295
#> 3          1.572057 -0.04198636
#> 4          1.871757 -0.12676263
#> 5          2.527588 -0.20649596
#> 6          2.125739 -0.13128921
```

**Comment by matschmitz** [comment]
Also, `get_variance_reaidual(m)` returns
```
var.residual
           1
```

Which seems to be incorrect.

**Comment by mattansb** [comment]
> Is there a way to compute the total sigma in those cases?

What is total sigma?

> Also, get_variance_reaidual(m) returns
> ```
> var.residual
>            1
> ```
> Which seems to be incorrect.

Yes, this should return `NULL` or fail somehow.
