### ISSUE TITLE
Dealing with splines::bs

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#93]
```r
model <- lm(Sepal.Length ~ splines::bs(Petal.Width, df=4), data=iris)
insight::get_data(model)
```
```
 Error in `[.data.frame`(md, , needed.vars, drop = FALSE) : 
  undefined columns selected 
```

It works with `poly` though.

**Comment by strengejacke** [comment]
And without `splines::`?

**Comment by DominiqueMakowski** [comment]
That works. Do we want to make it work or throw an informative error?

**Comment by strengejacke** [comment]
I'll try to make it work...

**Comment by strengejacke** [comment]
And then maybe release mid of may?

**Comment by DominiqueMakowski** [comment]
for the 0.3.0?

**Comment by strengejacke** [comment]
Yes... We have made some critical big fixes and other easystats packages rely on those fixes. Or would you say we should probably wait for JOSS?

**Comment by DominiqueMakowski** [comment]
Good question. I think we can update the CRAN release now, as we haven't received JOSS' reviews yet. These updates are important for the releases/updates of bayestestR parameters etc.
