### ISSUE TITLE
`display()` example loses linebreaks

### ISSUE THREAD

**Issue by d-morrison** [easystats/insight#931]
Here's how the example looks right now:

![image](https://github.com/user-attachments/assets/d20b3083-a089-4733-995e-e44bb8f05699)

Rstudio version info:

![image](https://github.com/user-attachments/assets/5216917c-7379-4ade-b769-e0edea3e7bf4)

**Comment by bwiernik** [comment]
Set the code chunk in your document to use "as-is" output

**Comment by strengejacke** [comment]
I think this refers to the help, see `?insight::display`, and the option in IDEs to run examples. Usually, the output is an HTML page, here the default is the markdown table, where new-lines (`\n`) are ignored in HTML.
