### ISSUE TITLE
Codecov

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#94]
@DominiqueMakowski do you know why codecov badge is not updated?

**Comment by DominiqueMakowski** [comment]
https://codecov.io/gh/easystats/insight/branches Indeed it reads "last updated a month ago"

**Comment by DominiqueMakowski** [comment]
everything seems in order in the travis.yml file

**Comment by DominiqueMakowski** [comment]
I think it solved (added back covr to deps)
