### ISSUE TITLE
Handle Box-Cox transformation

### ISSUE THREAD

**Issue by JoakimStefansson** [easystats/insight#940]
### Background
A reasonably common type of transformation is the Box-Cox transformation.
The transformed formula looks something like this:
`lm(((y^lambda-1)/lambda) ~ x)`
where lambda is a number, usually between -3 and 3.
### Problem
This transformation is not handled correctly in insight::get_transformation():
```
a<-aov(formula=(mpg^0.7-1)/0.7~hp, data=mtcars)
insight::get_transformation(a)
#Error in switch(trans_power, `0.5` = list(transformation = function(x) x^0.5,  : 
#                                            EXPR must be a length 1 vector
```
I don't think the Box-Cox transformation is handled by other functions, such as performance::performance_aicc(), either.

### Suggestion
I suggest support for the Box-Cox transformation is added. 
The inverse transformation is `exp(log(1 + lambda * yt)/lambda)`, where yt is the transformed response variable. 
But maybe the correction of log-likelihoods is different from, and a more complicated matter than, the inverse transformations of values.

**Comment by strengejacke** [comment]
What would be the inverse transformation?

**Comment by bwiernik** [comment]
exp(log(1 + lambda * yt)/lambda)

**Comment by strengejacke** [comment]
Thanks! Just realized it's also mentioned in the initial post...
