### ISSUE TITLE
Improvement in how get_transformation() deals with power transformations

### ISSUE THREAD

**Issue by JoakimStefansson** [easystats/insight#941]
### Background
The behaviour of get_transformation() to determine the transformation and inversion functions of transformed responses in a handful of hard-coded steps is surprising to me.
This is related to the issue #940, but might impede other uses as well.

### Suggestion
I suggest to replace this code:
```
  else if (transform_fun == "power") {
    trans_power <- .safe(gsub("\\(|\\)", "", gsub("(.*)(\\^|\\*\\*)\\s*(\\d+|[()])", 
      "\\3", find_terms(x)[["response"]])))
    if (is.null(trans_power)) {
      trans_power <- "2"
    }
    out <- switch(trans_power, `0.5` = list(transformation = function(x) x^0.5, 
      inverse = function(x) x^2), `3` = list(transformation = function(x) x^3, 
      inverse = function(x) x^(1/3)), `4` = list(transformation = function(x) x^4, 
      inverse = function(x) x^0.25), `5` = list(transformation = function(x) x^5, 
      inverse = function(x) x^0.2), list(transformation = function(x) x^2, 
      inverse = sqrt))
  }
```
, that is rows 31 to 43 in insight::get_transformation(), with something like this code:
```
  else if (transform_fun == "power") {
    trans_power <- .safe(gsub("\\(|\\)", "", gsub("(.*)(\\^|\\*\\*)\\s*(\\d+|[()])", 
      "\\3", find_terms(x)[["response"]])))
    if (is.null(trans_power)) {
      trans_power <- "2"
    }
    if (trans_power==0) {
out <- NULL } else{
out<-list(
  transformation = function(x) x ^ as.numeric(trans_power), inverse= function(x) x ^ (as.numeric(trans_power)^-1)
)
}
  }
```
The only changes are in the `out <- `but I included the whole `if`. I hope it's clear.

To the best of my understanding, that should catch and invert any power function. 
I don't know if the functions in `out` created this way will be OK to use downstream, and I can't easily test it from here, but I'm guessing it can be solved by the package experts.

**Comment by strengejacke** [comment]
I'm not sure this will work, because `trans_power` will be an unknown token/object.

**Comment by strengejacke** [comment]
``` r
out<-list(
  transformation = function(x)x^ as.numeric(trans_power),
  inverse = function(x) x^(as.numeric(trans_power)^-1)
)
out$transformation(5)
#> Error in out$transformation(5): object 'trans_power' not found
```

<sup>Created on 2024-10-18 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by JoakimStefansson** [comment]
OK. I believe that this should work better:
` out<-list(
    transformation = eval(parse(text=paste0("function(x)x^", as.character(as.numeric(trans_power))))),
    inverse = eval(parse(text=paste0("function(x) x^(",as.character(as.numeric(trans_power)),"^-1)")))
  )`

This is the test I have made, that makes me think the formulas are now being passed on with numbers, without relying on the existence of `trans_power ` any more:

```
rm(list=ls())
test<-function(){
  trans_power<-as.character(sample(-50:50, size=1)/10)
  out<-list(
    transformation = eval(parse(text=paste0("function(x)x^", as.character(as.numeric(trans_power))))),
    inverse = eval(parse(text=paste0("function(x) x^(",as.character(as.numeric(trans_power)),"^-1)")))
  )
print(  out$transformation(5))
  return(out)}
test()
```
