### ISSUE TITLE
rstanarm and brms diagnostic file

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#95]
to compute BFs from models, additional parameters have to be added:
  - `brmsfit` models **must** have been fitted with `save_all_pars = TRUE`
  - `stanreg` models **must** have been fitted with a defined `diagnostic_file`.

Maybe we could add in model_info or in get_algorithm the information about whether this information is available. 

For us, this could be used to eventually, down the road, think about adding some default BF to model_performance or compare_performance if this information is available.

**Comment by strengejacke** [comment]
I think since this is more an information that a sampling-thing, `get_algorithm()` is not the right place for it. But what about another small helper-function, like `has_intercept()` or `is_nullmodel()`, something like `has_bfinfo()` or something?

**Comment by DominiqueMakowski** [comment]
`has_diagnosticfile`? As maybe this thing is also used for other things than BFs?

**Comment by mattansb** [comment]
Maybe `has_diagnosticinfo`? This extra data is also used for other things.

Note that for `stanreg`, the function would also have to check if there is a pointer to the file, *and* if it actually exists.

**Comment by DominiqueMakowski** [comment]
👍

**Comment by strengejacke** [comment]
I'm not sure if this information is easily available... I checked the source from `brms::bridge_sampler()`, and this function does not check for `save_all_pars`, but waits until `bridgesampler()` fails. So it seems to me that the only way to check if `save_all_vars` was set to `TRUE` is to wait for `bridgesampler()` to fail, and that there is ni apriori-check.

**Comment by mattansb** [comment]
I suspected as much, due to the very vague error `brms::bridge_sampler` returns... :/
