### ISSUE TITLE
Update `get_datagrid(<marginaleffects>)` for structural changes in 0.24.0

### ISSUE THREAD

**Issue by mattansb** [easystats/insight#978]
Previously the `get_datagrid(<marginaleffects>)` function relied on the `attr(mfx, "newdata")` attribute, but in the newer version `{marginaleffects}` this attributed seems to no long be available when the `newdata=` argument isn't explicitly set.

@vincentarelbundock Is this intentional? If so, I'm trying to figure out what the best course of action is here to get the relevant column names (those that contain the data id-ing the rows, and not the statistical results).

Is the new `attr(mfx, "original") |> colnames()` appropriate to use here? Or `attr(mfx, "newdata_variable_class") |> names()`?

Please advise.

---

- [ ] Need to also write (better?) tests to catch such changes?

**Comment by vincentarelbundock** [comment]
Ooops, nope, that was totally unintentional! Sorry!

(I'll blame @grantmcdermott and his preference for "lean" objects j/k )

Should be fixed in Github `main` now. I plan to release to CRAN in the next few weeks.

Sorry again for the trouble!

**Comment by grantmcdermott** [comment]
Ugh, sorry.

But does this affect regular (non-lean) objects too? That shouldn't be the case, right?

**Comment by vincentarelbundock** [comment]
The issue was that we (probably me; I didn`t check git blame) reassigned the `newdata` attribute in `slopes()`, and the value was sometimes `NULL`. Now we just delegate lean and non-lean handling to `comparisons()`.

Was just poking fun.

**Comment by strengejacke** [comment]
Thanks for clarification! So nothing needs to be done from _insight_ side?

**Comment by vincentarelbundock** [comment]
Nope. Should be fixed in the next release of `marginaleffects`. Can close this.

**Comment by mattansb** [comment]
Nothing like this happening as I'm live demoing some code in class 😅

**Comment by mattansb** [comment]
(Opening this because I still want to add a test.)
